/* eslint-disable */
function ba(){this.va=!1;this.Z=null;this.wd=void 0;this.Y=1;this.vc=this.Kd=0;this.ra=null}function da(a){if(a.va)throw new TypeError("Generator is already running");a.va=!0}ba.prototype.wa=function(a){this.wd=a};ba.prototype.ya=function(a){this.ra={Xd:a,ue:!0};this.Y=this.Kd||this.vc};ba.prototype.return=function(a){this.ra={return:a};this.Y=this.vc};function na(a){this.o=new ba;this.Je=a}na.prototype.wa=function(a){da(this.o);if(this.o.Z)return qa(this,this.o.Z.next,a,this.o.wa);this.o.wa(a);return sa(this)};
function ta(a,c){da(a.o);var d=a.o.Z;if(d)return qa(a,"return"in d?d["return"]:function(g){return{value:g,done:!0}},c,a.o.return);a.o.return(c);return sa(a)}na.prototype.ya=function(a){da(this.o);if(this.o.Z)return qa(this,this.o.Z["throw"],a,this.o.wa);this.o.ya(a);return sa(this)};
function qa(a,c,d,g){try{var t=c.call(a.o.Z,d);if(!(t instanceof Object))throw new TypeError("Iterator result "+t+" is not an object");if(!t.done)return a.o.va=!1,t;var p=t.value}catch(k){return a.o.Z=null,a.o.ya(k),sa(a)}a.o.Z=null;g.call(a.o,p);return sa(a)}
function sa(a){for(;a.o.Y;)try{var c=a.Je(a.o);if(c)return a.o.va=!1,{value:c.value,done:!1}}catch(d){a.o.wd=void 0,a.o.ya(d)}a.o.va=!1;if(a.o.ra){c=a.o.ra;a.o.ra=null;if(c.ue)throw c.Xd;return{value:c.return,done:!0}}return{value:void 0,done:!0}}function wa(a){this.next=function(c){return a.wa(c)};this.throw=function(c){return a.ya(c)};this.return=function(c){return ta(a,c)};this[Symbol.iterator]=function(){return this}}
function Aa(a){function c(g){return a.next(g)}function d(g){return a.throw(g)}return new Promise(function(g,t){function p(k){k.done?g(k.value):Promise.resolve(k.value).then(c,d).then(p,t)}p(a.next())})}function Ca(a){var c=new XMLHttpRequest;c.open("GET",b.bc+b.neuralNetworkPath,!0);c.withCredentials=!1;c.onreadystatechange=function(){4!==c.readyState||200!==c.status&&0!==c.status||a(c.responseText)};c.send()}function Da(){for(var a=b.Uc,c=Array(a),d=0;d<a;++d)c[d]=0;return c}
function Ha(a,c){if(0===c||"object"!==typeof a)return a;a=Object.assign({},a);c=void 0===c||-1===c?-1:c-1;for(var d in a)a[d]=Ha(a[d],c);return a}function Ia(a,c,d){a=Math.min(Math.max((d-a)/(c-a),0),1);return a*a*(3-2*a)}function Ja(a,c,d){return Math.min(Math.max((d-a)/(c-a),0),1)}function Ka(a,c,d,g){return Math.pow(Math.min(Math.max((g-a)/(c-a),0),1),d)}
function Oa(a){switch(a){case "relu":return"gl_FragColor=max(vec4(0.,0.,0.,0.),gl_FragColor);";case "elu":return"gl_FragColor=mix(exp(-abs(gl_FragColor))-vec4(1.,1.,1.,1.),gl_FragColor,step(0.,gl_FragColor));";case "elu01":return"gl_FragColor=mix(0.1*exp(-abs(gl_FragColor))-vec4(0.1,0.1,0.1,0.1),gl_FragColor,step(0.,gl_FragColor));";case "arctan":return"gl_FragColor=atan(3.14159265359*texture2D(u0,vUV))/3.14159265359;";case "copy":return"";default:return!1}}
function Pa(a,c){var d=c%8;return a[(c-d)/8]>>7-d&1}
function Qa(a){var c=JSON.parse(a);a=c.ne;var d=c.nf,g=c.n;var t="undefined"===typeof btoa?Buffer.from(c.data,"base64").toString("latin1"):atob(c.data);var p=t.length;c=new Uint8Array(p);for(var k=0;k<p;++k)c[k]=t.charCodeAt(k);t=new Float32Array(g);p=new Float32Array(d);k=a+d+1;for(var r=0;r<g;++r){for(var f=k*r,v=0===Pa(c,f)?1:-1,z=f+1,m=1,l=0,x=z+a-1;x>=z;--x)l+=m*Pa(c,x),m*=2;z=l;f=f+1+a;m=p.length;l=0;for(x=f;x<f+m;++x)p[l]=Pa(c,x),++l;for(m=f=0;m<d;++m)f+=p[m]*Math.pow(2,-m-1);t[r]=0===f&&0===
z?0:v*(1+f)*Math.pow(2,1+z-Math.pow(2,a-1))}return t}
var F=function(){function a(u,q,C){q=u.createShader(q);u.shaderSource(q,C);u.compileShader(q);return u.getShaderParameter(q,u.COMPILE_STATUS)?q:!1}function c(u,q,C){q=a(u,u.VERTEX_SHADER,q);C=a(u,u.FRAGMENT_SHADER,C);u===D&&k.push(q,C);var M=u.createProgram();u.attachShader(M,q);u.attachShader(M,C);u.linkProgram(M);return M}function d(u,q){q.B=q.B?!0:!1;if(!q.B){void 0===q.za&&(q.za="precision lowp float;attribute vec2 a0;varying vec2 vv0;void main(){gl_Position=vec4(a0,0.,1.),vv0=a0*.5+vec2(.5,.5);}");void 0===
q.Da&&(q.Da=["a0"]);void 0===q.sa&&(q.sa=[2]);if(void 0===q.precision||"highp"===q.precision)q.precision=m;q.id=v++;void 0!==q.ld&&(q.ld.forEach(function(M,S){q.h=q.h.replace(M,q.Ya[S])}),q.ld.splice(0));q.ac=0;q.sa.forEach(function(M){q.ac+=4*M});q.da=c(u,q.za,"precision "+q.precision+" float;\n"+q.h);q.v={};q.i.forEach(function(M){q.v[M]=u.getUniformLocation(q.da,M)});q.attributes={};q.ta=[];q.Da.forEach(function(M){var S=u.getAttribLocation(q.da,M);q.attributes[M]=S;q.ta.push(S)});if(q.j){u.useProgram(q.da);
f=q;r=q.id;for(var C in q.j)u.uniform1i(q.v[C],q.j[C])}q.ca=!0}}function g(u){Ra.af(I);r!==u.id&&(I.N(),r=u.id,f=u,D.useProgram(u.da),u.ta.forEach(function(q){0!==q&&D.enableVertexAttribArray(q)}))}function t(u,q,C){d(u,q,C);u.useProgram(q.da);u.enableVertexAttribArray(0);r=-1;return f=q}function p(){return{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",i:["u1"],j:{u1:0}}}var k=[],r=-1,f=null,v=0,z=!1,m="highp",l=["u1"],x=["u0"],y={u1:0},h={u0:0},n={u1:0,u2:1},
K={u3:0},H={s0:p(),s1:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",i:l,j:y,precision:"lowp"},s2:{h:"uniform sampler2D u1,u2;varying vec2 vv0;void main(){vec4 a=texture2D(u2,vv0),b=texture2D(u1,vv0);gl_FragColor=a*b;}",i:["u1","u2"],j:n},s3:{h:"uniform sampler2D u1;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u1,vv0);gl_FragColor=a.r*f;}",i:l,j:y},s4:{h:"uniform sampler2D u1,u2;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u2,vv0),b=texture2D(u1,vv0);gl_FragColor=a.a*b.r*f;}",
i:["u1","u2"],j:n},s5:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vec2(1.-vv0.x,vv0.y));}",i:l,j:y},s6:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vec2(vv0.x,1.-vv0.y));}",i:l,j:y},s7:{h:"uniform sampler2D u0;uniform float u4;varying vec2 vv0;void main(){vec4 a=texture2D(u0,vv0);gl_FragColor=a*u4;}",i:["u0","u4"],j:h},s8:{h:"uniform sampler2D u0;uniform float u4;varying vec2 vv0;const vec4 f=vec4(.25,.25,.25,.25),g=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0);float b=dot(a*u4,f);gl_FragColor=b*g;}",
i:["u0","u4"],j:h},s9:{h:"uniform sampler2D u1;varying vec2 vv0;const vec4 e=vec4(1.,1.,1.,1.);void main(){float a=.25*dot(e,texture2D(u1,vv0));gl_FragColor=a*e;}",i:l,j:y},s10:{h:"uniform sampler2D u1,u5;uniform float u6;const vec4 f=vec4(1.,1.,1.,1.);varying vec2 vv0;void main(){vec4 a=texture2D(u1,vv0),b=texture2D(u5,vv0);gl_FragColor=mix(b,a,u6*f);}",i:["u1","u5","u6"],j:{u1:0,u5:1}},s11:{h:"uniform sampler2D u1;uniform vec2 u7;varying vec2 vv0;void main(){gl_FragColor=.25*(texture2D(u1,vv0+u7)+texture2D(u1,vv0+u7*vec2(1.,-1.))+texture2D(u1,vv0+u7*vec2(-1.,-1.))+texture2D(u1,vv0+u7*vec2(-1.,1.)));}",
i:["u1","u7"],j:y},s12:{h:"uniform sampler2D u1;uniform vec4 u8;varying vec2 vv0;float g(float a,float b){a=floor(a)+.5;return floor(a/exp2(b));}float h(float a,float b){return floor(a*exp2(b)+.5);}float i(float a,float b){return mod(a,h(1.,b));}float e(float c,float a,float b){a=floor(a+.5),b=floor(b+.5);return i(g(c,a),b-a);}vec4 j(float a){if(a==0.)return vec4(0.,0.,0.,0.);float k=128.*step(a,0.);a=abs(a);float c=floor(log2(a)),l=c+127.,b=(a/exp2(c)-1.)*8388608.,d=l/2.,m=fract(d)*2.,n=floor(d),o=e(b,0.,8.),p=e(b,8.,16.),q=m*128.+e(b,16.,23.),r=k+n;return vec4(o,p,q,r)/255.;}void main(){float a=dot(texture2D(u1,vv0),u8);gl_FragColor=j(a);}",
i:["u1","u8"],j:y},s13:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 e=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),b=e/(e+exp(-a));gl_FragColor=b;}",i:x,j:h,B:!0},s14:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(0.,0.,0.,0.);void main(){vec4 a=texture2D(u0,vv0);gl_FragColor=max(f,a);}",i:x,j:h},s15:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0);gl_FragColor=mix(exp(-abs(a))-f,a,step(0.,a));}",i:x,j:h},
s16:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),b=exp(-abs(a))-f;gl_FragColor=mix(.1*b,a,step(0.,a));}",i:x,j:h},s17:{h:"uniform sampler2D u0,u6,u9;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),c=texture2D(u6,vv0),d=texture2D(u9,vv0),b=a/d;gl_FragColor=c*mix(exp(-abs(b))-f,b,step(0.,a));}",i:["u0","u6","u9"],j:{u0:0,u6:1,u9:2},B:!0},s18:{h:"uniform sampler2D u0;const float e=3.141593;varying vec2 vv0;void main(){gl_FragColor=atan(e*texture2D(u0,vv0))/e;}",
i:x,j:h},s19:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),b=log(f+a);gl_FragColor=b;}",i:x,j:h,B:!0},s20:{h:"uniform sampler2D u0,u10;uniform float u11;const vec2 e=vec2(.5,.5);const float f=1e-5;const vec4 g=vec4(1.,1.,1.,1.),i=vec4(0.,0.,0.,0.);varying vec2 vv0;void main(){vec4 a=texture2D(u10,e);float b=u11*u11;vec4 c=max(b*a,f*g);gl_FragColor=texture2D(u0,vv0)/c;}",i:["u0","u10","u11"],j:{u0:0,u10:1},B:!0},s21:{h:"uniform sampler2D u1;uniform vec2 u12;varying vec2 vv0;void main(){float a=u12.x*u12.y;vec2 b=floor(vv0*a)/a,c=fract(vv0*a),d=floor(b*u12.y),f=floor(u12.x*fract(b*u12.y)),g=(f*u12.y+d)/a;gl_FragColor=texture2D(u1,g+c/a);}",
i:["u1","u12"],j:y},s22:{h:"uniform sampler2D u13,u14,u15;varying vec2 vv0;void main(){vec4 a=texture2D(u15,vv0);vec2 b=a.rg,c=a.ba;vec4 d=texture2D(u13,b),f=texture2D(u14,c);gl_FragColor=d*f;}",i:["u13","u14","u15"],j:{u14:0,u13:1,u15:2},B:!0},s23:{h:"uniform float u16;uniform sampler2D u13,u14;varying vec2 vv0;void main(){vec2 a=fract(vv0*u16);vec4 b=texture2D(u13,vv0),c=texture2D(u14,a);gl_FragColor=b*c;}",i:["u14","u13","u16"],j:{u14:0,u13:1}},s24:{h:"uniform float u16;uniform sampler2D u13,u14,u17,u18,u19,u20;varying vec2 vv0;const vec4 e=vec4(1.,1.,1.,1.),g=vec4(1e-3,1e-3,1e-3,1e-3);void main(){vec2 h=vv0*u16,l=floor(h),c=h-l;vec4 m=texture2D(u13,vv0),d=texture2D(u14,c),a=texture2D(u20,vv0);a=a*255.;vec4 n=texture2D(u17,c),o=texture2D(u18,c),p=texture2D(u19,c),i=step(-g,-a),b=e-i,j=b*step(-e-g,-a);b*=e-j;vec4 k=b*step(-2.*e-g,-a);b*=e-k;vec4 q=b;d=i*d+j*n+k*o+q*p,gl_FragColor=m*d;}",
i:"u13 u14 u16 u20 u17 u18 u19".split(" "),j:{u14:0,u13:1,u20:3,u17:4,u18:5,u19:6},B:!0},s25:{h:"uniform sampler2D u13,u14,u21;uniform float u16,u22,u23,u24;varying vec2 vv0;const vec2 j=vec2(1.,1.);void main(){vec2 a=floor(u22*vv0),b=u22*vv0-a;float c=u16/u22;vec2 d=floor(b*c),f=b*c-d,g=(a+f)/u22;float k=u22*u24/u16;vec2 l=k*d,h=(l+f*u23)/u24,i=step(h,j);vec4 m=texture2D(u13,g),n=texture2D(u14,h),o=m*n*i.x*i.y,p=texture2D(u21,g);gl_FragColor=o*u23*u23+p;}",i:"u13 u14 u16 u22 u23 u24 u21".split(" "),
j:{u14:0,u13:1,u21:2}},s26:{h:"uniform sampler2D u13,u14;varying vec2 vv0;void main(){vec4 a=texture2D(u13,vv0),b=texture2D(u14,vv0);gl_FragColor=a*b;}",i:["u13","u14"],j:{u14:0,u13:1},B:!0},s27:{h:"uniform sampler2D u1,u21;uniform float u25;varying vec2 vv0;void main(){gl_FragColor=texture2D(u21,vv0)+u25*texture2D(u1,vv0);}",i:["u1","u21","u25"],j:{u1:0,u21:1}},s28:{h:"varying vec2 vv0;uniform sampler2D u1;const vec4 f=vec4(1.,1.,1.,1.),g=vec4(.299,.587,.114,0.);void main(){vec4 a=texture2D(u1,vv0);gl_FragColor=dot(a,g)*f;}",
i:l,j:y,precision:"lowp"},s29:{h:"varying vec2 vv0;uniform sampler2D u1;uniform float u26;const vec3 f=vec3(.299,.587,.114);void main(){vec3 a=texture2D(u1,vv0).rgb,b=texture2D(u1,vv0+vec2(0.,u26)).rgb,c=texture2D(u1,vv0+vec2(u26,u26)).rgb,d=texture2D(u1,vv0+vec2(u26,0.)).rgb;gl_FragColor=vec4(dot(a,f),dot(b,f),dot(c,f),dot(d,f));}",i:["u1","u26"],j:y,precision:"lowp"},s30:{h:"varying vec2 vv0;uniform sampler2D u1;uniform float u26;const vec3 f=vec3(.299,.587,.114);void main(){vec3 a=texture2D(u1,vv0).rgb,b=texture2D(u1,vv0+vec2(0.,u26)).rgb,c=texture2D(u1,vv0+vec2(u26,u26)).rgb,d=texture2D(u1,vv0+vec2(u26,0.)).rgb;gl_FragColor=vec4(a.r,b.g,c.b,dot(d,f));}",
i:["u1","u26"],j:y,precision:"lowp"},s31:{h:"varying vec2 vv0;uniform sampler2D u1,u2;uniform float u27;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=vec4(0.);a-=texture2D(u1,vec2(vv0.x-u27,vv0.y-u27))*1.,a-=texture2D(u1,vec2(vv0.x-u27,vv0.y))*2.,a-=texture2D(u1,vec2(vv0.x-u27,vv0.y+u27))*1.,a+=texture2D(u1,vec2(vv0.x+u27,vv0.y-u27))*1.,a+=texture2D(u1,vec2(vv0.x+u27,vv0.y))*2.,a+=texture2D(u1,vec2(vv0.x+u27,vv0.y+u27))*1.;vec4 b=vec4(0.);b-=texture2D(u1,vec2(vv0.x-u27,vv0.y-u27))*1.,b-=texture2D(u1,vec2(vv0.x,vv0.y-u27))*2.,b-=texture2D(u1,vec2(vv0.x+u27,vv0.y-u27))*1.,b+=texture2D(u1,vec2(vv0.x-u27,vv0.y+u27))*1.,b+=texture2D(u1,vec2(vv0.x,vv0.y+u27))*2.,b+=texture2D(u1,vec2(vv0.x+u27,vv0.y+u27))*1.;vec3 c=sqrt(a.rgb*a.rgb+b.rgb*b.rgb);vec4 e=vec4(c,texture2D(u1,vv0).a),g=texture2D(u2,vv0);gl_FragColor=g.a*e.r*f;}",
i:["u1","u2","u27"],j:n,B:!0},s32:{h:"varying vec2 vv0;uniform sampler2D u1,u2;uniform float u27;const vec4 j=vec4(1.,1.,1.,1.);const vec2 k=vec2(1.,1.);void main(){float h=0.;vec2 l=k*u27,a,b;float c,d,i=0.;for(float e=-4.;e<=4.;e+=1.)for(float f=-4.;f<=4.;f+=1.)a=vec2(e,f),c=length(a)/2.,d=exp(-c*c),b=vv0+l*a,h+=d*texture2D(u1,b).r,i+=d;vec4 m=texture2D(u2,vv0);gl_FragColor=m.a*(texture2D(u1,b).r-h/i)*j;}",i:["u1","u2","u27"],j:n,B:!0},s33:{h:"uniform sampler2D u3;uniform vec2 u7;varying vec2 vv0;vec4 e(vec4 a,vec4 b){vec4 c=step(a,b);return mix(a,b,c);}const vec2 g=vec2(.5,.5),h=vec2(1.,0.),i=vec2(0.,1.);void main(){vec2 a=vv0-u7*g;vec4 b=texture2D(u3,a),c=texture2D(u3,a+u7*h),d=texture2D(u3,a+u7*i),j=texture2D(u3,a+u7),k=e(b,c),l=e(d,j);gl_FragColor=e(k,l);}",
i:["u3","u7"],j:K},s34:{h:"uniform sampler2D u3;uniform vec2 u7;varying vec2 vv0;const vec2 k=vec2(1.,0.),l=vec2(0.,1.),m=vec2(2.,0.),n=vec2(0.,2.);vec4 e(vec4 a,vec4 b){vec4 c=step(a,b);return mix(a,b,c);}vec4 f(vec2 a){vec4 b=texture2D(u3,a),c=texture2D(u3,a+u7*k),d=texture2D(u3,a+u7*l),g=texture2D(u3,a+u7),h=e(b,c),i=e(d,g);return e(h,i);}void main(){vec2 a=vv0+u7*vec2(-.55,-1.05);vec4 b=f(a),c=f(a+u7*m),d=f(a+u7*2.),g=f(a+u7*n),h=e(b,c),i=e(d,g);gl_FragColor=e(h,i);}",i:["u3","u7"],j:K,B:!0},
s35:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){vec4 a=texture2D(u1,vv0);gl_FragColor=a*a;}",i:["u1"],j:y,precision:"lowp",B:!0},s36:{h:"uniform sampler2D u1;uniform vec2 u7;varying vec2 vv0;const float e=15444.;void main(){vec4 a=1001./e*texture2D(u1,vv0-3.*u7)+2002./e*texture2D(u1,vv0-2.*u7)+3003./e*texture2D(u1,vv0-u7)+3432./e*texture2D(u1,vv0)+3003./e*texture2D(u1,vv0+u7)+2002./e*texture2D(u1,vv0+2.*u7)+1001./e*texture2D(u1,vv0+3.*u7);gl_FragColor=a;}",i:["u7","u1"],j:y,precision:"lowp",
B:!0},s37:{h:"uniform sampler2D u1,u10,u28;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);const float g=.1;void main(){vec4 a=texture2D(u10,vv0),b=texture2D(u28,vv0),c=texture2D(u1,vv0),d=max(f*g,b-a*a),h=sqrt(d);gl_FragColor=(c-a)/h;}",i:["u1","u10","u28"],j:{u1:0,u10:1,u28:2},B:!0}},N={s38:{h:"uniform float u16,u29;uniform sampler2D u13,u14,u21;varying vec2 vv0;const vec2 ZERO2=vec2(0.,0.),ONE2=vec2(1.,1.),HALF2=vec2(.5,.5),EPS2=vec2(1e-5,1e-5);void main(){vec4 sum=texture2D(u21,vv0);float toSparsity=1.1111;vec2 uvFrom,uvWeight,xyPatch=ZERO2,eps2=EPS2/u16,xyTo=floor(vv0*u16+eps2);float weightSize=toSparsity*u16;vec2 halfFromSparsity=ONE2*(toSparsity-1.)/2.;for(float patch_x=0.;patch_x<1.1111;patch_x+=1.){xyPatch.x=patch_x;for(float patch_y=0.;patch_y<1.1111;patch_y+=1.)xyPatch.y=patch_y,uvFrom=(xyTo+HALF2+u29*(xyPatch-halfFromSparsity))/u16,uvFrom+=step(uvFrom,-eps2),uvFrom-=step(ONE2-eps2,uvFrom),uvWeight=(xyTo*toSparsity+xyPatch+HALF2)/weightSize,sum+=texture2D(u13,uvWeight)*texture2D(u14,uvFrom);}gl_FragColor=sum,gl_FragColor*=2.2222;}",
i:["u16","u13","u14","u21","u29"],Ya:["1.1111","gl_FragColor\\*=2.2222;"]},s39:{h:"uniform float u16,u29,u24;uniform sampler2D u13,u14,u21;varying vec2 vv0;const vec2 ZERO2=vec2(0.,0.),ONE2=vec2(1.,1.),HALF2=vec2(.5,.5),EPS2=vec2(1e-4,1e-4);void main(){vec4 sum=texture2D(u21,vv0);float fromSparsity=1.1111,shrinkFactor=3.3333;vec2 uvFrom,uvWeight,xyFrom,xyPatchTo,xyPatch=ZERO2,xyShrink=ZERO2,eps2=EPS2/u24,xyTo=floor(vv0*u16+eps2);float weightSize=fromSparsity*u24;vec2 halfFromSparsity=ONE2*(fromSparsity-1.)/2.;float toSparsity=weightSize/u16;vec2 xyFrom0=xyTo*shrinkFactor;for(float patch_x=0.;patch_x<1.1111;patch_x+=1.){xyPatch.x=patch_x;for(float patch_y=0.;patch_y<1.1111;patch_y+=1.){xyPatch.y=patch_y;for(float shrink_x=0.;shrink_x<3.3333;shrink_x+=1.){xyShrink.x=shrink_x;for(float shrink_y=0.;shrink_y<3.3333;shrink_y+=1.)xyShrink.y=shrink_y,xyFrom=xyFrom0+xyShrink+shrinkFactor*u29*(xyPatch-halfFromSparsity),uvFrom=(xyFrom+HALF2)/u24,uvFrom+=step(uvFrom,-eps2),uvFrom-=step(ONE2-eps2,uvFrom),xyPatchTo=xyPatch*shrinkFactor+xyShrink,uvWeight=(xyTo*toSparsity+xyPatchTo+HALF2)/weightSize,sum+=texture2D(u13,uvWeight)*texture2D(u14,uvFrom);}}}gl_FragColor=sum,gl_FragColor*=2.2222;}",
i:"u16 u24 u13 u14 u21 u29".split(" "),Ya:["1.1111","gl_FragColor\\*=2.2222;","3.3333"]}},Q=null,J=null,I={Sa:function(){return z},s:function(){if(!z){Q=Ha(H,2);J=Ha(N,2);m="highp";for(var u in Q)d(D,Q[u],u);F.set("s0");D.enableVertexAttribArray(0);z=!0}},ec:function(u){u.forEach(function(q){I.dc(q)})},dc:function(u){Q[u.id]=u;d(D,u,u.id)},Ec:function(u,q,C){q||(q=u);Q[q]=Object.create(J[u]);Q[q].we=!0;J[u].Ya&&J[u].Ya.forEach(function(M,S){Q[q].h=Q[q].h.replace(new RegExp(M,"g"),C[S])});d(D,Q[q],
q)},set:function(u){u=Q[u];u.B&&(u.B=!1,d(D,u,u.id));g(u)},xa:function(u){return t(u,p(),"s40")},Sb:function(u){return t(u,{h:"void main(){gl_FragColor=vec4(.5,.5,.5,.5);}",i:[],precision:"highp"},"s41")},Yd:function(u){return"undefined"===typeof Q[u]?!1:Q[u].ca},N:function(){-1!==r&&(r=-1,f.ta.forEach(function(u){0!==u&&D.disableVertexAttribArray(u)}))},Ub:function(){var u=0;f.ta.forEach(function(q,C){C=f.sa[C];D.vertexAttribPointer(q,C,D.FLOAT,!1,f.ac,u);u+=4*C})},Df:function(){D.enableVertexAttribArray(0)},
Za:function(){I.$a(D)},$a:function(u){u.vertexAttribPointer(f.ta[0],2,u.FLOAT,!1,8,0)},hg:function(u,q){D.uniform1i(f.v[u],q)},L:function(u,q){D.uniform1f(f.v[u],q)},ea:function(u,q,C){D.uniform2f(f.v[u],q,C)},ig:function(u,q){D.uniform2fv(f.v[u],q)},od:function(u,q){D.uniform3fv(f.v[u],q)},jg:function(u,q,C,M){D.uniform3f(f.v[u],q,C,M)},kg:function(u,q,C,M,S){D.uniform4f(f.v[u],q,C,M,S)},Tb:function(u,q){D.uniform4fv(f.v[u],q)},lg:function(u,q){D.uniformMatrix2fv(f.v[u],!1,q)},mg:function(u,q){D.uniformMatrix3fv(f.v[u],
!1,q)},ng:function(u,q){D.uniformMatrix4fv(f.v[u],!1,q)},I:function(u,q){I.set(u);q.forEach(function(C){switch(C.type){case "4f":D.uniform4fv(f.v[C.name],C.value);break;case "3f":D.uniform3fv(f.v[C.name],C.value);break;case "2f":D.uniform2fv(f.v[C.name],C.value);break;case "1f":D.uniform1f(f.v[C.name],C.value);break;case "1i":D.uniform1i(f.v[C.name],C.value);break;case "mat2":D.uniformMatrix2fv(f.v[C.name],!1,C.value);break;case "mat3":D.uniformMatrix3fv(f.v[C.name],!1,C.value);break;case "mat4":D.uniformMatrix4fv(f.v[C.name],
!1,C.value)}})},Nf:function(){return"lowp"},m:function(){D.disableVertexAttribArray(0);I.N();for(var u in Q){var q=Q[u];q.ca&&(q.ca=!1,D.deleteProgram(q.da));q.we&&delete Q[u]}k.forEach(function(C){D.deleteShader(C)});k.splice(0);v=0;z=!1;f=null;r=-1}};return I}(),D=null,Wa=function(){function a(m){console.log("ERROR in ContextFF: ",m);return!1}function c(m){function l(){Sa.m();Ta.reset();y.getExtension("WEBGL_lose_context").loseContext()}if(navigator.userAgent&&-1!==navigator.userAgent.indexOf("forceWebGL1"))return!1;
var x=document.createElement("canvas");x.setAttribute("width",5);x.setAttribute("height",5);var y=null;try{y=x.getContext("webgl2",m)}catch(h){return!1}if(!y)return!1;d(y);Ta.nc(y);m=Ta.pb(y);if(!m.V&&!m.W)return l(),!1;m=Sa.kc(y,m);l();return m?!0:!1}function d(m){m.clearColor(0,0,0,0);m.disable(m.DEPTH_TEST);m.disable(m.BLEND);m.disable(m.DITHER);m.disable(m.STENCIL_TEST);m.disable(m.CULL_FACE);m.GENERATE_MIPMAP_HINT&&m.hint(m.GENERATE_MIPMAP_HINT,m.FASTEST);m.disable(m.SAMPLE_ALPHA_TO_COVERAGE);
m.disable(m.SAMPLE_COVERAGE);m.depthFunc(m.LEQUAL);m.clearDepth(1)}var g=null,t=null,p=null,k=null,r=!0,f=null,v=null,z={A:function(){return g.width},J:function(){return g.height},La:function(){return g},Ff:function(){return D},X:function(){return r},flush:function(){D.flush()},be:function(){f||(f=new Uint8Array(g.width*g.height*4));D.readPixels(0,0,g.width,g.height,D.RGBA,D.UNSIGNED_BYTE,f);return f},Hf:function(){return g.toDataURL("image/jpeg")},If:function(){Va.M();t||(t=document.createElement("canvas"),
p=t.getContext("2d"));t.width=g.width;t.height=g.height;for(var m=z.be(),l=p.createImageData(t.width,t.height),x=t.width,y=t.height,h=l.data,n=0;n<y;++n)for(var K=y-n-1,H=0;H<x;++H){var N=4*(n*x+H),Q=4*(K*x+H);h[N]=m[Q];h[N+1]=m[Q+1];h[N+2]=m[Q+2];h[N+3]=m[Q+3]}p.putImageData(l,0,0);return t.toDataURL("image/png")},Gf:function(m){!t&&m&&(t=document.createElement("canvas"),p=t.getContext("2d"));var l=m?t:document.createElement("canvas");l.width=g.width;l.height=g.height;(m?p:l.getContext("2d")).drawImage(g,
0,0);return l},s:function(m){m.Pd&&!m.ob?g=document.getElementById(m.Pd):m.ob&&(g=m.ob);g||(g=document.createElement("canvas"));g.width=m&&void 0!==m.width?m.width:512;g.height=m&&void 0!==m.height?m.height:512;"undefined"===typeof m&&(m={});void 0===m.premultipliedAlpha&&(m.premultipliedAlpha=!1);void 0===m.Bb&&(m.Bb=!0);void 0===m.antialias&&(m.antialias=!1);if(D)r=D instanceof WebGL2RenderingContext;else{r=!0;var l={antialias:m.antialias,alpha:!0,preserveDrawingBuffer:!0,premultipliedAlpha:m.premultipliedAlpha,
stencil:!1,depth:m.Bb};navigator&&navigator.userAgent&&-1!==navigator.userAgent.indexOf("noAntialiasing")&&(l.antialias=!1);var x=c(l);!x&&l.antialias&&(l.antialias=!1,x=c(l));x&&(D=g.getContext("webgl2",l));D?r=!0:((D=g.getContext("webgl",l))||(D=g.getContext("experimental-webgl",l)),r=!1)}if(!D)return a("WebGL1 and 2 are not enabled");(k=D.getExtension("WEBGL_lose_context"))&&m.Wc&&(v=m.Wc,g.addEventListener("webglcontextlost",v,!1));if(!Ta.s())return a("Not enough GL capabilities");d(D);F.s();
O.s();return Sa.kc(D,Ta.$d())?!0:a("Cannot filter float textures")},m:function(){D&&(Ta.m(),Sa.m());k&&v&&(g.removeEventListener("webglcontextlost",v,!1),k=v=null);D=f=p=t=g=null}};return z}(),Ra=function(){function a(){null===c&&("undefined"!==typeof F?c=F:"undefined"!==typeof JEShaders&&(c=JEShaders))}var c=null;a();return{af:function(d){c!==d&&(c&&c.N(),c=d)},Sa:function(){return c.Sa()},Za:function(){return c.Za()},$a:function(d){return c.$a(d)},Ub:function(){return c.Ub()},N:function(){return c.N()},
set:function(d){return c.set(d)},xa:function(d){a();return c.xa(d)},Sb:function(d){a();return c.Sb(d)},m:function(){return c.m()}}}(),R=function(){function a(e){D.bindTexture(D.TEXTURE_2D,e)}function c(e){q[0]=e;e=C[0];var L=e>>16&32768,G=e>>12&2047,P=e>>23&255;return 103>P?L:142<P?L|31744|((255==P?0:1)&&e&8388607):113>P?(G|=2048,L|(G>>114-P)+(G>>113-P&1)):L=(L|P-112<<10|G>>1)+(G&1)}function d(e){var L=new Uint16Array(e.length);e.forEach(function(G,P){L[P]=c(G)});return L}function g(){if(null!==M.yb)return M.yb;
var e=p(d([.5,.5,.5,.5]));return null===e?!0:M.yb=e}function t(){if(null!==M.zb)return M.zb;var e=p(new Uint8Array([127,127,127,127]));return null===e?!0:M.zb=e}function p(e){if(!Ra.Sa()||!h)return null;var L=null,G=Math.sqrt(e.length/4);try{var P=D.getError();if("FUCKING_BIG_ERROR"===P)return!1;L=S.instance({isFloat:!1,G:!0,array:e,width:G});P=D.getError();if(P!==D.NO_ERROR)return!1}catch(W){return!1}Va.M();D.viewport(0,0,G,G);D.clearColor(0,0,0,0);D.clear(D.COLOR_BUFFER_BIT);Ra.set("s0");L.ic(0);
O.l(!0,!0);e=4*G*G;P=new Uint8Array(e);D.readPixels(0,0,G,G,D.RGBA,D.UNSIGNED_BYTE,P);G=!0;for(var aa=0;aa<e;++aa)G=G&&3>Math.abs(P[aa]-127);L.remove();Va.U();return G}var k=0,r=null,f=0,v=null,z=null,m=null,l=null,x=null,y=null,h=!1,n=[],K={isFloat:!1,isPot:!0,isLinear:!1,isMipmap:!1,isAnisotropicFiltering:!1,isMirrorX:!1,isMirrorY:!1,isSrgb:!1,isKeepArray:!1,isFlipY:null,width:0,height:0,url:null,array:null,data:null,C:null,Bc:null,ve:!1,G:!1,ba:null,Ua:4,Hb:0},H=!1,N=null,Q=null,J=[[1,0,0,0],[0,
1,0,0],[0,0,1,0],[0,0,0,1]],I=!1,u=!1,q=new Float32Array(1),C=new Int32Array(q.buffer),M={yb:null,zb:null},S={s:function(){h||(x=[D.RGBA,null,D.RGBA,D.RGBA],y=[D.RGBA,null,D.RGBA,D.RGBA],r=[D.TEXTURE0,D.TEXTURE1,D.TEXTURE2,D.TEXTURE3,D.TEXTURE4,D.TEXTURE5,D.TEXTURE6,D.TEXTURE7],I="undefined"!==typeof JEContext,u="undefined"!==typeof Ta,I&&JEContext.ag()&&r.push(D.TEXTURE8,D.TEXTURE9),v=[-1,-1,-1,-1,-1,-1,-1,-1],l=[D.UNSIGNED_BYTE,D.FLOAT,D.FLOAT],h=!0)},pe:function(){if(!z){for(var e=new Float32Array(16384),
L=0;16384>L;++L)e[L]=2*Math.random()-1;z={random:S.instance({isFloat:!0,isPot:!0,array:e,width:64}),td:S.instance({isFloat:!1,isPot:!0,width:1,array:new Uint8Array([0,0,0,0])})}}S.mf()},Tf:function(){return z.td},mf:function(){l[1]=Ta.tb(D)},Ze:function(){y=x=[D.RGBA,D.RGBA,D.RGBA,D.RGBA]},fd:function(e){F.set("s1");Va.M();var L=e.A(),G=e.J();D.viewport(0,0,L,G);e.g(0);O.l(!1,!1)},Pe:function(e,L){S.fd(e);D.readPixels(0,0,e.A(),e.J(),D.RGBA,D.UNSIGNED_BYTE,L)},Qe:function(e,L){S.fd(e);return Ta.Rb(0,
0,e.A(),e.J(),L)},uc:function(e,L,G,P,aa,W,ka){e.activeTexture(e.TEXTURE0);var w=e.createTexture();e.bindTexture(e.TEXTURE_2D,w);aa=aa instanceof Float32Array?aa:new Float32Array(aa);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_S,e.CLAMP_TO_EDGE);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_T,e.CLAMP_TO_EDGE);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MAG_FILTER,e.NEAREST);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MIN_FILTER,e.NEAREST);e.pixelStorei(e.UNPACK_FLIP_Y_WEBGL,W);e.texImage2D(e.TEXTURE_2D,0,e.RGBA,
G,P,0,e.RGBA,e.FLOAT,aa);e.bindTexture(e.TEXTURE_2D,null);e.pixelStorei(e.UNPACK_FLIP_Y_WEBGL,!1);ka&&(Va.U(),F.xa(e));e.viewport(0,0,G,P);e.framebufferTexture2D(e.FRAMEBUFFER,e.COLOR_ATTACHMENT0,e.TEXTURE_2D,L,0);e.bindTexture(e.TEXTURE_2D,w);ka?O.l(!0,!0):O.Ja(e);e.deleteTexture(w);h&&(v[0]=-1,m=null,k=0)},jb:function(e){e!==k&&(D.activeTexture(r[e]),k=e)},instance:function(e){function L(){T=void 0!==w.C.videoWidth?w.C.videoWidth:w.C.width;X=void 0!==w.C.videoHeight?w.C.videoHeight:w.C.height}function G(B){var U=
D.getError();if("FUCKING_BIG_ERROR"===U)return!1;D.texImage2D(D.TEXTURE_2D,0,ha,fa,ia,B);U=D.getError();U!==D.NO_ERROR&&fa!==D.RGBA&&(fa=D.RGBA,D.texImage2D(D.TEXTURE_2D,0,ha,fa,ia,B));return!0}function P(){if(!Za){a(la);ra&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,ra);w.isPot?(D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_S,w.isMirrorX?D.MIRRORED_REPEAT:D.REPEAT),D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_T,w.isMirrorY?D.MIRRORED_REPEAT:D.REPEAT)):(D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_S,D.CLAMP_TO_EDGE),
D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_T,D.CLAMP_TO_EDGE));w.isAnisotropicFiltering&&"undefined"!==typeof JESETTINGS&&D.texParameterf(D.TEXTURE_2D,JEContext.Kf().TEXTURE_MAX_ANISOTROPY_EXT,JESETTINGS.sf);D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MAG_FILTER,w.isLinear?D.LINEAR:D.NEAREST);w.isLinear?D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MIN_FILTER,w.isMipmap&&!ya?D.NEAREST_MIPMAP_LINEAR:D.LINEAR):D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MIN_FILTER,w.isMipmap&&!ya?D.NEAREST_MIPMAP_NEAREST:D.NEAREST);
fa=x[w.Ua-1];ha=y[w.Ua-1];ia=l[E];if(Ta.X()){var B=Ta.ce();fa===D.RGBA&&ia===D.FLOAT?w.isMipmap||w.isLinear?ha=Sa.ee(D):Ta.lc()?B&&(ha=B):ha=D.RGBA16F||D.RGBA:fa===D.RGB&&ia===D.FLOAT&&B&&(ha=B,fa=D.RGBA)}if(w.G&&!w.isFloat||w.isFloat&&w.isMipmap&&Sa.ze())ha=Ta.de(),ia=Ta.tb(D);w.Hb&&(La=w.Hb);w.isSrgb&&4===w.Ua&&(fa=JEContext.Rf());if(w.C)G(w.C);else if(w.url)G(xa);else if(ma){B=ma;try{"FUCKING_BIG_ERROR"!==D.getError()&&(D.texImage2D(D.TEXTURE_2D,0,ha,T,X,0,fa,ia,B),D.getError()!==D.NO_ERROR&&(D.texImage2D(D.TEXTURE_2D,
0,ha,T,X,0,fa,ia,null),D.getError()!==D.NO_ERROR&&D.texImage2D(D.TEXTURE_2D,0,D.RGBA,T,X,0,D.RGBA,D.UNSIGNED_BYTE,null)))}catch(Kb){D.texImage2D(D.TEXTURE_2D,0,ha,T,X,0,fa,ia,null)}w.isKeepArray||(ma=null)}else B=D.getError(),"FUCKING_BIG_ERROR"!==B&&(D.texImage2D(D.TEXTURE_2D,0,ha,T,X,0,fa,ia,null),B=D.getError(),B!==D.NO_ERROR&&(fa=D.RGBA,w.G&&ia!==D.FLOAT&&(ia=D.FLOAT,D.texImage2D(D.TEXTURE_2D,0,ha,T,X,0,fa,ia,null))));if(w.isMipmap)if(!ya&&ea)ea.sb(),Ma=!0;else if(ya){B=Math.log2(Math.min(T,X));
Ba=Array(1+B);Ba[0]=la;for(var U=1;U<=B;++U){var ja=Math.pow(2,U),Z=T/ja;ja=X/ja;var za=D.createTexture();a(za);D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MIN_FILTER,D.NEAREST);D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MAG_FILTER,D.NEAREST);D.texImage2D(D.TEXTURE_2D,0,ha,Z,ja,0,fa,ia,null);a(null);Ba[U]=za}Ma=!0}a(null);v[k]=-1;ra&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1);Ea=!0;w.ba&&ea&&(w.ba(ea),w.ba=null)}}function aa(){for(var B=T*X,U=2*B,ja=3*B,Z=0;Z<B;++Z)oa[0][Z]=Fa[Z],oa[1][Z]=Fa[Z+B],oa[2][Z]=Fa[Z+
U],oa[3][Z]=Fa[Z+ja]}function W(){var B=T*X*4;ua=[new Uint8Array(B),new Uint8Array(B),new Uint8Array(B),new Uint8Array(B)];oa=[new Float32Array(ua[0].buffer),new Float32Array(ua[1].buffer),new Float32Array(ua[2].buffer),new Float32Array(ua[3].buffer)];Na=new Uint8Array(4*B);Fa=new Float32Array(Na.buffer);Ga=!0}function ka(){va.lb=new Uint8Array(T*X*4);va.wc=new Float32Array(va.buffer);va.Db=!0}var w=Object.assign({},K,e),A=f++;null===w.isFlipY&&(w.isFlipY=w.url||w.array?!0:!1);w.data&&(w.array="string"===
typeof w.data?Qa(w.data):w.isFloat?new Float32Array(w.data):new Uint8Array(w.data),w.isFlipY=!1);var E=0,ca=w.C?!0:!1,Y=null,pa=null,$a=!1,Ua=null;w.G=w.G||w.isFloat;w.G&&(E=1);!w.ve&&w.isFloat&&u&&!Ta.lc()&&(w.isFloat=!1);w.isFloat&&(E=2);w.isAnisotropicFiltering&&I&&!JEContext.Wf()&&(w.isAnisotropicFiltering=!1);var la=w.Bc||D.createTexture(),xa=null,ma=!1,T=0,X=0,Ea=!1,Za=!1,Ga=!1,oa=null,ua=null,Na=null,Fa=null,ha=null,fa=null,ia=null,ra=w.isFlipY,tb=(e=w.G&&w.isMipmap)&&Sa.Gd(),ya=e&&tb?!0:!1,
Ba=null,La=-1,Ma=!1,va={Db:!1,lb:null,wc:null};w.width&&(T=w.width,X=w.height?w.height:T);var ea={get:function(){return la},A:function(){return T},J:function(){return X},Uf:function(){return w.url},Xf:function(){return w.isFloat},Zf:function(){return w.G},$f:function(){return w.isLinear},sb:function(){D.generateMipmap(D.TEXTURE_2D)},Ed:function(B,U){ya?(B||(B=ea.zc()),S.jb(U),a(Ba[B]),v[U]=-1):ea.g(U)},zc:function(){-1===La&&(La=Math.log(T)/Math.log(2));return La},Zd:function(B){if(ya){B||(B=ea.zc());
F.set("s11");S.jb(0);for(var U=T,ja=X,Z=1;Z<=B;++Z)U/=2,ja/=2,F.ea("u7",.25/U,.25/ja),D.viewport(0,0,U,ja),a(Ba[Z-1]),D.framebufferTexture2D(Va.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,Ba[Z],0),O.l(!1,1===Z);v[0]=-1}else ea.sb()},gg:function(B){(ca=!(Array.isArray(B)||B.constructor===Float32Array||B.constructor===Uint8Array))?(ma=null,w.C=B,L()):ma=B},g:function(B){if(!Ea)return!1;S.jb(B);if(v[B]===A)return!1;a(la);v[B]=A;return!0},ic:function(B){D.activeTexture(r[B]);k=B;a(la);v[B]=A},u:function(){m=
ea;D.framebufferTexture2D(Va.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,la,0)},P:function(){m=ea;D.viewport(0,0,T,X);D.framebufferTexture2D(Va.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,la,0)},$b:S.$b,resize:function(B,U){T=B;X=U;P()},clone:function(B){B=S.instance({width:T,height:X,G:w.G,isFloat:w.isFloat,isLinear:w.isLinear,isMirrorY:w.isMirrorY,isFlipY:B?!ra:ra,isPot:w.isPot});Ra.set("s0");Va.U();B.u();D.viewport(0,0,T,X);ea.g(0);O.l(!0,!0);return B},bf:function(){D.viewport(0,0,T,X)},remove:function(){D.deleteTexture(la);
Za=!0;n.splice(n.indexOf(ea),1);ea=null},refresh:function(){ea.ic(0);ra&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!0);ca?D.texImage2D(D.TEXTURE_2D,0,ha,fa,D.UNSIGNED_BYTE,w.C):D.texImage2D(D.TEXTURE_2D,0,ha,T,X,0,fa,ia,ma);ra&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1)},Qb:function(){Ga||W();D.readPixels(0,0,T,4*X,D.RGBA,D.UNSIGNED_BYTE,Na);aa();return oa},Me:function(){Ga||W();return Ta.Rb(0,0,T,4*X,Na).then(function(){aa();return oa})},Oe:function(){va.Db||ka();D.readPixels(0,0,T,X,D.RGBA,D.UNSIGNED_BYTE,
va.lb);return va.wc},Ne:function(){va.Db||ka();return Ta.Rb(0,0,T,X,va.lb)},qb:function(B){Va.M();F.set("s12");ea.g(0);if(B)D.viewport(0,0,T,X),F.Tb("u8",.25,.25,.25,.25),O.l(!1,!0);else for(B=0;4>B;++B)D.viewport(0,X*B,T,X),F.Tb("u8",J[B]),O.l(!1,0===B)},qg:function(B){var U=ia===l[0]&&!t();a(la);ra&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!0);U?($a||(Y=document.createElement("canvas"),Y.width=T,Y.height=X,pa=Y.getContext("2d"),Ua=pa.createImageData(T,X),$a=!0),Ua.data.set(B),pa.putImageData(Ua,0,0),
D.texImage2D(D.TEXTURE_2D,0,ha,fa,ia,Y)):D.texImage2D(D.TEXTURE_2D,0,ha,T,X,0,fa,ia,B);v[k]=A;ra&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1)},rg:function(B,U){a(la);U&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!0);D.texImage2D(D.TEXTURE_2D,0,ha,fa,ia,B);v[k]=A;U&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1)},eg:function(B,U){var ja=T*X,Z=4*ja;B=w.G?B?"RGBE":"JSON":"RGBA";U&&(B=U);U=Ta.X()&&!1;var za=null;switch(B){case "RGBE":za="s42";break;case "JSON":za=U?"s0":"s12";break;case "RGBA":case "RGBAARRAY":za="s6"}Ga||
("RGBA"===B||"RGBE"===B||"RGBAARRAY"===B?(ua=new Uint8Array(Z),Ga=!0):"JSON"!==B||U||W());Va.M();F.set(za);ea.g(0);Z=null;if("RGBA"===B||"RGBE"===B||"RGBAARRAY"===B){D.viewport(0,0,T,X);O.l(!0,!0);D.readPixels(0,0,T,X,D.RGBA,D.UNSIGNED_BYTE,ua);if("RGBAARRAY"===B)return{data:ua};H||(N=document.createElement("canvas"),Q=N.getContext("2d"),H=!0);N.width=T;N.height=X;ja=Q.createImageData(T,X);ja.data.set(ua);Q.putImageData(ja,0,0);Z=N.toDataURL("image/png")}else if("JSON"===B)if(U)Z=new Float32Array(ja),
D.viewport(0,0,T,X),O.l(!0,!0),D.readPixels(0,0,T,X,D.RGBA,D.FLOAT,Z);else{for(Z=0;4>Z;++Z)D.viewport(0,X*Z,T,X),F.Tb("u8",J[Z]),O.l(!Z,!Z);ea.Qb();Z=Array(ja);for(U=0;U<ja;++U)Z[4*U]=oa[0][U],Z[4*U+1]=oa[1][U],Z[4*U+2]=oa[2][U],Z[4*U+3]=oa[3][U]}return{format:B,data:Z,width:T,height:X,isMirrorY:w.isMirrorY,isFlipY:"RGBA"===B?w.isFlipY:!w.isFlipY}}};w.isMipmap&&!ya&&Ea&&!Ma&&(ea.sb(),Ma=!0);if(w.url)a(la),D.texImage2D(D.TEXTURE_2D,0,D.RGBA,1,1,0,D.RGBA,D.UNSIGNED_BYTE,null),xa=new Image,xa.Af="Anonymous",
xa.crossOrigin="Anonymous",xa.src=w.url,xa.onload=function(){T=xa.width;X=xa.height;P()};else if(w.C){var ab=function(){L();T?P():setTimeout(ab,1)};ab()}else w.array?(w.G&&!w.isFloat?w.array instanceof Uint16Array?(ma=w.array,P()):g()?(ma=d(w.array),P()):(P(),S.uc(D,la,ea.A(),ea.J(),w.array,ra,!0)):(ma=w.isFloat?w.array instanceof Float32Array?w.array:new Float32Array(w.array):w.array instanceof Uint8Array?w.array:new Uint8Array(w.array),P()),w.isKeepArray||(ma&&ma!==w.array&&(ma=null),delete w.array)):
w.Bc?Ea=!0:P();ea.Qf=ea.A;w.ba&&Ea&&(w.ba(ea),w.ba=null);n.push(ea);return ea},M:function(e){e!==k&&(D.activeTexture(r[e]),k=e);v[e]=-1;a(null)},vf:function(e){z.random.g(e)},$b:function(){m=null;D.framebufferTexture2D(Va.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,null,0)},reset:function(){0!==k&&D.activeTexture(r[0]);for(var e=0;e<r.length;++e)v[e]=-1;k=-1},dg:function(){k=-1},hf:function(){for(var e=0;e<r.length;++e)S.M(e)},xc:function(){z&&(z.random.remove(),z.td.remove())},pg:function(e,L){if("RGBA"===
e.format||"RGBE"===e.format){var G=new Image;G.src=e.data;G.onload=function(){S.instance({isMirrorY:e.isMirrorY,isFlipY:e.isFlipY,isFloat:!1,C:G,ba:function(P){if("RGBA"===e.format)L(P);else{var aa=e.width,W=e.height,ka=S.instance({isMirrorY:e.isMirrorY,isFloat:!0,width:aa,height:W,isFlipY:e.isFlipY});Va.U();D.viewport(0,0,aa,W);F.set("s43");ka.u();P.g(0);O.l(!0,!0);S.M(0);L(ka);D.flush();setTimeout(P.remove,50)}}})}}else"JSON"===e.format?L(S.instance({isFloat:!0,isFlipY:e.isFlipY,width:e.width,height:e.height,
array:new Float32Array(e.data)})):L(!1)},Ld:d,m:function(){m&&(Va.U(),S.$b(),Va.M());S.hf();n.slice(0).forEach(function(e){e.remove()});n.splice(0);h=!1;f=0;"undefined"!==typeof Sa&&Sa.m();z=null}};return S}(),Xa={instance:function(a){var c=[R.instance(a),R.instance(a)],d=[c[1],c[0]],g=d,t={nd:function(p){g[1].u();g[0].g(p);t.rd()},fg:function(p){g[1].P();g[0].g(p);t.rd()},rd:function(){g=g===c?d:c},refresh:function(){g[0].refresh();g[1].refresh()},g:function(p){g[0].g(p)},uf:function(p){g[1].g(p)},
he:function(){return g[0]},Of:function(){return g[1]},remove:function(){g[0].remove();g[1].remove();g=null}};return t}},O=function(){function a(f){var v={T:null,F:null};v.T=f.createBuffer();f.bindBuffer(f.ARRAY_BUFFER,v.T);f.bufferData(f.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),f.STATIC_DRAW);v.F=f.createBuffer();f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,v.F);f.bufferData(f.ELEMENT_ARRAY_BUFFER,new Uint16Array([0,1,2]),f.STATIC_DRAW);return v}var c=null,d=0,g=!1,t=[],p=-2,k=-2,r={reset:function(){k=
p=-2},s:function(){g||(c=a(D),r.kb(),g=!0)},instance:function(f){var v=d++,z=f.F?f.F.length:0,m="undefined"===typeof f.mode?D.STATIC_DRAW:f.mode,l=D.createBuffer();D.bindBuffer(D.ARRAY_BUFFER,l);D.bufferData(D.ARRAY_BUFFER,f.T instanceof Float32Array?f.T:new Float32Array(f.T),m);p=v;var x=null,y=null,h=null;if(f.F){x=D.createBuffer();D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,x);var n=null;65536>f.F.length?(n=Uint16Array,y=D.UNSIGNED_SHORT,h=2):(n=Uint32Array,y=D.UNSIGNED_INT,h=4);n=f.F instanceof n?f.F:
new n(f.F);D.bufferData(D.ELEMENT_ARRAY_BUFFER,n,m);k=v}var K={Fd:function(H){p!==v&&(D.bindBuffer(D.ARRAY_BUFFER,l),p=v);H&&Ra.Ub()},Cd:function(){k!==v&&(D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,x),k=v)},bind:function(H){K.Fd(H);K.Cd()},Bf:function(){D.drawElements(D.TRIANGLES,z,y,0)},Cf:function(H,N){D.drawElements(D.TRIANGLES,H,y,N*h)},remove:function(){D.deleteBuffer(l);f.F&&D.deleteBuffer(x);K=null}};t.push(K);return K},kb:function(){-1!==p&&(D.bindBuffer(D.ARRAY_BUFFER,c.T),p=-1);-1!==k&&(D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,
c.F),k=-1)},l:function(f,v){f&&O.kb();v&&Ra.Za();D.drawElements(D.TRIANGLES,3,D.UNSIGNED_SHORT,0)},Ja:function(f){f=f||D;var v=a(f);f.bindBuffer(f.ARRAY_BUFFER,v.T);f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,v.F);Ra.$a(f);f.clear(f.COLOR_BUFFER_BIT);f.drawElements(f.TRIANGLES,3,f.UNSIGNED_SHORT,0);f.flush();f.bindBuffer(f.ARRAY_BUFFER,null);f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,null);f.deleteBuffer(v.T);f.deleteBuffer(v.F);r.reset();g&&(r.kb(),Ra.Za())},xc:function(){var f=D,v=c;f.deleteBuffer(v.T);f.deleteBuffer(v.F)},
m:function(){r.xc();t.forEach(function(f){f.remove()});D.bindBuffer(D.ARRAY_BUFFER,null);D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,null);r.reset();g=!1;t.splice(0);d=0}};return r}(),Va=function(){var a=null,c=null,d=null,g=!1,t=[],p={D:-2,tc:1},k={Sa:function(){return g},s:function(){if(!g){a=D.createFramebuffer();var r=Ta.X();c=r&&D.DRAW_FRAMEBUFFER?D.DRAW_FRAMEBUFFER:D.FRAMEBUFFER;d=r&&D.READ_FRAMEBUFFER?D.READ_FRAMEBUFFER:D.FRAMEBUFFER;g=!0}},Lf:function(){return c},fe:function(){return d},Na:function(){return D.FRAMEBUFFER},
Pf:function(){return p},Ef:function(){return a},instance:function(r){void 0===r.Ic&&(r.Ic=!1);var f=r.pa?r.pa:null,v=r.width,z=void 0!==r.height?r.height:r.width,m=a,l=null,x=!1,y=!1,h=0;f&&(v=v?v:f.A(),z=z?z:f.J());var n={md:function(){x||(m=D.createFramebuffer(),x=!0,h=p.tc++)},xd:function(){n.md();n.u();l=D.createRenderbuffer();D.bindRenderbuffer(D.RENDERBUFFER,l);D.renderbufferStorage(D.RENDERBUFFER,D.DEPTH_COMPONENT16,v,z);D.framebufferRenderbuffer(c,D.DEPTH_ATTACHMENT,D.RENDERBUFFER,l);D.clearDepth(1)},
bind:function(K,H){h!==p.D&&(D.bindFramebuffer(c,m),p.D=h);f&&f.u();H&&D.viewport(0,0,v,z);K&&D.clear(D.COLOR_BUFFER_BIT|D.DEPTH_BUFFER_BIT)},tf:function(){h!==p.D&&(D.bindFramebuffer(c,m),p.D=h)},clear:function(){D.clear(D.COLOR_BUFFER_BIT|D.DEPTH_BUFFER_BIT)},yf:function(){D.clear(D.COLOR_BUFFER_BIT)},zf:function(){D.clear(D.DEPTH_BUFFER_BIT)},bf:function(){D.viewport(0,0,v,z)},u:function(){h!==p.D&&(D.bindFramebuffer(c,m),p.D=h)},rtt:function(K){f=K;p.D!==h&&(D.bindFramebuffer(D.FRAMEBUFFER,m),
p.D=h);K.u()},M:function(){D.bindFramebuffer(c,null);p.D=-1},resize:function(K,H){v=K;z=H;l&&(D.bindRenderbuffer(D.RENDERBUFFER,l),D.renderbufferStorage(D.RENDERBUFFER,D.DEPTH_COMPONENT16,v,z))},remove:function(){m===a||y||(D.bindFramebuffer(c,m),D.framebufferTexture2D(c,D.COLOR_ATTACHMENT0,D.TEXTURE_2D,null,0),l&&D.framebufferRenderbuffer(c,D.DEPTH_ATTACHMENT,D.RENDERBUFFER,null),D.bindFramebuffer(c,null),D.deleteFramebuffer(m),l&&D.deleteRenderbuffer(l));y=!0}};r.Ic&&n.xd();t.push(n);return n},
M:function(){D.bindFramebuffer(c,null);p.D=-1},jf:function(){D.bindFramebuffer(c,null);D.clear(D.COLOR_BUFFER_BIT|D.DEPTH_BUFFER_BIT);D.viewport(0,0,Ta.A(),Ta.J());p.D=-1},reset:function(){p.D=-2},U:function(){0!==p.D&&(D.bindFramebuffer(c,a),p.D=0)},clear:function(){D.viewport(0,0,Ta.A(),Ta.J());D.clear(D.COLOR_BUFFER_BIT)},m:function(){k.M();t.forEach(function(r){r.remove()});null!==a&&(D.deleteFramebuffer(a),a=null);k.reset();g=!1;t.splice(0);p.tc=1}};return k}(),Ta=function(){function a(){g="undefined"===
typeof Wa?JEContext:Wa;t=!0}function c(h,n){for(var K=0;K<h.length;++K){var H=n.getExtension(h[K]);if(H)return H}return null}function d(){null!==l.cb&&(clearInterval(l.cb),l.cb=null);l.ua=!1}var g=null,t=!1,p={Jc:!1,Wb:null,Xb:null,Mc:!1,ye:!1,Yb:null,Nc:!1,Zb:null,Kc:!1,mb:null,se:!1,nb:null,te:!1},k=null,r={V:!0,W:!0,rb:!0,ed:!1},f=null,v=!0,z=null,m=null,l={ua:!1,ja:null,Oa:null,wb:-1,ka:null,cb:null},x="undefined"===typeof window?{}:window,y={s:function(){if(t)return!0;y.reset();t||a();var h=
D;if(!k.Jc){k.Wb=y.qc(h);x.GL_EXT_FLOAT=k.Wb;k.Mc=k.Wb?!0:!1;if(k.Mc||y.X())k.Xb=y.rc(h),k.ye=k.Xb?!0:!1,x.GL_EXT_FLOATLINEAR=k.Xb;k.Jc=!0}if(!k.Kc){k.Yb=y.Ia(h);k.Yb&&(k.Nc=!0,x.GL_EXT_HALFFLOAT=k.Yb);if(k.Nc||y.X())k.Zb=y.sc(h),x.GL_EXT_HALFFLOATLINEAR=k.Zb;k.Vf=k.Zb?!0:!1;k.Kc=!0}k.mb=y.oc(h);k.se=k.mb?!0:!1;x.GL_EXT_COLORBUFFERFLOAT=k.mb;k.nb=y.pc(h);k.te=k.nb?!0:!1;x.GL_EXT_COLORBUFFERHALFFLOAT=k.nb;Va.s();R.s();if(!y.Rd())return!1;O.s();R.pe();return!0},reset:function(){k=Object.assign({},p);
f=Object.assign({},r)},A:function(){t||a();return g.A()},J:function(){t||a();return g.J()},X:function(){t||a();return g.X()},nc:function(h){y.oc(h);y.pc(h);y.qc(h);y.rc(h);y.Ia(h);y.sc(h)},oc:c.bind(null,["EXT_color_buffer_float","WEBGL_color_buffer_float","OES_color_buffer_float"]),pc:c.bind(null,["EXT_color_buffer_half_float","WEBGL_color_buffer_half_float","OES_color_buffer_half_float"]),qc:c.bind(null,["OES_texture_float","MOZ_OES_texture_float","WEBKIT_OES_texture_float"]),rc:c.bind(null,["OES_texture_float_linear",
"MOZ_OES_texture_float_linear","WEBKIT_OES_texture_float_linear"]),Ia:c.bind(null,["OES_texture_half_float","MOZ_OES_texture_half_float","WEBKIT_OES_texture_half_float"]),sc:c.bind(null,["OES_texture_half_float_linear","MOZ_OES_texture_half_float_linear","WEBKIT_OES_texture_half_float_linear"]),tb:function(h){var n=y.Ia(h);return n&&n.HALF_FLOAT_OES?n.HALF_FLOAT_OES:h.HALF_FLOAT||h.FLOAT},ce:function(){return m||D.RGBA32F||D.RGBA},de:function(){return z||D.RGBA16F||D.RGBA},$d:function(){return f},
lc:function(){return f.V},xf:function(){return f.W},wf:function(){return f.rb},Hd:function(){return f.ed&&v},sd:function(h){v=h;!h&&l.ua&&(D.deleteSync(l.Oa),D.bindBuffer(l.ka,null),l.ua=!1)},bb:function(h,n,K){function H(){h.bindTexture(h.TEXTURE_2D,null);h.bindFramebuffer(N,null);h.deleteTexture(I);h.deleteFramebuffer(J)}var N=h.FRAMEBUFFER,Q=h.NEAREST,J=h.createFramebuffer();h.bindFramebuffer(N,J);var I=h.createTexture();h.activeTexture(h.TEXTURE0);h.bindTexture(h.TEXTURE_2D,I);h.pixelStorei(h.UNPACK_FLIP_Y_WEBGL,
!1);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_WRAP_S,h.CLAMP_TO_EDGE);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_WRAP_T,h.CLAMP_TO_EDGE);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_MAG_FILTER,Q);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_MIN_FILTER,Q);h.texImage2D(h.TEXTURE_2D,0,n,3,3,0,h.RGBA,K,null);h.framebufferTexture2D(h.FRAMEBUFFER,h.COLOR_ATTACHMENT0,h.TEXTURE_2D,I,0);if(h.checkFramebufferStatus(h.READ_FRAMEBUFFER||h.FRAMEBUFFER)!==h.FRAMEBUFFER_COMPLETE)return H(),!1;Ra.Sb(h);h.clearColor(0,0,0,0);h.viewport(0,
0,3,3);h.disable(h.DEPTH_TEST);h.clear(h.COLOR_BUFFER_BIT);O.Ja(h);h.bindFramebuffer(N,null);Ra.xa(h);h.activeTexture(h.TEXTURE0);h.bindTexture(h.TEXTURE_2D,I);O.Ja(h);n=new Uint8Array(36);h.readPixels(0,0,3,3,h.RGBA,h.UNSIGNED_BYTE,n);H();for(K=0;36>K;++K)if(3!==K%4&&3<Math.abs(n[K]-127))return!1;return!0},pb:function(h){var n={V:!1,W:!1};h.disable(h.BLEND);h.clearColor(0,0,0,0);h.clear(h.COLOR_BUFFER_BIT);h.RGBA32F&&y.bb(h,h.RGBA32F,h.FLOAT)&&(n.V=!0,m=h.RGBA32F);!n.V&&y.bb(h,h.RGBA,h.FLOAT)&&(n.V=
!0,m=h.RGBA);var K=y.tb(h);z=null;h.RGBA16F&&y.bb(h,h.RGBA16F,K)&&(n.W=!0,z=h.RGBA16F);!n.W&&y.bb(h,h.RGBA,K)&&(n.W=!0,z=h.RGBA);return n},Sd:function(){var h=Va.instance({width:2});h.md();var n=R.instance({width:2,isFloat:!0,Ua:3});h.u();n.u();D.flush();D.checkFramebufferStatus(Va.fe())!==D.FRAMEBUFFER_COMPLETE?(R.Ze(),f.rb=!1):f.rb=!0;h.remove();n.remove()},Td:function(){var h=!1;y.X()&&(h="PIXEL_PACK_BUFFER STREAM_READ SYNC_GPU_COMMANDS_COMPLETE WAIT_FAILED fenceSync deleteSync createBuffer".split(" ").every(function(n){return"undefined"!==
typeof D[n]}));f.ed=h},Rd:function(){var h=y.pb(D);Object.assign(f,h);if(!f.V&&!f.W)return!1;y.Sd();y.Td();return!0},Rb:function(h,n,K,H,N){if(!y.Hd())return D.readPixels(h,n,K,H,D.RGBA,D.UNSIGNED_BYTE,N),Promise.resolve(N);null===l.ja&&(l.ka=D.PIXEL_PACK_BUFFER,l.ja=D.createBuffer(),l.wb=-1);D.bindBuffer(l.ka,l.ja);N.byteLength!==l.wb&&(D.bufferData(l.ka,N.byteLength,D.STREAM_READ),l.wb=N.byteLength);D.readPixels(h,n,K,H,D.RGBA,D.UNSIGNED_BYTE,0);l.Oa=D.fenceSync(D.SYNC_GPU_COMMANDS_COMPLETE,0);
D.flush();return new Promise(function(Q,J){function I(){if(!l.ua)return d(),J(),!1;switch(D.clientWaitSync(l.Oa,0,0)){case D.TIMEOUT_EXPIRED:return!1;case D.WAIT_FAILED:return d(),J(),!1;default:return d(),D.deleteSync(l.Oa),D.getBufferSubData(l.ka,0,N),D.bindBuffer(l.ka,null),Q(N),!0}}d();l.ua=!0;I()||(l.cb=setInterval(I,0))})},m:function(){d();R.m();Ra.m();Va.m();O.m();null!==l.ja&&(D.deleteBuffer(l.ja),l.ja=null);t=!1}};return y}(),Sa=function(){function a(J,I,u,q){n.texParameteri(n.TEXTURE_2D,
n.TEXTURE_MIN_FILTER,q?n.NEAREST_MIPMAP_NEAREST:n.LINEAR);var C=null;if(null!==u)try{C=n.getError();if("FUCKING_BIG_ERROR"===C)return!1;n.texImage2D(n.TEXTURE_2D,0,J,4,4,0,n.RGBA,I,u);C=n.getError();if(C!==n.NO_ERROR)return!1}catch(M){return!1}q&&n.generateMipmap(n.TEXTURE_2D);n.clear(n.COLOR_BUFFER_BIT);O.Ja(n);C=n.getError();if("FUCKING_BIG_ERROR"===C)return!1;n.readPixels(0,0,2,2,n.RGBA,n.UNSIGNED_BYTE,z);C=n.getError();C===n.INVALID_OPERATION&&"undefined"!==typeof n.PIXEL_PACK_BUFFER&&(n.bindBuffer(n.PIXEL_PACK_BUFFER,
null),n.readPixels(0,0,2,2,n.RGBA,n.UNSIGNED_BYTE,z),C=n.getError());if(C!==n.NO_ERROR)return!1;u=!0;for(q=0;16>q;++q)u=u&&4>Math.abs(z[q]-127);u&&(f.Yc=I,f.Hc=J);return u}function c(J,I){return K.V&&a(J,n.FLOAT,new Float32Array(m),I)?(r=k.cc,!0):!1}function d(J,I,u){if(!K.W)return!1;var q=R.Ld(m),C=Ta.Ia(n);if(C&&C.HALF_FLOAT_OES&&a(J,C.HALF_FLOAT_OES,q,I)||n.HALF_FLOAT&&a(J,n.HALF_FLOAT,q,I))return r=k.qa,!0;q=new Float32Array(m);if(a(J,n.FLOAT,q,I))return r=k.qa,!0;n.bindTexture(n.TEXTURE_2D,u);
n.texImage2D(n.TEXTURE_2D,0,n.RGBA,2,2,0,n.RGBA,n.UNSIGNED_BYTE,null);n.bindFramebuffer(f.Ga,Q);R.uc(n,u,2,2,q,!1,!1);n.bindFramebuffer(f.Ga,null);n.bindTexture(n.TEXTURE_2D,u);return a(J,null,null,I)?(r=k.qa,!0):!1}function g(J,I,u){v=!0;if(d(J,!0,u)||c(I,!0))return!0;v=!1;return d(J,!1,u)||c(I,!1)?!0:!1}function t(J){if(r===k.N){n=J||D;r=k.RGBA8;v=!0;Ta.nc(n);K||(K=Ta.pb(n));Va.reset();Q=n.createFramebuffer();f.Ga=n.DRAW_FRAMEBUFFER||n.FRAMEBUFFER;n.bindFramebuffer(f.Ga,null);n.clearColor(0,0,0,
0);n.viewport(0,0,2,2);F.N();H=F.xa(n);J=n.createTexture();n.activeTexture(n.TEXTURE0);n.bindTexture(n.TEXTURE_2D,J);n.texParameteri(n.TEXTURE_2D,n.TEXTURE_WRAP_S,n.REPEAT);n.texParameteri(n.TEXTURE_2D,n.TEXTURE_WRAP_T,n.REPEAT);n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,n.NEAREST);N=J;var I=J=n.RGBA,u=n.RGBA16F,q=n.RGBA32F;q&&(J=q);u&&(I=u);if((u||q)&&g(I,J,N))return p(),!0;J=I=n.RGBA;if(g(I,J,N))return p(),!0;r=k.RGBA8;p();return!1}}function p(){n.deleteProgram(H.da);n.deleteTexture(N);N=
H=null}for(var k={N:-1,cc:3,qa:2,RGBA8:0},r=k.N,f={Yc:null,Hc:null,Ga:null},v=!0,z=new Uint8Array(16),m=Array(64),l=0;4>l;++l)for(var x=0;4>x;++x){var y=0===(x+l)%2?1:0,h=4*l+x;m[4*h]=y;m[4*h+1]=y;m[4*h+2]=y;m[4*h+3]=y}var n=null,K=null,H=null,N=null,Q=null;return{Gd:function(J){t(J);return v},kc:function(J,I){r===k.N&&(typeof("undefined"!==I)&&(K=I),t(J));return r!==k.RGBA8},Yf:function(J){t(J);return r===k.cc},ze:function(J){t(J);return r===k.qa},Mf:function(J){t(J);return f.Yc},ee:function(J){t(J);
return f.Hc},m:function(){n=null;v=!0;r=k.N;K=null}}}(),Ya={instance:function(a){var c=R.instance(a.alpha),d=R.instance(a.beta);return{Vd:function(){c.g(1);d.g(2)}}}},db={instance:function(a){var c=null,d=!1,g=!1,t=null,p=!1,k=!1,r=null,f="undefined"===typeof a.preprocessing?!1:a.preprocessing,v="undefined"===typeof a.preprocessingSize?a.size:a.preprocessingSize;a.mask&&(d=!0,b&&void 0!==b.Bd&&(a.mask=b.Bd+a.mask),c=R.instance({isFloat:!1,url:a.mask}));var z=!1;a.customInputShader&&(z="s44",F.dc({name:"_",
id:z,h:a.customInputShader,og:["uSource"],precision:"lowp"}),F.I(z,[{type:"1i",name:"_",value:0}]));switch(f){case "sobel":r="s31";p=!0;break;case "meanNormalization":r="s32";p=!0;break;case "grayScale":r="s28";p=!1;break;case "grayScaleTilt":r="s29";k=!0;p=!1;break;case "rgbGrayTilt":r="s30";k=!0;p=!1;break;case "copy":r=z?z:"s0";break;case "inputLightRegulation":r=z?z:"s28";t=bb.instance({Gc:v,Xc:a.size,Tc:a.nBlurPass,Ra:!1});g=!0;break;case "inputMix0":r="none";t=cb.instance({ga:v,vd:a.varianceMin,
jc:a.blurKernelSizePx,Ra:!1});g=!0;break;case "direct":case "none":r="abort";break;default:r="s3"}k&&F.I(r,[{name:"u26",type:"1f",value:a.tilt}]);d&&(r+="Mask");var m=R.instance({isFloat:!1,isPot:!1,width:a.size}),l={A:function(){return v},ub:function(){return l.A()},le:function(){return g?t.vb():m},K:function(x){Va.U();"abort"!==r&&("none"!==r&&(F.set(r),p&&F.L("u27",1/a.size),m.P(),d&&c.g(1),O.l(!1,!1),m.g(0),x=m),g&&t.process(x))},m:function(){m.remove();d&&c.remove()}};return l}},kb={instance:function(a){function c(e){t.forEach(function(L,
G){p[G][0]=e[0][L];p[G][1]=e[1][L];p[G][2]=e[2][L];p[G][3]=e[3][L]});return p}"undefined"===typeof a.normalize&&(a.normalize=!1);var d={input:null,Ea:null,Ab:null,S:null,Va:null,Nb:null,Ob:null},g=null,t=[],p=[],k=!1,r=null,f=!0,v=-1,z=a.isReorganize?a.isReorganize:!1,m=a.kernelsCount?!0:!1,l=a.dynPelu?Ya.instance(a.dynPelu):!1,x=l?!0:!1,y={isEnabled:!1};a.xe?(a.sparsity="undefined"!==typeof a.sparsity?a.sparsity:a.Xa.ub(),f=!1):"full"===a.connectivityUp&&(a.sparsity=a.Xa.ub());var h={elu:"s15",elu01:"s16",
relu:"s14",arctan:"s18",sigmoid:"s13",copy:"s0",softplus:"s19",dynPelu:"s17"}[a.activation],n=a.sparsity*a.sparsity,K=!1,H=a.size,N="";if(a.maxPooling){switch(a.maxPooling.size){case 2:N="s33";break;case 4:N="s34"}K=!0;H/=a.maxPooling.size;d.Nb=R.instance({isFloat:!0,isPot:!1,width:H})}var Q=void 0!==a.Ee&&a.Ee?!0:!1,J=null,I=null,u=null;if(Q){J="s45"+a.index.toString();F.Ec("s45",J,[((a.normalization.n-1)/2).toFixed(1)]);F.I(J,[{type:"1i",name:"u1",value:0},{type:"2f",name:"u7",value:[1/a.size,1/
a.size]},{type:"1f",name:"u6",value:a.normalization.alpha},{type:"1f",name:"u9",value:a.normalization.beta},{type:"1f",name:"u30",value:a.normalization.k}]);var q={isFloat:!0,isPot:!0,width:a.size};I=R.instance(q);u=R.instance(q)}var C=-1,M=null;f&&(d.S=R.instance({isFloat:!0,isPot:!1,width:a.size}));d.Ea=R.instance(a.bias);var S={A:function(){return a.size},ub:function(){return H},yc:function(){return a.classesCount},Dd:function(e){g.g(e)},Ie:function(){a.remap&&a.remap.isEnabled&&(y={isEnabled:!0,
Ae:R.instance({isFloat:!1,isFlipY:!1,array:new Uint8Array(a.remap.maskTexture.data),width:a.remap.maskTexture.width,isPot:!1}),Ta:a.remap.layers.map(function(e){return a.parent.ie(e)}),depth:a.remap.depth})},$e:function(){switch(a.connectivityUp){case "direct":M=fb.instance(a.connectivity);break;case "square":M=gb.instance(a.connectivity);break;case "squareFast":M=hb.instance(a.connectivity,a.activation);break;case "full":M=ib.instance(a.connectivity);break;case "conv":v=a.kernelsCount,M=jb.instance(a.connectivity),
z&&(d.Va=R.instance({width:H,isFloat:!0,isFlipY:!1,isPot:!1}))}if(M.oa){var e=a.size*a.sparsity;C=Math.log(e/a.size)/Math.log(2);d.input=R.instance({isMipmap:!0,isFloat:!0,isPot:!0,width:e,Hb:C});d.Ab=R.instance({isFloat:!0,isPot:!0,width:a.size})}},K:function(e,L){g=e;M.oa?(d.input.P(),m&&d.Ea.g(2),M.K(y),d.input.g(0),d.input.Zd(C),d.Ab.P(),m?F.set("s0"):(F.set("s27"),F.L("u25",n),d.Ea.g(1)),d.input.Ed(C,0),O.l(!1,!1),F.set(h),Q?I.u():d.S.u(),d.Ab.g(0),x&&l.Vd(),O.l(!1,!1)):(d.S.P(),d.Ea.g(1),M.K());
Q&&(F.set(J),u.u(),I.g(0),O.l(!1,!1),F.set("s46"),F.L("u6",1),d.S.u(),u.g(1),O.l(!1,!1));if(f)return K?(d.Nb.P(),d.S.g(0),F.set(N),F.ea("u7",1/a.size,1/a.size),O.l(!1,!1),L=d.Nb):L=d.S,L.g(0),z&&(d.Va.u(),F.set("s21"),F.ea("u12",v,H/v),O.l(!1,!1),L=d.Va,d.Va.g(0)),L;var G=d.S;a.normalize&&(F.set("gpuRawAvg"===k?"s8":"s7"),F.L("u4",1/a.size),d.Ob.P(),d.S.g(0),O.l(!1,!1),G=d.Ob);e=null;switch(k){case "cpuRGBA2Float":G.qb(!1);L?e=S.Ke(G).then(r):(G=S.Le(G),r(G));break;case "cpuMeanFloat":G.qb(!0);L?
e=G.Ne().then(r):(G=G.Oe(),r(G));break;case "gpuRawAvg":case "gpuRaw":G.g(0);case "none":null!==r&&r(G)}L&&null===e&&(e=Promise.resolve());return e},Md:function(e){e&&(k=e.Pb||"none",r=e.Mb||null);d.S=R.instance({isFloat:!0,isPot:!0,isMipmap:!1,width:a.size});e="undefined"!==typeof a.classesCount&&a.classesCount?a.classesCount:a.size*a.size;for(var L=0,G=0,P=0;L<e;++L)t.push(G+(a.size-1-P)*a.size),p.push([-1,-1,-1,-1]),++G,G===a.size&&(G=0,++P);a.normalize&&(d.Ob=R.instance({isFloat:!0,isPot:!0,width:a.size}))},
Ke:function(e){return e.Me().then(c)},Le:function(e){e=e.Qb();c(e);return p},m:function(){for(var e in d){var L=d[e];L&&L.remove()}M&&(M.m(),M=null)}};a.Xa&&S.$e(a.Xa);return S}};
function lb(a){var c=null,d=null,g=null,t=0;this.s=function(p){this.Ye(p.Ta);g.Md({Pb:p.Pb,Mb:p.Mb})};this.ie=function(p){return c[p]};this.Ye=function(p){var k=null;t=p.length;c=p.map(function(r,f){r=Object.assign({},r,{index:f,parent:this,Xa:k,xe:f===t-1});return k=f=0===f?db.instance(r):kb.instance(r)});d=c[0];g=c[t-1];c.forEach(function(r,f){0!==f&&r.Ie()})};this.K=function(p){var k=p;c.forEach(function(r){k=r.K(k,!1)});return k};this.ge=function(){return d.A()};this.me=function(){return g.A()};
this.vb=function(){return g.le()};this.yc=function(){return g.yc()};this.m=function(){c&&(c.forEach(function(p){p.m()}),g=d=c=null,t=0)};"undefined"!==typeof a&&this.s(a)}
var fb={instance:function(a){var c=R.instance(a.weights);return{oa:!0,Ma:function(){return 1},m:function(){c.remove()},oe:function(){return c},K:function(){F.set("s26");c.g(1);O.l(!1,!1)}}}},ib={instance:function(a){var c=a.fromLayerSize,d=R.instance(a.weights);return{oa:!0,Ma:function(){return c},m:function(){d.remove()},K:function(g){if(g.isEnabled){F.set("s24");g.Ae.g(3);var t,p=Math.min(g.Ta.length,g.depth);for(t=0;t<p;++t)g.Ta[t].Dd(4+t)}else F.set("s23");F.L("u16",a.toLayerSize);d.g(1);O.l(!1,
!1)}}}},gb={instance:function(a){for(var c=a.fromLayerSize,d=a.toLayerSize,g=a.toSparsity,t=g*d,p=t/c,k=c/d,r=0,f=0,v=0,z=Array(g*d*g*d*4),m=Array(g*d*g*d*4),l=Array(c*c),x=0;x<l.length;++x)l[x]=0;x=Math.floor(g/2);for(var y=.5/d,h=.5/c,n=.5/t,K=0;K<d;++K)for(var H=Math.round(K*k),N=0;N<d;++N){var Q=Math.round(N*k),J=K/d,I=N/d;J+=y;I+=y;for(var u=0;u<g;++u){var q=H+u-x;0>q&&(q+=c);q>=c&&(q-=c);for(var C=0;C<g;++C){var M=r/t,S=f/t,e=Q+C-x;0>e&&(e+=c);e>=c&&(e-=c);var L=q/c,G=e/c;S=1-S-1/t;L+=h;G+=
h;M+=n;S+=n;var P=K*g+u,aa=N*g+C;aa=d*g-aa-1;P=aa*d*g+P;z[4*P]=M;z[4*P+1]=S;z[4*P+2]=L;z[4*P+3]=G;G=l[e*c+q]++;P=G%p;L=q*p+P;e=e*p+(G-P)/p;e=c*p-1-e;e=e*c*p+L;m[4*e]=M;m[4*e+1]=S;m[4*e+2]=J;m[4*e+3]=I;++r>=t&&(r=0,++f);++v}}}l=null;var W=R.instance(a.weights);delete a.weights.data;var ka=R.instance({width:t,isFloat:!0,array:new Float32Array(m),isPot:!0});m=null;var w=R.instance({width:t,isFloat:!0,array:new Float32Array(z),isPot:!0});z=null;return{oa:!0,Ma:function(){return p},m:function(){ka.remove();
w.remove();W.remove()},K:function(){F.set("s22");W.g(1);w.g(2);O.l(!1,!1)}}}},jb={instance:function(a){var c=a.kernelsCount,d=a.toSparsity,g=d*a.toLayerSize/a.fromLayerSize,t=R.instance(a.weights);return{oa:!0,Ma:function(){return g},Sf:function(){return d},oe:function(){return t},m:function(){t.remove()},K:function(){F.set("s25");F.L("u22",c);F.L("u23",d);F.L("u16",a.toLayerSize);F.L("u24",a.fromLayerSize);t.g(1);O.l(!1,!1)}}}},hb={instance:function(a,c){var d=a.fromLayerSize,g=a.toLayerSize,t=a.toSparsity,
p=a.stride?a.stride:1,k=t*g/d,r=g<d,f=d/g,v=R.instance(a.weights),z="s47"+[d.toString(),g.toString(),t.toString(),p.toString(),c].join("_");F.Yd(z)||(a=Oa(c),g=[{type:"1f",name:"u16",value:g},{type:"1f",name:"u29",value:p}],r&&g.push({type:"1f",name:"u24",value:d}),d=[(r?k:t).toFixed(1),a],r&&d.push(f.toFixed(1)),F.Ec(r?"s39":"s38",z,d),F.I(z,g.concat([{type:"1i",name:"u14",value:0},{type:"1i",name:"u21",value:1},{type:"1i",name:"u13",value:3}])));return{oa:!1,Ma:function(){return k},m:function(){v.remove()},
K:function(){F.set(z);v.g(3);O.l(!1,!1)}}}},bb={instance:function(a){var c=a.Tc?a.Tc:3,d=a.Gc?a.Gc:64,g=a.Xc?a.Xc:64,t=a.Ra?!0:!1;a={isFloat:!1,width:d,isPot:!1,isFlipY:!1};var p=R.instance(a),k=R.instance(a),r=R.instance(a),f=R.instance(a),v=R.instance({isFloat:!0,width:g,isPot:!1,isFlipY:!1}),z=1/d;return{process:function(m){F.set("s35");f.u();O.l(t,!1);F.set("s36");for(var l=0;l<c;++l)p.u(),F.ea("u7",z,0),O.l(t,!1),r.u(),f.g(0),O.l(t,!1),k.u(),p.g(0),F.ea("u7",0,z),O.l(t,!1),f.u(),r.g(0),O.l(t,
!1),l!==c-1&&k.g(0);F.set("s37");v.u();m.g(0);k.g(1);f.g(2);O.l(t,!1);v.g(0)},vb:function(){return v}}}},cb={instance:function(a){function c(v){return R.instance({isFloat:v,width:d.ga,isPot:!1,isFlipY:!1})}var d=Object.assign({vd:.1,jc:9,ga:128,Ra:!1},a),g=c(!1),t=[c(!1),c(!1),c(!1)],p=[c(!1),c(!1),c(!1)],k=c(!0),r=[g,p[0],p[1]];a="uniform sampler2D u1;const float e=1.1111,g=2.2222;uniform vec2 u31;varying vec2 vv0;void main(){float b=0.,c=0.;for(float a=-e;a<=e;a+=1.){vec2 i=u31*a,j=vv0+i*g;float d=1.2*a/e,f=exp(-d*d);b+=f*texture2D(u1,j).r,c+=f;}b/=c,gl_FragColor=vec4(b,0.,0.,1.);}".replace("1.1111",
Math.round((d.jc-1)/2).toFixed(2)).replace("2.2222",(1/d.ga).toFixed(6));var f={u1:0};F.ec([{id:"s49",name:"_",h:"uniform sampler2D u1;varying vec2 vv0;const vec3 f=vec3(.2126,.7152,.0722),g=vec3(1.,1.,1.);void main(){vec3 b=texture2D(u1,vv0).rgb;float a=dot(b,f);gl_FragColor=vec4(a,a,a,a);}",j:f,i:["u1"],precision:"lowp"},{id:"s50",name:"_",h:a,j:f,i:["u1","u31"],precision:"lowp"},{id:"s51",name:"_",h:"uniform sampler2D u32,u33,u34,u35;const float f=1.1111;const vec3 g=vec3(1.,1.,1.);varying vec2 vv0;void main(){vec3 a=texture2D(u32,vv0).rgb;float c=texture2D(u33,vv0).r,d=texture2D(u34,vv0).r,h=texture2D(u35,vv0).r,i=a.r*a.r;vec3 b=vec3(c,d,h),j=max(g*f,abs(i-b*b)),k=sqrt(j);gl_FragColor=vec4(a.r,(a-b)/k);}".replace("1.1111",
d.vd.toFixed(4)),j:{u32:0,u33:1,u34:2,u35:3},i:["u32","u33","u34","u35"],precision:"highp"}]);return{process:function(){F.set("s49");g.P();O.l(d.Ra,!1);F.set("s50");for(var v=0;3>v;++v)F.ea("u31",1,0),t[v].u(),r[v].g(0),O.l(!1,!1),F.ea("u31",0,1),p[v].u(),t[v].g(0),O.l(!1,!1);F.set("s51");k.u();g.g(0);p[0].g(1);p[1].g(2);p[2].g(3);O.l(!1,!1);k.g(0)},vb:function(){return k}}}};function mb(a,c){a[c]=!0;a.setAttribute(c,"true")}
function nb(){return/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream}function ob(){var a=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);return a&&a.length&&2<a.length?[parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3]||0,10)]:[0,0,0]}function pb(){var a=navigator.userAgent.toLowerCase();return-1!==a.indexOf("safari")&&-1===a.indexOf("chrome")?!0:!1}function qb(){return navigator.mediaDevices&&navigator.mediaDevices.getUserMedia?!0:!1}
function rb(a){if(!a)return a;var c=null;if(a.video){var d=function(g){return g&&"object"===typeof g?Object.assign({},g):g};c={};"undefined"!==typeof a.video.width&&(c.width=d(a.video.width));"undefined"!==typeof a.video.height&&(c.height=d(a.video.height));"undefined"!==typeof a.video.facingMode&&(c.facingMode=d(a.video.facingMode))}c={audio:a.audio,video:c};"undefined"!==typeof a.deviceId&&sb(c,a.deviceId);return c}
function sb(a,c){c&&(a.video=a.video||{},a.video.deviceId={exact:c},a.video.facingMode&&delete a.video.facingMode)}function ub(a){var c=a.video.width;a.video.width=a.video.height;a.video.height=c;return a}
function vb(a){function c(l){return[480,576,640,648,720,768,800,960,1080,1152,1280,1366,1920].sort(function(x,y){return Math.abs(x-l)-Math.abs(y-l)})}function d(l){var x=rb(a);l=l(x);t.push(l);g(l)}function g(l){if(l.video&&l.video.facingMode&&l.video.facingMode.exact){var x=l.video.facingMode.exact;l=rb(l);delete l.video.facingMode.exact;l.video.facingMode.ideal=x;t.push(l)}}var t=[];if(!a||!a.video)return t;g(a);if(a.video.width&&a.video.height){if(a.video.width.ideal&&a.video.height.ideal){var p=
c(a.video.width.ideal).slice(0,3),k=c(a.video.height.ideal).slice(0,3),r={},f=0;for(r.aa=void 0;f<p.length;r={aa:r.aa},++f){r.aa=p[f];var v={},z=0;for(v.$=void 0;z<k.length;v={$:v.$},++z)if(v.$=k[z],r.aa!==a.video.width.ideal||v.$!==a.video.height.ideal){var m=Math.max(r.aa,v.$)/Math.min(r.aa,v.$);m<4/3-.1||m>16/9+.1||d(function(l,x){return function(y){y.video.width.ideal=l.aa;y.video.height.ideal=x.$;return y}}(r,v))}}}d(function(l){return ub(l)})}a.video.width&&a.video.height&&(a.video.width.ideal&&
a.video.height.ideal&&d(function(l){delete l.video.width.ideal;delete l.video.height.ideal;return l}),d(function(l){delete l.video.width;delete l.video.height;return l}));a.video.facingMode&&(d(function(l){delete l.video.facingMode;return l}),a.video.width&&a.video.height&&d(function(l){ub(l);delete l.video.facingMode;return l}));t.push({audio:a.audio,video:!0});return t}
function wb(a){try{var c=window.matchMedia("(orientation: portrait)").matches?!0:!1}catch(g){c=window.innerHeight>window.innerWidth}if(c&&a&&a.video){c=a.video.width;var d=a.video.height;c&&d&&c.ideal&&d.ideal&&c.ideal>d.ideal&&(a.video.height=c,a.video.width=d)}}
function xb(a){a.volume=0;mb(a,"muted");if(pb()){if(1===a.volume){var c=function(){a.volume=0;window.removeEventListener("mousemove",c,!1);window.removeEventListener("touchstart",c,!1)};window.addEventListener("mousemove",c,!1);window.addEventListener("touchstart",c,!1)}setTimeout(function(){a.volume=0;mb(a,"muted")},5)}}
function yb(a,c,d,g){function t(k){p||(p=!0,d(k))}var p=!1;navigator.mediaDevices.getUserMedia(g).then(function(k){function r(){setTimeout(function(){if(a.currentTime){var v=a.videoWidth,z=a.videoHeight;if(0===v||0===z)t("VIDEO_NULLSIZE");else{v&&(a.style.width=v.toString()+"px");z&&(a.style.height=z.toString()+"px");v={Id:null,cf:null,Be:null};try{var m=k.getVideoTracks()[0];m&&(v.Be=m,v.Id=m.getCapabilities(),v.cf=m.getSettings())}catch(l){}pb()||nb()?a.parentNode&&null!==a.parentNode?(p||c(a,k,
v),setTimeout(function(){a.play()},100)):(document.body.appendChild(a),xb(a),p||c(a,k,v),setTimeout(function(){a.style.transform="scale(0.0001,0.0001)";a.style.position="fixed";a.style.bottom="0px";a.style.right="0px";xb(a);setTimeout(function(){a.play()},100)},80)):p||c(a,k,v)}}else t("VIDEO_NOTSTARTED")},700)}function f(){a.removeEventListener("loadeddata",f,!1);var v=a.play();xb(a);"undefined"===typeof v?r():v.then(function(){r()}).catch(function(){t("VIDEO_PLAYPROMISEREJECTED")})}"undefined"!==
typeof a.srcObject?a.srcObject=k:(a.src=window.URL.createObjectURL(k),a.videoStream=k);xb(a);a.addEventListener("loadeddata",f,!1)}).catch(function(k){t(k)})}
function zb(a,c,d){var g=qb()?document.createElement("video"):!1;if(g)if(qb()){if(d&&d.video){if(nb()){var t=ob();0!==t[0]&&(12>t[0]||12===t[0]&&2>t[1])&&wb(d)}d.video.width&&d.video.width.ideal&&(g.style.width=d.video.width.ideal+"px");d.video.height&&d.video.height.ideal&&(g.style.height=d.video.height.ideal+"px")}mb(g,"autoplay");mb(g,"playsinline");d&&d.audio?g.volume=0:mb(g,"muted");yb(g,a,function(){function p(r){if(0===r.length)c("INVALID_FALLBACKCONSTRAINTS");else{var f=r.shift();yb(g,a,function(){p(r)},
f)}}var k=vb(d);p(k)},d)}else c&&c("MEDIASTREAMAPI_NOTFOUND");else c&&c("VIDEO_NOTPROVIDED")}
var Ab=function(){var a={n:5,Jb:1,Rc:0,Ka:[30,45],Ha:[2,200],k:.7,lf:200,He:.05},c=-1,d=null,g=-1,t=-1,p=0,k=-1,r=-1,f=0,v=0,z=a.Ha[1],m={je:function(){switch(c){case -1:return-1;case 0:return r+d.Rc;case 1:return f}},ae:function(l){return Math.pow(Math.min(Math.max(k,0),d.n-1)/(d.n-1),l||1)},s:function(l){d=Object.assign({},a,l);k=r=d.Jb;c=0;m.reset()},ff:function(l){l=("undefined"===typeof l?Date.now():l)||0;var x=Math.min(Math.max(l-v,d.Ha[0]),d.Ha[1]);z=x;v=l;var y=-1===g?0:d.k;g=Math.min(Math.max(1E3/
x,5),120)*(1-y)+g*y;l-t>d.lf&&5<++p&&(x=d.k,k=k*(1-x)+(g<d.Ka[0]?r-1:g>d.Ka[1]?r+1:r)*x,Math.abs(k-r)>1-d.He&&(x=Math.min(Math.max(Math.round(k),0),d.n-1),x!==r&&(k=r=x,g=(d.Ka[1]-d.Ka[0])/2)),t=l)},Xe:function(l){f=l;c=1},kf:function(){c=0;m.reset()},reset:function(){z=a.Ha[1];t=g=-1;p=0},Jf:function(){return z}};return m}(),Bb=function(){var a={Vc:4,Wa:[1.5,1.5,2],fa:[.1,.1,.1],hd:1,ga:-1,xb:-1,ef:2,Ge:1,kd:!0,Wd:.8},c=null,d=[],g=0,t=[.5,.5,1];return{s:function(p){c=Object.assign({},a,p);d.splice(0);
p=c.Wa[0]*c.fa[0];var k=c.Wa[1]*c.fa[1],r=1/(1+c.Wa[2]*c.fa[2]),f=c.hd*Math.min(c.ga,c.xb),v=f/c.ga;f/=c.xb;var z=.5*c.Wd;z*=z;for(var m=0;m<c.Vc;++m){var l=Math.pow(r,m),x=v*l,y=f*l;l=x*p;var h=y*k,n=x/2;y/=2;for(var K=1+(1-n-n)/l,H=1+(1-y-y)/h,N=0;N<H;++N)for(var Q=y+N*h,J=Q-.5,I=0;I<K;++I){var u=n+I*l,q=u-.5;q*q+J*J>z||d.push([u,Q,x*c.Ge])}}c.kd&&d.sort(function(C,M){var S=C[0]-.5;C=C[1]-.5;var e=M[0]-.5;M=M[1]-.5;return S*S+C*C-(e*e+M*M)})},get:function(){var p=d.length;if(0===p)return t;g>=p&&
(g=0);var k=d[Math.floor(g)];g=(g+1/c.ef)%p;return k}}}(),Cb=function(){function a(){d(z+f.Ib)}function c(){y.Ca=0===f.ia?window.requestAnimationFrame(d):window.requestAnimationFrame(g)}function d(H){x.la&&null!==v&&(H-=z,H=Math.min(Math.max(H,f.mc[0]),f.mc[1]),z+=H,p(),v(z))}function g(H){x.la&&(y.timeout=window.setTimeout(d.bind(null,H),f.ia))}function t(){v=null;x.la=!1;p()}function p(){y.Ca&&(window.cancelAnimationFrame(y.Ca),y.Ca=null);y.timeout&&(window.clearTimeout(y.timeout),y.timeout=null)}
function k(H){H?(x.ma=!0,l&&Ab.kf(),m.port.postMessage("STOP"),Ta.sd(!0),c()):(x.ma=!1,l&&Ab.Xe(1),Ta.sd(!1),m.port.postMessage("START"))}var r={Lc:!0,mc:[1,200],Ib:50,ia:0},f=null,v=null,z=0,m=null,l=!1,x={ca:!1,ma:!0,Fb:!1,Eb:!1,Cb:!1,la:!1},y={Ca:null,timeout:null},h=k.bind(null,!0),n=k.bind(null,!1),K={s:function(H){f=Object.assign(r,H);Object.assign(x,{ma:!0,ca:!0,la:!1});if(f.Lc){H=!1;try{if("undefined"===typeof SharedWorker){var N=URL.createObjectURL(new Blob(["let handler = null;\n      self.addEventListener('message', function(e){\n        switch (e.data) {\n          case 'START':\n            if (handler === null){\n              handler = setInterval(function(){\n                self.postMessage('tick');\n              }, "+
f.Ib.toString()+");\n            }\n            break;\n          case 'STOP':\n            if (handler !== null){\n              clearInterval(handler);\n              handler = null;\n            }\n            break;\n        };\n      }, false);"],{type:"text/javascript"})),Q=new Worker(N);Q.addEventListener("message",a);m={Zc:Q,port:Q};x.Fb=!0}else{var J=URL.createObjectURL(new Blob(["let handler = null;\n      onconnect = function(e) {\n        const port = e.ports[0];\n        port.addEventListener('message', function(e) {\n          \n          switch (e.data) {\n            case 'START':\n              if (handler === null){\n                handler = setInterval(function(){\n                  port.postMessage('tick');\n                }, "+
f.Ib.toString()+");\n              }\n              break;\n            case 'STOP':\n              if (handler !== null){\n                clearInterval(handler);\n                handler = null;\n              }\n              break;\n          };\n          \n        });\n        \n        port.start();\n      } // end onconnect()"],{type:"text/javascript"})),I=new SharedWorker(J);I.port.start();I.port.addEventListener("message",a);m={Zc:I,port:I.port};x.Eb=!0}H=!0}catch(u){}H&&(window.addEventListener("blur",
n),window.addEventListener("focus",h),x.Cb=!0)}l="undefined"!==typeof Ab},m:function(){t();x.Cb&&(window.removeEventListener("blur",n),window.removeEventListener("focus",h),x.Cb=!1);x.Eb?(m.port.close(),x.Eb=!1):x.Fb&&(m.Zc.terminate(),x.Fb=!1);Object.assign(x,{ma:!0,ca:!1,la:!1});v=null},bg:function(){return x.ma},update:function(H){Object.assign(f,H)},Te:function(H){x.ca||K.s({});p();x.la=!0;v=H;x.ma&&c()},stop:t};return K}(),Db=function(){var a=0,c=null,d=null,g=null,t=null;return{s:function(p,
k){a=p.length;c=k;d=p;g=new Float32Array(a);t=new Float32Array(a)},ke:function(){return t},df:function(p,k,r){p.forEach(function(f,v){var z=Math.min(1,d[v]*r*(k+.33*(1-k)));f=z*f+(1-z)*g[v];g[v]=f;t[v]=c[v](f)})}}}(),V={VERSION:"1.2.4",ha:[],hb:!1,ib:!1,gb:!1,Ba:!0,Aa:!1,ready:!1,initialized:!1},Eb={facingMode:"user",idealWidth:800,idealHeight:600,minWidth:240,maxWidth:1280,minHeight:240,maxHeight:1280,isAudio:!1},b={neuralNetworkPath:"jeelizFaceTransferNNC.json",
bc:"../../",ia:0,width:512,height:512,gf:30,jd:[.6,5.8],fa:[.06,.08,.15],We:.7,Ue:2,Ve:[2,2,2],threshold:.9,zd:[.03,1],rf:20,re:!1,fb:[2,7],H:{Cc:[3,7],quality:[0,6],position:[0,7],rotation:[5,7]},Uc:11,Sc:1,Ce:1,fc:[.1,.01],Re:[.4,-.7,-.4],Se:[.3,0,0],Ud:!1,Ad:.001,hc:[Math.PI/10,Math.PI/6],ad:[.1,.4],bd:[.009,.02],cd:[.02,.04],Kb:5,Dc:.05,yd:[.2,.2,.15,.15,.15,.15,.2,.2,.15,.15,.2],De:[Ia.bind(null,.05,.7),Ia.bind(null,.05,.7),Ia.bind(null,0,.4),Ia.bind(null,0,.4),Ia.bind(null,0,.6),Ia.bind(null,
0,.6),Ja.bind(null,.05,.5),Ia.bind(null,.2,.6),Ka.bind(null,.7,.8,2),Ka.bind(null,.7,.8,2),Ia.bind(null,.15,.5)]};V.get_nMorphs=function(){return b.Uc};var Fb=null,Gb=null,Hb=null,Ib=[];
function Jb(){function a(){1===++L&&(Db.s(b.yd,b.De),c(),V.ready=!0,V.ha.forEach(function(A){A()}),V.ha.splice(0,V.ha.length),d(),L=0)}function c(){H=Da();N=new Uint8Array(y*y*4);V.get_morphTargetInfluences=function(){return H};V.get_morphTargetInfluencesStabilized=function(){return Db.ke()};V.set_morphUpdateCallback=function(A){Q=A};V.get_rotation=function(){return u};V.get_positionScale=function(){var A=n.qd.he();A.qb(!1);A=A.Qb();M[0]=1-A[1][0];M[1]=A[2][0];M[2]=A[3][0]*h[0];return M};V.get_rotationStabilized=
function(){return C};V.switch_sleep=function(A){P!==G.Vb||A?P=A?G.Vb:G.play:d()};V.on_detect=function(A){A(aa.R);aa.Lb.push(A)};V.is_detected=function(){return aa.R};V.set_animateDelay=function(A){l=A;Cb.update({ia:l})}}function d(){P!==G.play&&(P=G.play,Cb.stop(),g())}function g(){var A,E;return Aa(new wa(new na(function(ca){switch(ca.Y){case 1:a:{if("VIDEO"===e.element.nodeName){var Y=e.element.currentTime-ka;0>Y&&(ka=e.element.currentTime);if(1E3*Y<b.rf)break a;ka+=Y}e.pa.refresh();Y=w.Ac();Y[0]===
e.Fa[0]&&Y[1]===e.Fa[1]||w.ud()}A=Ab.je();E=0;case 2:if(!(E<A)){ca.Y=4;break}Y=n;var pa=x;F.set("s53");Va.U();Y.Pa.P();e.pa.g(0);Y.ab.g(1);O.l(!1,!1);Y.Pa.g(0);pa.K(Y.Pa);b.re?Y=R.Qe(J,N).then(t):(R.Pe(J,N),t(),Y=Promise.resolve());ca.Y=3;return{value:Y};case 3:++E;ca.Y=2;break;case 4:Y=n,Va.U(),K.P(),F.set("s56"),Y.ab.g(0),O.l(!1,!1),Y=Ab.ae(),S=3*(1-Y)+1*Y,Ab.ff(),V.Ba&&(Va.jf(),F.set("s52"),e.pa.g(0),O.l(!1,!1),D.enable(D.BLEND),D.blendFunc(D.SRC_ALPHA,D.ONE),K.g(0),O.l(!1,!1),D.disable(D.BLEND)),
D.flush(),P!==G.Vb&&Cb.Te(g),ca.Y=0}})))}function t(){r();if(!b.Ud&&aa.R)for(var A=0;3>A;++A){var E=k(A+b.H.rotation[0],b.H.rotation[1]);E=(2*E-1)*b.Re[A];E+=b.Se[A];I[A]=E}p();A=Date.now();E=A-W.Pc;var ca=k(b.H.quality[0],b.H.quality[1]);W.$c=Ja(b.ad[0],b.ad[1],ca);ca=k(b.H.position[0],b.H.position[1]);var Y=k(b.H.position[0]+1,b.H.position[1]),pa=k(b.H.position[0]+2,b.H.position[1]);W.gd=1-Ja(b.cd[0],b.cd[1],Math.sqrt(ca*ca+Y*Y+pa*pa)/E);ca=W.na[0]-I[0];Y=W.na[1]-I[1];pa=W.na[2]-I[2];E=Math.sqrt(ca*
ca+Y*Y+pa*pa)/E;W.na[0]=I[0];W.na[1]=I[1];W.na[2]=I[2];W.dd=1-Ja(b.bd[0],b.bd[1],E);W.O=W.$c*W.gd*W.dd;W.Pc=A;W.Oc[W.Gb]=W.O;W.Gb=(W.Gb+1)%b.Kb;for(A=0;A<b.Kb;++A)W.O=Math.min(W.Oc[A],W.O);Db.df(H,W.O,S);Q&&Q(W.O,S);if(aa.R)for(A=b.fc[1]*W.O+b.fc[0]*(1-W.O),A*=S,E=0;3>E;++E)u[E]=A*I[E]+(1-A)*u[E],C[E]=u[E];else A=Date.now()*b.Ad,q[0]=b.hc[0]*Math.sin(A),q[1]=b.hc[1]*Math.cos(A),C[0]=q[0],C[1]=q[1],C[2]=q[2]}function p(){var A=k(b.H.Cc[0],b.H.Cc[1]);aa.Qa=b.Dc*A+(1-b.Dc)*aa.Qa;.6<aa.Qa&&!aa.R?(aa.Lb.forEach(function(E){E(!0)}),
aa.R=!0):.4>aa.Qa&&aa.R&&(aa.Lb.forEach(function(E){E(!1)}),aa.R=!1)}function k(A,E){A+=y*E;return(N[4*A]+N[4*A+1]+N[4*A+2]+N[4*A+3])/1020}function r(){H.forEach(function(A,E){if(aa.R){A=(b.Sc+E)%y;var ca=b.Ce+Math.floor((b.Sc+E)/y);ca=y-1-ca;A=k(A,ca);H[E]=A}else H[E]=0})}function f(A){x=new lb({Ta:A.layers,Pb:"gpuRaw",Mb:function(E){var ca=n;ca.ab.nd(1);D.viewport(0,0,1,1);F.set("s54");F.L("u36",W.O);F.od("u37",Bb.get());F.od("u38",b.fa);O.l(!1,!1);ca.qd.nd(1);F.set("s55");F.L("u36",W.O);ca.ab.g(0);
O.l(!1,!1);J=E}});A=x.ge();A!==m&&(m=A,w.Fc(),n.Pa.resize(m,m),w.pd());y=x.me();a()}var v=-1,z=-1,m=64,l=b.ia,x=null,y=0,h=null,n={},K=null,H=null,N=null,Q=null,J=null,I=[0,0,0],u=[0,0,0],q=[0,0,0],C=[0,0,0],M=[0,0,0],S=1,e={qf:[.5,.5],pf:[.5,.5],element:null,pa:null,Fa:[-1,-1]},L=0,G={Qd:-4,Fe:-3,cg:-2,Vb:-1,play:0},P=G.Fe,aa={Qa:0,R:!1,Lb:[]},W={O:1,gd:1,$c:1,dd:1,na:[0,0,0],Pc:Date.now(),Oc:new Float32Array(b.Kb),Gb:0},ka=0,w={Fc:function(){v=b.width;z=b.height;Bb.s({Wa:b.Ve,Vc:b.Ue,ga:v,xb:z,
hd:b.We,fa:b.fa,kd:!0});h=[1,v/z]},pd:function(){F.I("s52",[{type:"1i",name:"u1",value:0}]);F.I("s53",[{type:"1i",name:"u1",value:0},{type:"1i",name:"u39",value:1},{type:"2f",name:"u40",value:h}]);F.I("s56",[{type:"1i",name:"u39",value:0},{type:"2f",name:"u40",value:h},{type:"3f",name:"u41",value:[0,.5,1]}]);F.I("s54",[{type:"1i",name:"u42",value:0},{type:"1i",name:"u39",value:1},{type:"1f",name:"u43",value:b.jd[0]},{type:"1f",name:"u44",value:b.jd[1]},{type:"1f",name:"u45",value:b.gf},{type:"1f",
name:"u46",value:b.threshold},{type:"1f",name:"u47",value:h[0]}]);F.I("s55",[{type:"1i",name:"u1",value:0},{type:"1i",name:"u5",value:1},{type:"2f",name:"u48",value:b.zd}])},Nd:function(){F.ec([{id:"s52",name:"_",za:"attribute vec2 a0;uniform vec2 u49,u50;varying vec2 vv0;void main(){gl_Position=vec4(a0,0.,1.),vv0=u50+u49*a0;}",Da:["a0"],sa:[2],h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",i:["u1","u49","u50"],precision:"lowp"},{id:"s53",name:"_",h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",
za:"attribute vec2 a0;uniform sampler2D u39;uniform vec2 u40,u49,u50;const vec2 f=vec2(.25,.5),i=vec2(.75,.5),e=vec2(.5,.5);varying vec2 vv0;void main(){vec4 a=texture2D(u39,f);vec2 b=a.gb,c=a.a*u40,d=a0*.5+e,h=b+(d-e)*c;vv0=u50+u49*2.*(h-.5),gl_Position=vec4(a0,0.,1.);}",Da:["a0"],sa:[2],i:["u1","u39","u40","u49","u50"],precision:"lowp"},{id:"s54",name:"_",za:"attribute vec2 a0;void main(){gl_Position=vec4(a0,0.,1.);}",h:"uniform sampler2D u42,u39;uniform vec3 u37,u38;uniform float u43,u44,u45,u46,u47,u36;varying vec2 vv0;const vec4 e=vec4(.25,.25,.25,.25);void main(){vec4 c=texture2D(u42,vec2(.4375,.9375)),d=texture2D(u42,vec2(.5625,.9375));float f=dot(c-d,e);bool g=f>u46;vec4 a=texture2D(u39,vec2(.5,.5));g?a.r=2.:a.r>u45?a.r=0.:a.r>1.9&&(a.a>u44||a.a<u43)?a.r=0.:a.r>1.9?a.r+=1.:0.;if(a.r<.9)a.gba=u37,a.r=1.;else{float h=dot(e,texture2D(u42,vec2(.0625,.9375))),i=dot(e,texture2D(u42,vec2(.1875,.9375))),j=dot(e,texture2D(u42,vec2(.3125,.9375))),b;if(a.r>1.9)b=1.-u36;else b=1.,a.r=0.;float k=a.a*u47;a.gba+=vec3(h,i,j)*u38*b*k;}gl_FragColor=a;}",
i:"u42 u39 u37 u43 u44 u45 u46 u38 u47 u36".split(" ")},{id:"s56",name:"_",h:"uniform sampler2D u39;uniform vec3 u41;uniform vec2 u40;varying vec2 vv0;const vec2 i=vec2(1.,1.);void main(){vec4 f=texture2D(u39,vec2(.25,.5));vec2 g=f.gb;float j=f.a;vec2 a=j*u40,c=g+a,d=g;d-=a/2.,c-=a/2.;vec2 k=.5*(d+c),h=step(d,vv0)*step(vv0,c);float l=h.x*h.y;vec2 b=2.*abs(k-vv0)/a;b=pow(b,3.*i),gl_FragColor=vec4(l*u41*max(b.x,b.y),1.);}",i:["u39","u40","u41"],precision:"lowp"},{id:"s55",name:"_",h:"uniform sampler2D u1,u5;uniform vec2 u48;uniform float u36;const vec4 f=vec4(1.,1.,1.,1.);varying vec2 vv0;void main(){vec4 a=texture2D(u1,vv0),b=texture2D(u5,vv0);float c=(1.-u36)*(u48.y-u48.x)+u48.x;gl_FragColor=mix(b,a,c*f);}",
i:["u1","u5","u48","u36"]}])},qe:function(A){var E=new Float32Array([0,.5,.5,0]);A.Pa=R.instance({isPot:!0,isFloat:!1,width:m});E={width:1,height:1,isFloat:!0,isPot:!1,array:E};A.ab=Xa.instance(E);A.qd=Xa.instance(E)},Od:function(){e.pa=R.instance({C:e.element,isPot:!1,isFloat:!1,isFlipY:!0});K=R.instance({isPot:!1,isFloat:!1,width:v,height:z})},s:function(){w.Od();w.qe(n);Cb.s({Lc:!1,ia:l});Ab.s({Jb:0,n:b.fb[1]-b.fb[0]+1,Rc:b.fb[0]});Hb?f(Hb):Ca(function(A){A=JSON.parse(A);f(A)})},m:function(){Cb.stop();
x&&(x.m(),x=null);P=G.Qd},Jd:function(A){V.hb&&V.hb();var E={video:{facingMode:{ideal:Eb.facingMode},width:{min:Eb.minWidth,max:Eb.maxWidth,ideal:Eb.idealWidth},height:{min:Eb.minHeight,max:Eb.maxHeight,ideal:Eb.idealHeight}},audio:Eb.isAudio};sb(E,Eb.deviceId);zb(function(ca,Y){Fb=Y;V.ib&&V.ib();A(ca)},function(){window.eb&&window.eb("WEBCAM_UNAVAILABLE")},E)},Qc:function(A,E){w.Nd();e.element=A;Gb=e.element;w.ud();w.Fc();w.pd();w.s();E&&E()},Ac:function(){var A=[-1,-1],E=e.element;"VIDEO"===E.nodeName?
(A[0]=E.videoWidth,A[1]=E.videoHeight):(A[0]=E.width,A[1]=E.height);return A},ud:function(){var A=w.Ac();e.Fa[0]=A[0];e.Fa[1]=A[1];Wa.La().width=A[0];Wa.La().height=A[1];b.width=A[0];b.height=A[1];var E=e.qf,ca=e.pf,Y=A[1]/A[0];A=Wa.J()/Wa.A();Y>A?1>=Y?E[0]*=Y:E[1]/=Y:(E[0]*=Y,Y=1/A,E[0]*=Y,E[1]*=Y);E[1]*=A;E=[{type:"2f",name:"u49",value:E},{type:"2f",name:"u50",value:ca}];F.I("s53",[{type:"1i",name:"u1",value:0}].concat(E));F.I("s52",E)}};Ib.push(w);return w}V.onLoad=function(a){V.ready?a():V.ha.push(a)};
V.switch_displayVideo=function(a){V.Ba=a;V.Aa&&(V.Aa.style.display=V.Ba?"block":"none")};V.onWebcamAsk=function(a){V.hb=a};V.onContextLost=function(a){V.gb=a};V.onWebcamGet=function(a){V.ib=a};V.destroy=function(){Cb.m();Gb&&Gb.srcObject&&Gb.srcObject.getTracks().forEach(function(a){a.stop()});Ib.forEach(function(a){a.m()});Ib.splice(0);Wa.m();V.switch_displayVideo(!1);V.initialized=!1;V.ha.splice(0)};V.set_size=function(a,c){b.width=a;b.height=c};V.get_size=function(){return{width:b.width,height:b.height}};
V.get_videoStream=function(){return Fb};V.get_video=function(){return Gb};V.get_cv=function(){return Wa.La()};V.set_color=function(a){F.I("s56",[{type:"3f",name:"u41",value:a}])};
V.init=function(a){var c=Jb(),d=a.callbackReady?a.callbackReady:function(p){console.log("ERR:",p)},g=a.callbackReady?a.callbackReady.bind(null,!1):!1;if(a.canvasId||a.canvas){var t=a.canvas?a.canvas:document.getElementById(a.canvasId);if(t)if(V.initialized)d("ALREADY_INITIALIZED");else{V.initialized=!0;window.eb=d?function(p){d(p);window.eb=!1}:!1;a.NNCPath&&(b.bc=a.NNCPath);"undefined"!==typeof a.NNC&&(Hb="string"===typeof a.NNC?JSON.parse(a.NNC):a.NNC);g&&V.ha.push(g);if(!Wa.s({ob:t,width:b.width,
height:b.height,debug:!1,Bb:!1,Wc:function(){V.gb&&V.gb()},premultipliedAlpha:!1}))return d("GL_INCOMPATIBLE"),!1;V.Aa=Wa.La();V.Ba||(V.Aa.style.display="none");O.s();Va.s();F.s();R.s();D.depthFunc(D.LEQUAL);D.clearDepth(1);a.videoSettings&&a.videoSettings.videoElement?c.Qc(a.videoSettings.videoElement,!1):(a.videoSettings&&Object.assign(Eb,a.videoSettings),c.Jd(function(p){c.Qc(p,!1)}));return!0}else d("INVALID_CANVAS")}else d("NO_CANVASID")};const JEELIZFACEEXPRESSIONS=V;
if(typeof(module)!=='undefined'){module.exports=JEELIZFACEEXPRESSIONS;}
/* eslint-enable */
