/* eslint-disable */
function ba(){this.va=!1;this.$=null;this.wd=void 0;this.Z=1;this.vc=this.Kd=0;this.ra=null}function da(a){if(a.va)throw new TypeError("Generator is already running");a.va=!0}ba.prototype.wa=function(a){this.wd=a};ba.prototype.ya=function(a){this.ra={Xd:a,ue:!0};this.Z=this.Kd||this.vc};ba.prototype.return=function(a){this.ra={return:a};this.Z=this.vc};function ka(a){this.o=new ba;this.Je=a}ka.prototype.wa=function(a){da(this.o);if(this.o.$)return oa(this,this.o.$.next,a,this.o.wa);this.o.wa(a);return ra(this)};
function ta(a,c){da(a.o);var d=a.o.$;if(d)return oa(a,"return"in d?d["return"]:function(h){return{value:h,done:!0}},c,a.o.return);a.o.return(c);return ra(a)}ka.prototype.ya=function(a){da(this.o);if(this.o.$)return oa(this,this.o.$["throw"],a,this.o.wa);this.o.ya(a);return ra(this)};
function oa(a,c,d,h){try{var t=c.call(a.o.$,d);if(!(t instanceof Object))throw new TypeError("Iterator result "+t+" is not an object");if(!t.done)return a.o.va=!1,t;var n=t.value}catch(l){return a.o.$=null,a.o.ya(l),ra(a)}a.o.$=null;h.call(a.o,n);return ra(a)}
function ra(a){for(;a.o.Z;)try{var c=a.Je(a.o);if(c)return a.o.va=!1,{value:c.value,done:!1}}catch(d){a.o.wd=void 0,a.o.ya(d)}a.o.va=!1;if(a.o.ra){c=a.o.ra;a.o.ra=null;if(c.ue)throw c.Xd;return{value:c.return,done:!0}}return{value:void 0,done:!0}}function ua(a){this.next=function(c){return a.wa(c)};this.throw=function(c){return a.ya(c)};this.return=function(c){return ta(a,c)};this[Symbol.iterator]=function(){return this}}
function Aa(a){function c(h){return a.next(h)}function d(h){return a.throw(h)}return new Promise(function(h,t){function n(l){l.done?h(l.value):Promise.resolve(l.value).then(c,d).then(n,t)}n(a.next())})}function Ca(a){var c=new XMLHttpRequest;c.open("GET",b.bc+b.neuralNetworkPath,!0);c.withCredentials=!1;c.onreadystatechange=function(){4!==c.readyState||200!==c.status&&0!==c.status||a(c.responseText)};c.send()}function Da(){for(var a=b.Uc,c=Array(a),d=0;d<a;++d)c[d]=0;return c}
function Ha(a,c){if(0===c||"object"!==typeof a)return a;a=Object.assign({},a);c=void 0===c||-1===c?-1:c-1;for(var d in a)a[d]=Ha(a[d],c);return a}function Ia(a,c,d){return Math.min(Math.max((d-a)/(c-a),0),1)}
function Ja(a){switch(a){case "relu":return"gl_FragColor=max(vec4(0.,0.,0.,0.),gl_FragColor);";case "elu":return"gl_FragColor=mix(exp(-abs(gl_FragColor))-vec4(1.,1.,1.,1.),gl_FragColor,step(0.,gl_FragColor));";case "elu01":return"gl_FragColor=mix(0.1*exp(-abs(gl_FragColor))-vec4(0.1,0.1,0.1,0.1),gl_FragColor,step(0.,gl_FragColor));";case "arctan":return"gl_FragColor=atan(3.14159265359*texture2D(u0,vUV))/3.14159265359;";case "copy":return"";default:return!1}}
function Na(a,c){var d=c%8;return a[(c-d)/8]>>7-d&1}
function Oa(a){var c=JSON.parse(a);a=c.ne;var d=c.nf,h=c.n;var t="undefined"===typeof btoa?Buffer.from(c.data,"base64").toString("latin1"):atob(c.data);var n=t.length;c=new Uint8Array(n);for(var l=0;l<n;++l)c[l]=t.charCodeAt(l);t=new Float32Array(h);n=new Float32Array(d);l=a+d+1;for(var r=0;r<h;++r){for(var f=l*r,u=0===Na(c,f)?1:-1,y=f+1,p=1,k=0,A=y+a-1;A>=y;--A)k+=p*Na(c,A),p*=2;y=k;f=f+1+a;p=n.length;k=0;for(A=f;A<f+p;++A)n[k]=Na(c,A),++k;for(p=f=0;p<d;++p)f+=n[p]*Math.pow(2,-p-1);t[r]=0===f&&0===
y?0:u*(1+f)*Math.pow(2,1+y-Math.pow(2,a-1))}return t}
var G=function(){function a(v,q,C){q=v.createShader(q);v.shaderSource(q,C);v.compileShader(q);return v.getShaderParameter(q,v.COMPILE_STATUS)?q:!1}function c(v,q,C){q=a(v,v.VERTEX_SHADER,q);C=a(v,v.FRAGMENT_SHADER,C);v===D&&l.push(q,C);var M=v.createProgram();v.attachShader(M,q);v.attachShader(M,C);v.linkProgram(M);return M}function d(v,q){q.B=q.B?!0:!1;if(!q.B){void 0===q.za&&(q.za="precision lowp float;attribute vec2 a0;varying vec2 vv0;void main(){gl_Position=vec4(a0,0.,1.),vv0=a0*.5+vec2(.5,.5);}");void 0===
q.Da&&(q.Da=["a0"]);void 0===q.sa&&(q.sa=[2]);if(void 0===q.precision||"highp"===q.precision)q.precision=p;q.id=u++;void 0!==q.ld&&(q.ld.forEach(function(M,R){q.h=q.h.replace(M,q.Ya[R])}),q.ld.splice(0));q.ac=0;q.sa.forEach(function(M){q.ac+=4*M});q.ea=c(v,q.za,"precision "+q.precision+" float;\n"+q.h);q.v={};q.i.forEach(function(M){q.v[M]=v.getUniformLocation(q.ea,M)});q.attributes={};q.ta=[];q.Da.forEach(function(M){var R=v.getAttribLocation(q.ea,M);q.attributes[M]=R;q.ta.push(R)});if(q.j){v.useProgram(q.ea);
f=q;r=q.id;for(var C in q.j)v.uniform1i(q.v[C],q.j[C])}q.da=!0}}function h(v){Pa.af(J);r!==v.id&&(J.N(),r=v.id,f=v,D.useProgram(v.ea),v.ta.forEach(function(q){0!==q&&D.enableVertexAttribArray(q)}))}function t(v,q,C){d(v,q,C);v.useProgram(q.ea);v.enableVertexAttribArray(0);r=-1;return f=q}function n(){return{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",i:["u1"],j:{u1:0}}}var l=[],r=-1,f=null,u=0,y=!1,p="highp",k=["u1"],A=["u0"],x={u1:0},g={u0:0},m={u1:0,u2:1},
K={u3:0},O={s0:n(),s1:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",i:k,j:x,precision:"lowp"},s2:{h:"uniform sampler2D u1,u2;varying vec2 vv0;void main(){vec4 a=texture2D(u2,vv0),b=texture2D(u1,vv0);gl_FragColor=a*b;}",i:["u1","u2"],j:m},s3:{h:"uniform sampler2D u1;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u1,vv0);gl_FragColor=a.r*f;}",i:k,j:x},s4:{h:"uniform sampler2D u1,u2;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u2,vv0),b=texture2D(u1,vv0);gl_FragColor=a.a*b.r*f;}",
i:["u1","u2"],j:m},s5:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vec2(1.-vv0.x,vv0.y));}",i:k,j:x},s6:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vec2(vv0.x,1.-vv0.y));}",i:k,j:x},s7:{h:"uniform sampler2D u0;uniform float u4;varying vec2 vv0;void main(){vec4 a=texture2D(u0,vv0);gl_FragColor=a*u4;}",i:["u0","u4"],j:g},s8:{h:"uniform sampler2D u0;uniform float u4;varying vec2 vv0;const vec4 f=vec4(.25,.25,.25,.25),g=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0);float b=dot(a*u4,f);gl_FragColor=b*g;}",
i:["u0","u4"],j:g},s9:{h:"uniform sampler2D u1;varying vec2 vv0;const vec4 e=vec4(1.,1.,1.,1.);void main(){float a=.25*dot(e,texture2D(u1,vv0));gl_FragColor=a*e;}",i:k,j:x},s10:{h:"uniform sampler2D u1,u5;uniform float u6;const vec4 f=vec4(1.,1.,1.,1.);varying vec2 vv0;void main(){vec4 a=texture2D(u1,vv0),b=texture2D(u5,vv0);gl_FragColor=mix(b,a,u6*f);}",i:["u1","u5","u6"],j:{u1:0,u5:1}},s11:{h:"uniform sampler2D u1;uniform vec2 u7;varying vec2 vv0;void main(){gl_FragColor=.25*(texture2D(u1,vv0+u7)+texture2D(u1,vv0+u7*vec2(1.,-1.))+texture2D(u1,vv0+u7*vec2(-1.,-1.))+texture2D(u1,vv0+u7*vec2(-1.,1.)));}",
i:["u1","u7"],j:x},s12:{h:"uniform sampler2D u1;uniform vec4 u8;varying vec2 vv0;float g(float a,float b){a=floor(a)+.5;return floor(a/exp2(b));}float h(float a,float b){return floor(a*exp2(b)+.5);}float i(float a,float b){return mod(a,h(1.,b));}float e(float c,float a,float b){a=floor(a+.5),b=floor(b+.5);return i(g(c,a),b-a);}vec4 j(float a){if(a==0.)return vec4(0.,0.,0.,0.);float k=128.*step(a,0.);a=abs(a);float c=floor(log2(a)),l=c+127.,b=(a/exp2(c)-1.)*8388608.,d=l/2.,m=fract(d)*2.,n=floor(d),o=e(b,0.,8.),p=e(b,8.,16.),q=m*128.+e(b,16.,23.),r=k+n;return vec4(o,p,q,r)/255.;}void main(){float a=dot(texture2D(u1,vv0),u8);gl_FragColor=j(a);}",
i:["u1","u8"],j:x},s13:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 e=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),b=e/(e+exp(-a));gl_FragColor=b;}",i:A,j:g,B:!0},s14:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(0.,0.,0.,0.);void main(){vec4 a=texture2D(u0,vv0);gl_FragColor=max(f,a);}",i:A,j:g},s15:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0);gl_FragColor=mix(exp(-abs(a))-f,a,step(0.,a));}",i:A,j:g},
s16:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),b=exp(-abs(a))-f;gl_FragColor=mix(.1*b,a,step(0.,a));}",i:A,j:g},s17:{h:"uniform sampler2D u0,u6,u9;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),c=texture2D(u6,vv0),d=texture2D(u9,vv0),b=a/d;gl_FragColor=c*mix(exp(-abs(b))-f,b,step(0.,a));}",i:["u0","u6","u9"],j:{u0:0,u6:1,u9:2},B:!0},s18:{h:"uniform sampler2D u0;const float e=3.141593;varying vec2 vv0;void main(){gl_FragColor=atan(e*texture2D(u0,vv0))/e;}",
i:A,j:g},s19:{h:"uniform sampler2D u0;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=texture2D(u0,vv0),b=log(f+a);gl_FragColor=b;}",i:A,j:g,B:!0},s20:{h:"uniform sampler2D u0,u10;uniform float u11;const vec2 e=vec2(.5,.5);const float f=1e-5;const vec4 g=vec4(1.,1.,1.,1.),i=vec4(0.,0.,0.,0.);varying vec2 vv0;void main(){vec4 a=texture2D(u10,e);float b=u11*u11;vec4 c=max(b*a,f*g);gl_FragColor=texture2D(u0,vv0)/c;}",i:["u0","u10","u11"],j:{u0:0,u10:1},B:!0},s21:{h:"uniform sampler2D u1;uniform vec2 u12;varying vec2 vv0;void main(){float a=u12.x*u12.y;vec2 b=floor(vv0*a)/a,c=fract(vv0*a),d=floor(b*u12.y),f=floor(u12.x*fract(b*u12.y)),g=(f*u12.y+d)/a;gl_FragColor=texture2D(u1,g+c/a);}",
i:["u1","u12"],j:x},s22:{h:"uniform sampler2D u13,u14,u15;varying vec2 vv0;void main(){vec4 a=texture2D(u15,vv0);vec2 b=a.rg,c=a.ba;vec4 d=texture2D(u13,b),f=texture2D(u14,c);gl_FragColor=d*f;}",i:["u13","u14","u15"],j:{u14:0,u13:1,u15:2},B:!0},s23:{h:"uniform float u16;uniform sampler2D u13,u14;varying vec2 vv0;void main(){vec2 a=fract(vv0*u16);vec4 b=texture2D(u13,vv0),c=texture2D(u14,a);gl_FragColor=b*c;}",i:["u14","u13","u16"],j:{u14:0,u13:1}},s24:{h:"uniform float u16;uniform sampler2D u13,u14,u17,u18,u19,u20;varying vec2 vv0;const vec4 e=vec4(1.,1.,1.,1.),g=vec4(1e-3,1e-3,1e-3,1e-3);void main(){vec2 h=vv0*u16,l=floor(h),c=h-l;vec4 m=texture2D(u13,vv0),d=texture2D(u14,c),a=texture2D(u20,vv0);a=a*255.;vec4 n=texture2D(u17,c),o=texture2D(u18,c),p=texture2D(u19,c),i=step(-g,-a),b=e-i,j=b*step(-e-g,-a);b*=e-j;vec4 k=b*step(-2.*e-g,-a);b*=e-k;vec4 q=b;d=i*d+j*n+k*o+q*p,gl_FragColor=m*d;}",
i:"u13 u14 u16 u20 u17 u18 u19".split(" "),j:{u14:0,u13:1,u20:3,u17:4,u18:5,u19:6},B:!0},s25:{h:"uniform sampler2D u13,u14,u21;uniform float u16,u22,u23,u24;varying vec2 vv0;const vec2 j=vec2(1.,1.);void main(){vec2 a=floor(u22*vv0),b=u22*vv0-a;float c=u16/u22;vec2 d=floor(b*c),f=b*c-d,g=(a+f)/u22;float k=u22*u24/u16;vec2 l=k*d,h=(l+f*u23)/u24,i=step(h,j);vec4 m=texture2D(u13,g),n=texture2D(u14,h),o=m*n*i.x*i.y,p=texture2D(u21,g);gl_FragColor=o*u23*u23+p;}",i:"u13 u14 u16 u22 u23 u24 u21".split(" "),
j:{u14:0,u13:1,u21:2}},s26:{h:"uniform sampler2D u13,u14;varying vec2 vv0;void main(){vec4 a=texture2D(u13,vv0),b=texture2D(u14,vv0);gl_FragColor=a*b;}",i:["u13","u14"],j:{u14:0,u13:1},B:!0},s27:{h:"uniform sampler2D u1,u21;uniform float u25;varying vec2 vv0;void main(){gl_FragColor=texture2D(u21,vv0)+u25*texture2D(u1,vv0);}",i:["u1","u21","u25"],j:{u1:0,u21:1}},s28:{h:"varying vec2 vv0;uniform sampler2D u1;const vec4 f=vec4(1.,1.,1.,1.),g=vec4(.299,.587,.114,0.);void main(){vec4 a=texture2D(u1,vv0);gl_FragColor=dot(a,g)*f;}",
i:k,j:x,precision:"lowp"},s29:{h:"varying vec2 vv0;uniform sampler2D u1;uniform float u26;const vec3 f=vec3(.299,.587,.114);void main(){vec3 a=texture2D(u1,vv0).rgb,b=texture2D(u1,vv0+vec2(0.,u26)).rgb,c=texture2D(u1,vv0+vec2(u26,u26)).rgb,d=texture2D(u1,vv0+vec2(u26,0.)).rgb;gl_FragColor=vec4(dot(a,f),dot(b,f),dot(c,f),dot(d,f));}",i:["u1","u26"],j:x,precision:"lowp"},s30:{h:"varying vec2 vv0;uniform sampler2D u1;uniform float u26;const vec3 f=vec3(.299,.587,.114);void main(){vec3 a=texture2D(u1,vv0).rgb,b=texture2D(u1,vv0+vec2(0.,u26)).rgb,c=texture2D(u1,vv0+vec2(u26,u26)).rgb,d=texture2D(u1,vv0+vec2(u26,0.)).rgb;gl_FragColor=vec4(a.r,b.g,c.b,dot(d,f));}",
i:["u1","u26"],j:x,precision:"lowp"},s31:{h:"varying vec2 vv0;uniform sampler2D u1,u2;uniform float u27;const vec4 f=vec4(1.,1.,1.,1.);void main(){vec4 a=vec4(0.);a-=texture2D(u1,vec2(vv0.x-u27,vv0.y-u27))*1.,a-=texture2D(u1,vec2(vv0.x-u27,vv0.y))*2.,a-=texture2D(u1,vec2(vv0.x-u27,vv0.y+u27))*1.,a+=texture2D(u1,vec2(vv0.x+u27,vv0.y-u27))*1.,a+=texture2D(u1,vec2(vv0.x+u27,vv0.y))*2.,a+=texture2D(u1,vec2(vv0.x+u27,vv0.y+u27))*1.;vec4 b=vec4(0.);b-=texture2D(u1,vec2(vv0.x-u27,vv0.y-u27))*1.,b-=texture2D(u1,vec2(vv0.x,vv0.y-u27))*2.,b-=texture2D(u1,vec2(vv0.x+u27,vv0.y-u27))*1.,b+=texture2D(u1,vec2(vv0.x-u27,vv0.y+u27))*1.,b+=texture2D(u1,vec2(vv0.x,vv0.y+u27))*2.,b+=texture2D(u1,vec2(vv0.x+u27,vv0.y+u27))*1.;vec3 c=sqrt(a.rgb*a.rgb+b.rgb*b.rgb);vec4 e=vec4(c,texture2D(u1,vv0).a),g=texture2D(u2,vv0);gl_FragColor=g.a*e.r*f;}",
i:["u1","u2","u27"],j:m,B:!0},s32:{h:"varying vec2 vv0;uniform sampler2D u1,u2;uniform float u27;const vec4 j=vec4(1.,1.,1.,1.);const vec2 k=vec2(1.,1.);void main(){float h=0.;vec2 l=k*u27,a,b;float c,d,i=0.;for(float e=-4.;e<=4.;e+=1.)for(float f=-4.;f<=4.;f+=1.)a=vec2(e,f),c=length(a)/2.,d=exp(-c*c),b=vv0+l*a,h+=d*texture2D(u1,b).r,i+=d;vec4 m=texture2D(u2,vv0);gl_FragColor=m.a*(texture2D(u1,b).r-h/i)*j;}",i:["u1","u2","u27"],j:m,B:!0},s33:{h:"uniform sampler2D u3;uniform vec2 u7;varying vec2 vv0;vec4 e(vec4 a,vec4 b){vec4 c=step(a,b);return mix(a,b,c);}const vec2 g=vec2(.5,.5),h=vec2(1.,0.),i=vec2(0.,1.);void main(){vec2 a=vv0-u7*g;vec4 b=texture2D(u3,a),c=texture2D(u3,a+u7*h),d=texture2D(u3,a+u7*i),j=texture2D(u3,a+u7),k=e(b,c),l=e(d,j);gl_FragColor=e(k,l);}",
i:["u3","u7"],j:K},s34:{h:"uniform sampler2D u3;uniform vec2 u7;varying vec2 vv0;const vec2 k=vec2(1.,0.),l=vec2(0.,1.),m=vec2(2.,0.),n=vec2(0.,2.);vec4 e(vec4 a,vec4 b){vec4 c=step(a,b);return mix(a,b,c);}vec4 f(vec2 a){vec4 b=texture2D(u3,a),c=texture2D(u3,a+u7*k),d=texture2D(u3,a+u7*l),g=texture2D(u3,a+u7),h=e(b,c),i=e(d,g);return e(h,i);}void main(){vec2 a=vv0+u7*vec2(-.55,-1.05);vec4 b=f(a),c=f(a+u7*m),d=f(a+u7*2.),g=f(a+u7*n),h=e(b,c),i=e(d,g);gl_FragColor=e(h,i);}",i:["u3","u7"],j:K,B:!0},
s35:{h:"uniform sampler2D u1;varying vec2 vv0;void main(){vec4 a=texture2D(u1,vv0);gl_FragColor=a*a;}",i:["u1"],j:x,precision:"lowp",B:!0},s36:{h:"uniform sampler2D u1;uniform vec2 u7;varying vec2 vv0;const float e=15444.;void main(){vec4 a=1001./e*texture2D(u1,vv0-3.*u7)+2002./e*texture2D(u1,vv0-2.*u7)+3003./e*texture2D(u1,vv0-u7)+3432./e*texture2D(u1,vv0)+3003./e*texture2D(u1,vv0+u7)+2002./e*texture2D(u1,vv0+2.*u7)+1001./e*texture2D(u1,vv0+3.*u7);gl_FragColor=a;}",i:["u7","u1"],j:x,precision:"lowp",
B:!0},s37:{h:"uniform sampler2D u1,u10,u28;varying vec2 vv0;const vec4 f=vec4(1.,1.,1.,1.);const float g=.1;void main(){vec4 a=texture2D(u10,vv0),b=texture2D(u28,vv0),c=texture2D(u1,vv0),d=max(f*g,b-a*a),h=sqrt(d);gl_FragColor=(c-a)/h;}",i:["u1","u10","u28"],j:{u1:0,u10:1,u28:2},B:!0}},E={s38:{h:"uniform float u16,u29;uniform sampler2D u13,u14,u21;varying vec2 vv0;const vec2 ZERO2=vec2(0.,0.),ONE2=vec2(1.,1.),HALF2=vec2(.5,.5),EPS2=vec2(1e-5,1e-5);void main(){vec4 sum=texture2D(u21,vv0);float toSparsity=1.1111;vec2 uvFrom,uvWeight,xyPatch=ZERO2,eps2=EPS2/u16,xyTo=floor(vv0*u16+eps2);float weightSize=toSparsity*u16;vec2 halfFromSparsity=ONE2*(toSparsity-1.)/2.;for(float patch_x=0.;patch_x<1.1111;patch_x+=1.){xyPatch.x=patch_x;for(float patch_y=0.;patch_y<1.1111;patch_y+=1.)xyPatch.y=patch_y,uvFrom=(xyTo+HALF2+u29*(xyPatch-halfFromSparsity))/u16,uvFrom+=step(uvFrom,-eps2),uvFrom-=step(ONE2-eps2,uvFrom),uvWeight=(xyTo*toSparsity+xyPatch+HALF2)/weightSize,sum+=texture2D(u13,uvWeight)*texture2D(u14,uvFrom);}gl_FragColor=sum,gl_FragColor*=2.2222;}",
i:["u16","u13","u14","u21","u29"],Ya:["1.1111","gl_FragColor\\*=2.2222;"]},s39:{h:"uniform float u16,u29,u24;uniform sampler2D u13,u14,u21;varying vec2 vv0;const vec2 ZERO2=vec2(0.,0.),ONE2=vec2(1.,1.),HALF2=vec2(.5,.5),EPS2=vec2(1e-4,1e-4);void main(){vec4 sum=texture2D(u21,vv0);float fromSparsity=1.1111,shrinkFactor=3.3333;vec2 uvFrom,uvWeight,xyFrom,xyPatchTo,xyPatch=ZERO2,xyShrink=ZERO2,eps2=EPS2/u24,xyTo=floor(vv0*u16+eps2);float weightSize=fromSparsity*u24;vec2 halfFromSparsity=ONE2*(fromSparsity-1.)/2.;float toSparsity=weightSize/u16;vec2 xyFrom0=xyTo*shrinkFactor;for(float patch_x=0.;patch_x<1.1111;patch_x+=1.){xyPatch.x=patch_x;for(float patch_y=0.;patch_y<1.1111;patch_y+=1.){xyPatch.y=patch_y;for(float shrink_x=0.;shrink_x<3.3333;shrink_x+=1.){xyShrink.x=shrink_x;for(float shrink_y=0.;shrink_y<3.3333;shrink_y+=1.)xyShrink.y=shrink_y,xyFrom=xyFrom0+xyShrink+shrinkFactor*u29*(xyPatch-halfFromSparsity),uvFrom=(xyFrom+HALF2)/u24,uvFrom+=step(uvFrom,-eps2),uvFrom-=step(ONE2-eps2,uvFrom),xyPatchTo=xyPatch*shrinkFactor+xyShrink,uvWeight=(xyTo*toSparsity+xyPatchTo+HALF2)/weightSize,sum+=texture2D(u13,uvWeight)*texture2D(u14,uvFrom);}}}gl_FragColor=sum,gl_FragColor*=2.2222;}",
i:"u16 u24 u13 u14 u21 u29".split(" "),Ya:["1.1111","gl_FragColor\\*=2.2222;","3.3333"]}},S=null,I=null,J={Sa:function(){return y},s:function(){if(!y){S=Ha(O,2);I=Ha(E,2);p="highp";for(var v in S)d(D,S[v],v);G.set("s0");D.enableVertexAttribArray(0);y=!0}},ec:function(v){v.forEach(function(q){J.dc(q)})},dc:function(v){S[v.id]=v;d(D,v,v.id)},Ec:function(v,q,C){q||(q=v);S[q]=Object.create(I[v]);S[q].we=!0;I[v].Ya&&I[v].Ya.forEach(function(M,R){S[q].h=S[q].h.replace(new RegExp(M,"g"),C[R])});d(D,S[q],
q)},set:function(v){var q=S[v];q.B&&(q.B=!1,d(D,q,v));h(q)},xa:function(v){return t(v,n(),"s40")},Sb:function(v){return t(v,{h:"void main(){gl_FragColor=vec4(.5,.5,.5,.5);}",i:[],precision:"highp"},"s41")},Yd:function(v){return"undefined"===typeof S[v]?!1:S[v].da},N:function(){-1!==r&&(r=-1,f.ta.forEach(function(v){0!==v&&D.disableVertexAttribArray(v)}))},Ub:function(){var v=0;f.ta.forEach(function(q,C){C=f.sa[C];D.vertexAttribPointer(q,C,D.FLOAT,!1,f.ac,v);v+=4*C})},Df:function(){D.enableVertexAttribArray(0)},
Za:function(){J.$a(D)},$a:function(v){v.vertexAttribPointer(f.ta[0],2,v.FLOAT,!1,8,0)},hg:function(v,q){D.uniform1i(f.v[v],q)},L:function(v,q){D.uniform1f(f.v[v],q)},fa:function(v,q,C){D.uniform2f(f.v[v],q,C)},ig:function(v,q){D.uniform2fv(f.v[v],q)},od:function(v,q){D.uniform3fv(f.v[v],q)},jg:function(v,q,C,M){D.uniform3f(f.v[v],q,C,M)},kg:function(v,q,C,M,R){D.uniform4f(f.v[v],q,C,M,R)},Tb:function(v,q){D.uniform4fv(f.v[v],q)},lg:function(v,q){D.uniformMatrix2fv(f.v[v],!1,q)},mg:function(v,q){D.uniformMatrix3fv(f.v[v],
!1,q)},ng:function(v,q){D.uniformMatrix4fv(f.v[v],!1,q)},I:function(v,q){J.set(v);q.forEach(function(C){switch(C.type){case "4f":D.uniform4fv(f.v[C.name],C.value);break;case "3f":D.uniform3fv(f.v[C.name],C.value);break;case "2f":D.uniform2fv(f.v[C.name],C.value);break;case "1f":D.uniform1f(f.v[C.name],C.value);break;case "1i":D.uniform1i(f.v[C.name],C.value);break;case "mat2":D.uniformMatrix2fv(f.v[C.name],!1,C.value);break;case "mat3":D.uniformMatrix3fv(f.v[C.name],!1,C.value);break;case "mat4":D.uniformMatrix4fv(f.v[C.name],
!1,C.value)}})},Nf:function(){return"lowp"},m:function(){D.disableVertexAttribArray(0);J.N();for(var v in S){var q=S[v];q.da&&(q.da=!1,D.deleteProgram(q.ea));q.we&&delete S[v]}l.forEach(function(C){D.deleteShader(C)});l.splice(0);u=0;y=!1;f=null;r=-1}};return J}(),D=null,Ua=function(){function a(p){console.log("ERROR in ContextFF: ",p);return!1}function c(p){function k(){Qa.m();Ra.reset();x.getExtension("WEBGL_lose_context").loseContext()}if(navigator.userAgent&&-1!==navigator.userAgent.indexOf("forceWebGL1"))return!1;
var A=document.createElement("canvas");A.setAttribute("width",5);A.setAttribute("height",5);var x=null;try{x=A.getContext("webgl2",p)}catch(g){return!1}if(!x)return!1;d(x);Ra.nc(x);p=Ra.pb(x);if(!p.V&&!p.W)return k(),!1;p=Qa.kc(x,p);k();return p?!0:!1}function d(p){p.clearColor(0,0,0,0);p.disable(p.DEPTH_TEST);p.disable(p.BLEND);p.disable(p.DITHER);p.disable(p.STENCIL_TEST);p.disable(p.CULL_FACE);p.GENERATE_MIPMAP_HINT&&p.hint(p.GENERATE_MIPMAP_HINT,p.FASTEST);p.disable(p.SAMPLE_ALPHA_TO_COVERAGE);
p.disable(p.SAMPLE_COVERAGE);p.depthFunc(p.LEQUAL);p.clearDepth(1)}var h=null,t=null,n=null,l=null,r=!0,f=null,u=null,y={A:function(){return h.width},J:function(){return h.height},La:function(){return h},Ff:function(){return D},Y:function(){return r},flush:function(){D.flush()},be:function(){f||(f=new Uint8Array(h.width*h.height*4));D.readPixels(0,0,h.width,h.height,D.RGBA,D.UNSIGNED_BYTE,f);return f},Hf:function(){return h.toDataURL("image/jpeg")},If:function(){Sa.M();t||(t=document.createElement("canvas"),
n=t.getContext("2d"));t.width=h.width;t.height=h.height;for(var p=y.be(),k=n.createImageData(t.width,t.height),A=t.width,x=t.height,g=k.data,m=0;m<x;++m)for(var K=x-m-1,O=0;O<A;++O){var E=4*(m*A+O),S=4*(K*A+O);g[E]=p[S];g[E+1]=p[S+1];g[E+2]=p[S+2];g[E+3]=p[S+3]}n.putImageData(k,0,0);return t.toDataURL("image/png")},Gf:function(p){!t&&p&&(t=document.createElement("canvas"),n=t.getContext("2d"));var k=p?t:document.createElement("canvas");k.width=h.width;k.height=h.height;(p?n:k.getContext("2d")).drawImage(h,
0,0);return k},s:function(p){p.Pd&&!p.ob?h=document.getElementById(p.Pd):p.ob&&(h=p.ob);h||(h=document.createElement("canvas"));h.width=p&&void 0!==p.width?p.width:512;h.height=p&&void 0!==p.height?p.height:512;"undefined"===typeof p&&(p={});void 0===p.premultipliedAlpha&&(p.premultipliedAlpha=!1);void 0===p.Bb&&(p.Bb=!0);void 0===p.antialias&&(p.antialias=!1);if(D)r=D instanceof WebGL2RenderingContext;else{r=!0;var k={antialias:p.antialias,alpha:!0,preserveDrawingBuffer:!0,premultipliedAlpha:p.premultipliedAlpha,
stencil:!1,depth:p.Bb};navigator&&navigator.userAgent&&-1!==navigator.userAgent.indexOf("noAntialiasing")&&(k.antialias=!1);var A=c(k);!A&&k.antialias&&(k.antialias=!1,A=c(k));A&&(D=h.getContext("webgl2",k));D?r=!0:((D=h.getContext("webgl",k))||(D=h.getContext("experimental-webgl",k)),r=!1)}if(!D)return a("WebGL1 and 2 are not enabled");(l=D.getExtension("WEBGL_lose_context"))&&p.Wc&&(u=p.Wc,h.addEventListener("webglcontextlost",u,!1));if(!Ra.s())return a("Not enough GL capabilities");d(D);G.s();
N.s();return Qa.kc(D,Ra.$d())?!0:a("Cannot filter float textures")},m:function(){D&&(Ra.m(),Qa.m());l&&u&&(h.removeEventListener("webglcontextlost",u,!1),l=u=null);D=f=n=t=h=null}};return y}(),Pa=function(){function a(){null===c&&("undefined"!==typeof G?c=G:"undefined"!==typeof JEShaders&&(c=JEShaders))}var c=null;a();return{af:function(d){c!==d&&(c&&c.N(),c=d)},Sa:function(){return c.Sa()},Za:function(){return c.Za()},$a:function(d){return c.$a(d)},Ub:function(){return c.Ub()},N:function(){return c.N()},
set:function(d){return c.set(d)},xa:function(d){a();return c.xa(d)},Sb:function(d){a();return c.Sb(d)},m:function(){return c.m()}}}(),Q=function(){function a(e){D.bindTexture(D.TEXTURE_2D,e)}function c(e){q[0]=e;e=C[0];var L=e>>16&32768,H=e>>12&2047,P=e>>23&255;return 103>P?L:142<P?L|31744|((255==P?0:1)&&e&8388607):113>P?(H|=2048,L|(H>>114-P)+(H>>113-P&1)):L=(L|P-112<<10|H>>1)+(H&1)}function d(e){var L=new Uint16Array(e.length);e.forEach(function(H,P){L[P]=c(H)});return L}function h(){if(null!==M.yb)return M.yb;
var e=n(d([.5,.5,.5,.5]));return null===e?!0:M.yb=e}function t(){if(null!==M.zb)return M.zb;var e=n(new Uint8Array([127,127,127,127]));return null===e?!0:M.zb=e}function n(e){if(!Pa.Sa()||!g)return null;var L=null,H=Math.sqrt(e.length/4);try{var P=D.getError();if("FUCKING_BIG_ERROR"===P)return!1;L=R.instance({isFloat:!1,G:!0,array:e,width:H});P=D.getError();if(P!==D.NO_ERROR)return!1}catch(W){return!1}Sa.M();D.viewport(0,0,H,H);D.clearColor(0,0,0,0);D.clear(D.COLOR_BUFFER_BIT);Pa.set("s0");L.ic(0);
N.l(!0,!0);e=4*H*H;P=new Uint8Array(e);D.readPixels(0,0,H,H,D.RGBA,D.UNSIGNED_BYTE,P);H=!0;for(var aa=0;aa<e;++aa)H=H&&3>Math.abs(P[aa]-127);L.remove();Sa.U();return H}var l=0,r=null,f=0,u=null,y=null,p=null,k=null,A=null,x=null,g=!1,m=[],K={isFloat:!1,isPot:!0,isLinear:!1,isMipmap:!1,isAnisotropicFiltering:!1,isMirrorX:!1,isMirrorY:!1,isSrgb:!1,isKeepArray:!1,isFlipY:null,width:0,height:0,url:null,array:null,data:null,C:null,Bc:null,ve:!1,G:!1,ca:null,Ua:4,Hb:0},O=!1,E=null,S=null,I=[[1,0,0,0],[0,
1,0,0],[0,0,1,0],[0,0,0,1]],J=!1,v=!1,q=new Float32Array(1),C=new Int32Array(q.buffer),M={yb:null,zb:null},R={s:function(){g||(A=[D.RGBA,null,D.RGBA,D.RGBA],x=[D.RGBA,null,D.RGBA,D.RGBA],r=[D.TEXTURE0,D.TEXTURE1,D.TEXTURE2,D.TEXTURE3,D.TEXTURE4,D.TEXTURE5,D.TEXTURE6,D.TEXTURE7],J="undefined"!==typeof JEContext,v="undefined"!==typeof Ra,J&&JEContext.ag()&&r.push(D.TEXTURE8,D.TEXTURE9),u=[-1,-1,-1,-1,-1,-1,-1,-1],k=[D.UNSIGNED_BYTE,D.FLOAT,D.FLOAT],g=!0)},pe:function(){if(!y){for(var e=new Float32Array(16384),
L=0;16384>L;++L)e[L]=2*Math.random()-1;y={random:R.instance({isFloat:!0,isPot:!0,array:e,width:64}),td:R.instance({isFloat:!1,isPot:!0,width:1,array:new Uint8Array([0,0,0,0])})}}R.mf()},Tf:function(){return y.td},mf:function(){k[1]=Ra.tb(D)},Ze:function(){x=A=[D.RGBA,D.RGBA,D.RGBA,D.RGBA]},fd:function(e){G.set("s1");Sa.M();var L=e.A(),H=e.J();D.viewport(0,0,L,H);e.g(0);N.l(!1,!1)},Pe:function(e,L){R.fd(e);D.readPixels(0,0,e.A(),e.J(),D.RGBA,D.UNSIGNED_BYTE,L)},Qe:function(e,L){R.fd(e);return Ra.Rb(0,
0,e.A(),e.J(),L)},uc:function(e,L,H,P,aa,W,la){e.activeTexture(e.TEXTURE0);var w=e.createTexture();e.bindTexture(e.TEXTURE_2D,w);aa=aa instanceof Float32Array?aa:new Float32Array(aa);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_S,e.CLAMP_TO_EDGE);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_T,e.CLAMP_TO_EDGE);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MAG_FILTER,e.NEAREST);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MIN_FILTER,e.NEAREST);e.pixelStorei(e.UNPACK_FLIP_Y_WEBGL,W);e.texImage2D(e.TEXTURE_2D,0,e.RGBA,
H,P,0,e.RGBA,e.FLOAT,aa);e.bindTexture(e.TEXTURE_2D,null);e.pixelStorei(e.UNPACK_FLIP_Y_WEBGL,!1);la&&(Sa.U(),G.xa(e));e.viewport(0,0,H,P);e.framebufferTexture2D(e.FRAMEBUFFER,e.COLOR_ATTACHMENT0,e.TEXTURE_2D,L,0);e.bindTexture(e.TEXTURE_2D,w);la?N.l(!0,!0):N.Ja(e);e.deleteTexture(w);g&&(u[0]=-1,p=null,l=0)},jb:function(e){e!==l&&(D.activeTexture(r[e]),l=e)},instance:function(e){function L(){T=void 0!==w.C.videoWidth?w.C.videoWidth:w.C.width;X=void 0!==w.C.videoHeight?w.C.videoHeight:w.C.height}function H(B){var U=
D.getError();if("FUCKING_BIG_ERROR"===U)return!1;D.texImage2D(D.TEXTURE_2D,0,ia,fa,ha,B);U=D.getError();U!==D.NO_ERROR&&fa!==D.RGBA&&(fa=D.RGBA,D.texImage2D(D.TEXTURE_2D,0,ia,fa,ha,B));return!0}function P(){if(!Xa){a(ma);sa&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,sa);w.isPot?(D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_S,w.isMirrorX?D.MIRRORED_REPEAT:D.REPEAT),D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_T,w.isMirrorY?D.MIRRORED_REPEAT:D.REPEAT)):(D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_S,D.CLAMP_TO_EDGE),
D.texParameteri(D.TEXTURE_2D,D.TEXTURE_WRAP_T,D.CLAMP_TO_EDGE));w.isAnisotropicFiltering&&"undefined"!==typeof JESETTINGS&&D.texParameterf(D.TEXTURE_2D,JEContext.Kf().TEXTURE_MAX_ANISOTROPY_EXT,JESETTINGS.sf);D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MAG_FILTER,w.isLinear?D.LINEAR:D.NEAREST);w.isLinear?D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MIN_FILTER,w.isMipmap&&!ya?D.NEAREST_MIPMAP_LINEAR:D.LINEAR):D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MIN_FILTER,w.isMipmap&&!ya?D.NEAREST_MIPMAP_NEAREST:D.NEAREST);
fa=A[w.Ua-1];ia=x[w.Ua-1];ha=k[F];if(Ra.Y()){var B=Ra.ce();fa===D.RGBA&&ha===D.FLOAT?w.isMipmap||w.isLinear?ia=Qa.ee(D):Ra.lc()?B&&(ia=B):ia=D.RGBA16F||D.RGBA:fa===D.RGB&&ha===D.FLOAT&&B&&(ia=B,fa=D.RGBA)}if(w.G&&!w.isFloat||w.isFloat&&w.isMipmap&&Qa.ze())ia=Ra.de(),ha=Ra.tb(D);w.Hb&&(Ka=w.Hb);w.isSrgb&&4===w.Ua&&(fa=JEContext.Rf());if(w.C)H(w.C);else if(w.url)H(xa);else if(na){B=na;try{"FUCKING_BIG_ERROR"!==D.getError()&&(D.texImage2D(D.TEXTURE_2D,0,ia,T,X,0,fa,ha,B),D.getError()!==D.NO_ERROR&&(D.texImage2D(D.TEXTURE_2D,
0,ia,T,X,0,fa,ha,null),D.getError()!==D.NO_ERROR&&D.texImage2D(D.TEXTURE_2D,0,D.RGBA,T,X,0,D.RGBA,D.UNSIGNED_BYTE,null)))}catch(Ib){D.texImage2D(D.TEXTURE_2D,0,ia,T,X,0,fa,ha,null)}w.isKeepArray||(na=null)}else B=D.getError(),"FUCKING_BIG_ERROR"!==B&&(D.texImage2D(D.TEXTURE_2D,0,ia,T,X,0,fa,ha,null),B=D.getError(),B!==D.NO_ERROR&&(fa=D.RGBA,w.G&&ha!==D.FLOAT&&(ha=D.FLOAT,D.texImage2D(D.TEXTURE_2D,0,ia,T,X,0,fa,ha,null))));if(w.isMipmap)if(!ya&&ea)ea.sb(),La=!0;else if(ya){B=Math.log2(Math.min(T,X));
Ba=Array(1+B);Ba[0]=ma;for(var U=1;U<=B;++U){var ja=Math.pow(2,U),Z=T/ja;ja=X/ja;var za=D.createTexture();a(za);D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MIN_FILTER,D.NEAREST);D.texParameteri(D.TEXTURE_2D,D.TEXTURE_MAG_FILTER,D.NEAREST);D.texImage2D(D.TEXTURE_2D,0,ia,Z,ja,0,fa,ha,null);a(null);Ba[U]=za}La=!0}a(null);u[l]=-1;sa&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1);Ea=!0;w.ca&&ea&&(w.ca(ea),w.ca=null)}}function aa(){for(var B=T*X,U=2*B,ja=3*B,Z=0;Z<B;++Z)pa[0][Z]=Fa[Z],pa[1][Z]=Fa[Z+B],pa[2][Z]=Fa[Z+
U],pa[3][Z]=Fa[Z+ja]}function W(){var B=T*X*4;va=[new Uint8Array(B),new Uint8Array(B),new Uint8Array(B),new Uint8Array(B)];pa=[new Float32Array(va[0].buffer),new Float32Array(va[1].buffer),new Float32Array(va[2].buffer),new Float32Array(va[3].buffer)];Ma=new Uint8Array(4*B);Fa=new Float32Array(Ma.buffer);Ga=!0}function la(){wa.lb=new Uint8Array(T*X*4);wa.wc=new Float32Array(wa.buffer);wa.Db=!0}var w=Object.assign({},K,e),z=f++;null===w.isFlipY&&(w.isFlipY=w.url||w.array?!0:!1);w.data&&(w.array="string"===
typeof w.data?Oa(w.data):w.isFloat?new Float32Array(w.data):new Uint8Array(w.data),w.isFlipY=!1);var F=0,ca=w.C?!0:!1,Y=null,qa=null,Ya=!1,Ta=null;w.G=w.G||w.isFloat;w.G&&(F=1);!w.ve&&w.isFloat&&v&&!Ra.lc()&&(w.isFloat=!1);w.isFloat&&(F=2);w.isAnisotropicFiltering&&J&&!JEContext.Wf()&&(w.isAnisotropicFiltering=!1);var ma=w.Bc||D.createTexture(),xa=null,na=!1,T=0,X=0,Ea=!1,Xa=!1,Ga=!1,pa=null,va=null,Ma=null,Fa=null,ia=null,fa=null,ha=null,sa=w.isFlipY,rb=(e=w.G&&w.isMipmap)&&Qa.Gd(),ya=e&&rb?!0:!1,
Ba=null,Ka=-1,La=!1,wa={Db:!1,lb:null,wc:null};w.width&&(T=w.width,X=w.height?w.height:T);var ea={get:function(){return ma},A:function(){return T},J:function(){return X},Uf:function(){return w.url},Xf:function(){return w.isFloat},Zf:function(){return w.G},$f:function(){return w.isLinear},sb:function(){D.generateMipmap(D.TEXTURE_2D)},Ed:function(B,U){ya?(B||(B=ea.zc()),R.jb(U),a(Ba[B]),u[U]=-1):ea.g(U)},zc:function(){-1===Ka&&(Ka=Math.log(T)/Math.log(2));return Ka},Zd:function(B){if(ya){B||(B=ea.zc());
G.set("s11");R.jb(0);for(var U=T,ja=X,Z=1;Z<=B;++Z)U/=2,ja/=2,G.fa("u7",.25/U,.25/ja),D.viewport(0,0,U,ja),a(Ba[Z-1]),D.framebufferTexture2D(Sa.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,Ba[Z],0),N.l(!1,1===Z);u[0]=-1}else ea.sb()},gg:function(B){(ca=!(Array.isArray(B)||B.constructor===Float32Array||B.constructor===Uint8Array))?(na=null,w.C=B,L()):na=B},g:function(B){if(!Ea)return!1;R.jb(B);if(u[B]===z)return!1;a(ma);u[B]=z;return!0},ic:function(B){D.activeTexture(r[B]);l=B;a(ma);u[B]=z},u:function(){p=
ea;D.framebufferTexture2D(Sa.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,ma,0)},P:function(){p=ea;D.viewport(0,0,T,X);D.framebufferTexture2D(Sa.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,ma,0)},$b:R.$b,resize:function(B,U){T=B;X=U;P()},clone:function(B){B=R.instance({width:T,height:X,G:w.G,isFloat:w.isFloat,isLinear:w.isLinear,isMirrorY:w.isMirrorY,isFlipY:B?!sa:sa,isPot:w.isPot});Pa.set("s0");Sa.U();B.u();D.viewport(0,0,T,X);ea.g(0);N.l(!0,!0);return B},bf:function(){D.viewport(0,0,T,X)},remove:function(){D.deleteTexture(ma);
Xa=!0;m.splice(m.indexOf(ea),1);ea=null},refresh:function(){ea.ic(0);sa&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!0);ca?D.texImage2D(D.TEXTURE_2D,0,ia,fa,ha,w.C):D.texImage2D(D.TEXTURE_2D,0,ia,T,X,0,fa,ha,na);sa&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1)},Qb:function(){Ga||W();D.readPixels(0,0,T,4*X,D.RGBA,D.UNSIGNED_BYTE,Ma);aa();return pa},Me:function(){Ga||W();return Ra.Rb(0,0,T,4*X,Ma).then(function(){aa();return pa})},Oe:function(){wa.Db||la();D.readPixels(0,0,T,X,D.RGBA,D.UNSIGNED_BYTE,wa.lb);return wa.wc},
Ne:function(){wa.Db||la();return Ra.Rb(0,0,T,X,wa.lb)},qb:function(B){Sa.M();G.set("s12");ea.g(0);if(B)D.viewport(0,0,T,X),G.Tb("u8",.25,.25,.25,.25),N.l(!1,!0);else for(B=0;4>B;++B)D.viewport(0,X*B,T,X),G.Tb("u8",I[B]),N.l(!1,0===B)},qg:function(B){var U=ha===k[0]&&!t();a(ma);sa&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!0);U?(Ya||(Y=document.createElement("canvas"),Y.width=T,Y.height=X,qa=Y.getContext("2d"),Ta=qa.createImageData(T,X),Ya=!0),Ta.data.set(B),qa.putImageData(Ta,0,0),D.texImage2D(D.TEXTURE_2D,
0,ia,fa,ha,Y)):D.texImage2D(D.TEXTURE_2D,0,ia,T,X,0,fa,ha,B);u[l]=z;sa&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1)},rg:function(B,U){a(ma);U&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!0);D.texImage2D(D.TEXTURE_2D,0,ia,fa,ha,B);u[l]=z;U&&D.pixelStorei(D.UNPACK_FLIP_Y_WEBGL,!1)},eg:function(B,U){var ja=T*X,Z=4*ja;B=w.G?B?"RGBE":"JSON":"RGBA";U&&(B=U);U=Ra.Y()&&!1;var za=null;switch(B){case "RGBE":za="s42";break;case "JSON":za=U?"s0":"s12";break;case "RGBA":case "RGBAARRAY":za="s6"}Ga||("RGBA"===B||"RGBE"===
B||"RGBAARRAY"===B?(va=new Uint8Array(Z),Ga=!0):"JSON"!==B||U||W());Sa.M();G.set(za);ea.g(0);Z=null;if("RGBA"===B||"RGBE"===B||"RGBAARRAY"===B){D.viewport(0,0,T,X);N.l(!0,!0);D.readPixels(0,0,T,X,D.RGBA,D.UNSIGNED_BYTE,va);if("RGBAARRAY"===B)return{data:va};O||(E=document.createElement("canvas"),S=E.getContext("2d"),O=!0);E.width=T;E.height=X;ja=S.createImageData(T,X);ja.data.set(va);S.putImageData(ja,0,0);Z=E.toDataURL("image/png")}else if("JSON"===B)if(U)Z=new Float32Array(ja),D.viewport(0,0,T,
X),N.l(!0,!0),D.readPixels(0,0,T,X,D.RGBA,D.FLOAT,Z);else{for(Z=0;4>Z;++Z)D.viewport(0,X*Z,T,X),G.Tb("u8",I[Z]),N.l(!Z,!Z);ea.Qb();Z=Array(ja);for(U=0;U<ja;++U)Z[4*U]=pa[0][U],Z[4*U+1]=pa[1][U],Z[4*U+2]=pa[2][U],Z[4*U+3]=pa[3][U]}return{format:B,data:Z,width:T,height:X,isMirrorY:w.isMirrorY,isFlipY:"RGBA"===B?w.isFlipY:!w.isFlipY}}};w.isMipmap&&!ya&&Ea&&!La&&(ea.sb(),La=!0);if(w.url)a(ma),D.texImage2D(D.TEXTURE_2D,0,D.RGBA,1,1,0,D.RGBA,D.UNSIGNED_BYTE,null),xa=new Image,xa.Af="Anonymous",xa.crossOrigin=
"Anonymous",xa.src=w.url,xa.onload=function(){T=xa.width;X=xa.height;P()};else if(w.C){var Za=function(){L();T?P():setTimeout(Za,1)};Za()}else w.array?(w.G&&!w.isFloat?w.array instanceof Uint16Array?(na=w.array,P()):h()?(na=d(w.array),P()):(P(),R.uc(D,ma,ea.A(),ea.J(),w.array,sa,!0)):(na=w.isFloat?w.array instanceof Float32Array?w.array:new Float32Array(w.array):w.array instanceof Uint8Array?w.array:new Uint8Array(w.array),P()),w.isKeepArray||(na&&na!==w.array&&(na=null),delete w.array)):w.Bc?Ea=
!0:P();ea.Qf=ea.A;w.ca&&Ea&&(w.ca(ea),w.ca=null);m.push(ea);return ea},M:function(e){e!==l&&(D.activeTexture(r[e]),l=e);u[e]=-1;a(null)},vf:function(e){y.random.g(e)},$b:function(){p=null;D.framebufferTexture2D(Sa.Na(),D.COLOR_ATTACHMENT0,D.TEXTURE_2D,null,0)},reset:function(){0!==l&&D.activeTexture(r[0]);for(var e=0;e<r.length;++e)u[e]=-1;l=-1},dg:function(){l=-1},hf:function(){for(var e=0;e<r.length;++e)R.M(e)},xc:function(){y&&(y.random.remove(),y.td.remove())},pg:function(e,L){if("RGBA"===e.format||
"RGBE"===e.format){var H=new Image;H.src=e.data;H.onload=function(){R.instance({isMirrorY:e.isMirrorY,isFlipY:e.isFlipY,isFloat:!1,C:H,ca:function(P){if("RGBA"===e.format)L(P);else{var aa=e.width,W=e.height,la=R.instance({isMirrorY:e.isMirrorY,isFloat:!0,width:aa,height:W,isFlipY:e.isFlipY});Sa.U();D.viewport(0,0,aa,W);G.set("s43");la.u();P.g(0);N.l(!0,!0);R.M(0);L(la);D.flush();setTimeout(P.remove,50)}}})}}else"JSON"===e.format?L(R.instance({isFloat:!0,isFlipY:e.isFlipY,width:e.width,height:e.height,
array:new Float32Array(e.data)})):L(!1)},Ld:d,m:function(){p&&(Sa.U(),R.$b(),Sa.M());R.hf();m.slice(0).forEach(function(e){e.remove()});m.splice(0);g=!1;f=0;"undefined"!==typeof Qa&&Qa.m();y=null}};return R}(),Va={instance:function(a){var c=[Q.instance(a),Q.instance(a)],d=[c[1],c[0]],h=d,t={nd:function(n){h[1].u();h[0].g(n);t.rd()},fg:function(n){h[1].P();h[0].g(n);t.rd()},rd:function(){h=h===c?d:c},refresh:function(){h[0].refresh();h[1].refresh()},g:function(n){h[0].g(n)},uf:function(n){h[1].g(n)},
he:function(){return h[0]},Of:function(){return h[1]},remove:function(){h[0].remove();h[1].remove();h=null}};return t}},N=function(){function a(f){var u={T:null,F:null};u.T=f.createBuffer();f.bindBuffer(f.ARRAY_BUFFER,u.T);f.bufferData(f.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),f.STATIC_DRAW);u.F=f.createBuffer();f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,u.F);f.bufferData(f.ELEMENT_ARRAY_BUFFER,new Uint16Array([0,1,2]),f.STATIC_DRAW);return u}var c=null,d=0,h=!1,t=[],n=-2,l=-2,r={reset:function(){l=
n=-2},s:function(){h||(c=a(D),r.kb(),h=!0)},instance:function(f){var u=d++,y=f.F?f.F.length:0,p="undefined"===typeof f.mode?D.STATIC_DRAW:f.mode,k=D.createBuffer();D.bindBuffer(D.ARRAY_BUFFER,k);D.bufferData(D.ARRAY_BUFFER,f.T instanceof Float32Array?f.T:new Float32Array(f.T),p);n=u;var A=null,x=null,g=null;if(f.F){A=D.createBuffer();D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,A);var m=null;65536>f.F.length?(m=Uint16Array,x=D.UNSIGNED_SHORT,g=2):(m=Uint32Array,x=D.UNSIGNED_INT,g=4);m=f.F instanceof m?f.F:
new m(f.F);D.bufferData(D.ELEMENT_ARRAY_BUFFER,m,p);l=u}var K={Fd:function(O){n!==u&&(D.bindBuffer(D.ARRAY_BUFFER,k),n=u);O&&Pa.Ub()},Cd:function(){l!==u&&(D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,A),l=u)},bind:function(O){K.Fd(O);K.Cd()},Bf:function(){D.drawElements(D.TRIANGLES,y,x,0)},Cf:function(O,E){D.drawElements(D.TRIANGLES,O,x,E*g)},remove:function(){D.deleteBuffer(k);f.F&&D.deleteBuffer(A);K=null}};t.push(K);return K},kb:function(){-1!==n&&(D.bindBuffer(D.ARRAY_BUFFER,c.T),n=-1);-1!==l&&(D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,
c.F),l=-1)},l:function(f,u){f&&N.kb();u&&Pa.Za();D.drawElements(D.TRIANGLES,3,D.UNSIGNED_SHORT,0)},Ja:function(f){f=f||D;var u=a(f);f.bindBuffer(f.ARRAY_BUFFER,u.T);f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,u.F);Pa.$a(f);f.clear(f.COLOR_BUFFER_BIT);f.drawElements(f.TRIANGLES,3,f.UNSIGNED_SHORT,0);f.flush();f.bindBuffer(f.ARRAY_BUFFER,null);f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,null);f.deleteBuffer(u.T);f.deleteBuffer(u.F);r.reset();h&&(r.kb(),Pa.Za())},xc:function(){var f=D,u=c;f.deleteBuffer(u.T);f.deleteBuffer(u.F)},
m:function(){r.xc();t.forEach(function(f){f.remove()});D.bindBuffer(D.ARRAY_BUFFER,null);D.bindBuffer(D.ELEMENT_ARRAY_BUFFER,null);r.reset();h=!1;t.splice(0);d=0}};return r}(),Sa=function(){var a=null,c=null,d=null,h=!1,t=[],n={D:-2,tc:1},l={Sa:function(){return h},s:function(){if(!h){a=D.createFramebuffer();var r=Ra.Y();c=r&&D.DRAW_FRAMEBUFFER?D.DRAW_FRAMEBUFFER:D.FRAMEBUFFER;d=r&&D.READ_FRAMEBUFFER?D.READ_FRAMEBUFFER:D.FRAMEBUFFER;h=!0}},Lf:function(){return c},fe:function(){return d},Na:function(){return D.FRAMEBUFFER},
Pf:function(){return n},Ef:function(){return a},instance:function(r){void 0===r.Ic&&(r.Ic=!1);var f=r.pa?r.pa:null,u=r.width,y=void 0!==r.height?r.height:r.width,p=a,k=null,A=!1,x=!1,g=0;f&&(u=u?u:f.A(),y=y?y:f.J());var m={md:function(){A||(p=D.createFramebuffer(),A=!0,g=n.tc++)},xd:function(){m.md();m.u();k=D.createRenderbuffer();D.bindRenderbuffer(D.RENDERBUFFER,k);D.renderbufferStorage(D.RENDERBUFFER,D.DEPTH_COMPONENT16,u,y);D.framebufferRenderbuffer(c,D.DEPTH_ATTACHMENT,D.RENDERBUFFER,k);D.clearDepth(1)},
bind:function(K,O){g!==n.D&&(D.bindFramebuffer(c,p),n.D=g);f&&f.u();O&&D.viewport(0,0,u,y);K&&D.clear(D.COLOR_BUFFER_BIT|D.DEPTH_BUFFER_BIT)},tf:function(){g!==n.D&&(D.bindFramebuffer(c,p),n.D=g)},clear:function(){D.clear(D.COLOR_BUFFER_BIT|D.DEPTH_BUFFER_BIT)},yf:function(){D.clear(D.COLOR_BUFFER_BIT)},zf:function(){D.clear(D.DEPTH_BUFFER_BIT)},bf:function(){D.viewport(0,0,u,y)},u:function(){g!==n.D&&(D.bindFramebuffer(c,p),n.D=g)},rtt:function(K){f=K;n.D!==g&&(D.bindFramebuffer(D.FRAMEBUFFER,p),
n.D=g);K.u()},M:function(){D.bindFramebuffer(c,null);n.D=-1},resize:function(K,O){u=K;y=O;k&&(D.bindRenderbuffer(D.RENDERBUFFER,k),D.renderbufferStorage(D.RENDERBUFFER,D.DEPTH_COMPONENT16,u,y))},remove:function(){p===a||x||(D.bindFramebuffer(c,p),D.framebufferTexture2D(c,D.COLOR_ATTACHMENT0,D.TEXTURE_2D,null,0),k&&D.framebufferRenderbuffer(c,D.DEPTH_ATTACHMENT,D.RENDERBUFFER,null),D.bindFramebuffer(c,null),D.deleteFramebuffer(p),k&&D.deleteRenderbuffer(k));x=!0}};r.Ic&&m.xd();t.push(m);return m},
M:function(){D.bindFramebuffer(c,null);n.D=-1},jf:function(){D.bindFramebuffer(c,null);D.clear(D.COLOR_BUFFER_BIT|D.DEPTH_BUFFER_BIT);D.viewport(0,0,Ra.A(),Ra.J());n.D=-1},reset:function(){n.D=-2},U:function(){0!==n.D&&(D.bindFramebuffer(c,a),n.D=0)},clear:function(){D.viewport(0,0,Ra.A(),Ra.J());D.clear(D.COLOR_BUFFER_BIT)},m:function(){l.M();t.forEach(function(r){r.remove()});null!==a&&(D.deleteFramebuffer(a),a=null);l.reset();h=!1;t.splice(0);n.tc=1}};return l}(),Ra=function(){function a(){h="undefined"===
typeof Ua?JEContext:Ua;t=!0}function c(g,m){for(var K=0;K<g.length;++K){var O=m.getExtension(g[K]);if(O)return O}return null}function d(){null!==k.cb&&(clearInterval(k.cb),k.cb=null);k.ua=!1}var h=null,t=!1,n={Jc:!1,Wb:null,Xb:null,Mc:!1,ye:!1,Yb:null,Nc:!1,Zb:null,Kc:!1,mb:null,se:!1,nb:null,te:!1},l=null,r={V:!0,W:!0,rb:!0,ed:!1},f=null,u=!0,y=null,p=null,k={ua:!1,ka:null,Oa:null,wb:-1,la:null,cb:null},A="undefined"===typeof window?{}:window,x={s:function(){if(t)return!0;x.reset();t||a();var g=
D;if(!l.Jc){l.Wb=x.qc(g);A.GL_EXT_FLOAT=l.Wb;l.Mc=l.Wb?!0:!1;if(l.Mc||x.Y())l.Xb=x.rc(g),l.ye=l.Xb?!0:!1,A.GL_EXT_FLOATLINEAR=l.Xb;l.Jc=!0}if(!l.Kc){l.Yb=x.Ia(g);l.Yb&&(l.Nc=!0,A.GL_EXT_HALFFLOAT=l.Yb);if(l.Nc||x.Y())l.Zb=x.sc(g),A.GL_EXT_HALFFLOATLINEAR=l.Zb;l.Vf=l.Zb?!0:!1;l.Kc=!0}l.mb=x.oc(g);l.se=l.mb?!0:!1;A.GL_EXT_COLORBUFFERFLOAT=l.mb;l.nb=x.pc(g);l.te=l.nb?!0:!1;A.GL_EXT_COLORBUFFERHALFFLOAT=l.nb;Sa.s();Q.s();if(!x.Rd())return!1;N.s();Q.pe();return!0},reset:function(){l=Object.assign({},n);
f=Object.assign({},r)},A:function(){t||a();return h.A()},J:function(){t||a();return h.J()},Y:function(){t||a();return h.Y()},nc:function(g){x.oc(g);x.pc(g);x.qc(g);x.rc(g);x.Ia(g);x.sc(g)},oc:c.bind(null,["EXT_color_buffer_float","WEBGL_color_buffer_float","OES_color_buffer_float"]),pc:c.bind(null,["EXT_color_buffer_half_float","WEBGL_color_buffer_half_float","OES_color_buffer_half_float"]),qc:c.bind(null,["OES_texture_float","MOZ_OES_texture_float","WEBKIT_OES_texture_float"]),rc:c.bind(null,["OES_texture_float_linear",
"MOZ_OES_texture_float_linear","WEBKIT_OES_texture_float_linear"]),Ia:c.bind(null,["OES_texture_half_float","MOZ_OES_texture_half_float","WEBKIT_OES_texture_half_float"]),sc:c.bind(null,["OES_texture_half_float_linear","MOZ_OES_texture_half_float_linear","WEBKIT_OES_texture_half_float_linear"]),tb:function(g){var m=x.Ia(g);return m&&m.HALF_FLOAT_OES?m.HALF_FLOAT_OES:g.HALF_FLOAT||g.FLOAT},ce:function(){return p||D.RGBA32F||D.RGBA},de:function(){return y||D.RGBA16F||D.RGBA},$d:function(){return f},
lc:function(){return f.V},xf:function(){return f.W},wf:function(){return f.rb},Hd:function(){return f.ed&&u},sd:function(g){u=g;!g&&k.ua&&(D.deleteSync(k.Oa),D.bindBuffer(k.la,null),k.ua=!1)},bb:function(g,m,K){function O(){g.bindTexture(g.TEXTURE_2D,null);g.bindFramebuffer(E,null);g.deleteTexture(J);g.deleteFramebuffer(I)}var E=g.FRAMEBUFFER,S=g.NEAREST,I=g.createFramebuffer();g.bindFramebuffer(E,I);var J=g.createTexture();g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,J);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,
!1);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,S);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,S);g.texImage2D(g.TEXTURE_2D,0,m,3,3,0,g.RGBA,K,null);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,J,0);if(g.checkFramebufferStatus(g.READ_FRAMEBUFFER||g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)return O(),!1;Pa.Sb(g);g.clearColor(0,0,0,0);g.viewport(0,
0,3,3);g.disable(g.DEPTH_TEST);g.clear(g.COLOR_BUFFER_BIT);N.Ja(g);g.bindFramebuffer(E,null);Pa.xa(g);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,J);N.Ja(g);m=new Uint8Array(36);g.readPixels(0,0,3,3,g.RGBA,g.UNSIGNED_BYTE,m);O();for(K=0;36>K;++K)if(3!==K%4&&3<Math.abs(m[K]-127))return!1;return!0},pb:function(g){var m={V:!1,W:!1};g.disable(g.BLEND);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);g.RGBA32F&&x.bb(g,g.RGBA32F,g.FLOAT)&&(m.V=!0,p=g.RGBA32F);!m.V&&x.bb(g,g.RGBA,g.FLOAT)&&(m.V=
!0,p=g.RGBA);var K=x.tb(g);y=null;g.RGBA16F&&x.bb(g,g.RGBA16F,K)&&(m.W=!0,y=g.RGBA16F);!m.W&&x.bb(g,g.RGBA,K)&&(m.W=!0,y=g.RGBA);return m},Sd:function(){var g=Sa.instance({width:2});g.md();var m=Q.instance({width:2,isFloat:!0,Ua:3});g.u();m.u();D.flush();D.checkFramebufferStatus(Sa.fe())!==D.FRAMEBUFFER_COMPLETE?(Q.Ze(),f.rb=!1):f.rb=!0;g.remove();m.remove()},Td:function(){var g=!1;x.Y()&&(g="PIXEL_PACK_BUFFER STREAM_READ SYNC_GPU_COMMANDS_COMPLETE WAIT_FAILED fenceSync deleteSync createBuffer".split(" ").every(function(m){return"undefined"!==
typeof D[m]}));f.ed=g},Rd:function(){var g=x.pb(D);Object.assign(f,g);if(!f.V&&!f.W)return!1;x.Sd();x.Td();return!0},Rb:function(g,m,K,O,E){if(!x.Hd())return D.readPixels(g,m,K,O,D.RGBA,D.UNSIGNED_BYTE,E),Promise.resolve(E);null===k.ka&&(k.la=D.PIXEL_PACK_BUFFER,k.ka=D.createBuffer(),k.wb=-1);D.bindBuffer(k.la,k.ka);E.byteLength!==k.wb&&(D.bufferData(k.la,E.byteLength,D.STREAM_READ),k.wb=E.byteLength);D.readPixels(g,m,K,O,D.RGBA,D.UNSIGNED_BYTE,0);k.Oa=D.fenceSync(D.SYNC_GPU_COMMANDS_COMPLETE,0);
D.flush();return new Promise(function(S,I){function J(){if(!k.ua)return d(),I(),!1;switch(D.clientWaitSync(k.Oa,0,0)){case D.TIMEOUT_EXPIRED:return!1;case D.WAIT_FAILED:return d(),I(),!1;default:return d(),D.deleteSync(k.Oa),D.getBufferSubData(k.la,0,E),D.bindBuffer(k.la,null),S(E),!0}}d();k.ua=!0;J()||(k.cb=setInterval(J,0))})},m:function(){d();Q.m();Pa.m();Sa.m();N.m();null!==k.ka&&(D.deleteBuffer(k.ka),k.ka=null);t=!1}};return x}(),Qa=function(){function a(I,J,v,q){m.texParameteri(m.TEXTURE_2D,
m.TEXTURE_MIN_FILTER,q?m.NEAREST_MIPMAP_NEAREST:m.LINEAR);var C=null;if(null!==v)try{C=m.getError();if("FUCKING_BIG_ERROR"===C)return!1;m.texImage2D(m.TEXTURE_2D,0,I,4,4,0,m.RGBA,J,v);C=m.getError();if(C!==m.NO_ERROR)return!1}catch(M){return!1}q&&m.generateMipmap(m.TEXTURE_2D);m.clear(m.COLOR_BUFFER_BIT);N.Ja(m);C=m.getError();if("FUCKING_BIG_ERROR"===C)return!1;m.readPixels(0,0,2,2,m.RGBA,m.UNSIGNED_BYTE,y);C=m.getError();C===m.INVALID_OPERATION&&"undefined"!==typeof m.PIXEL_PACK_BUFFER&&(m.bindBuffer(m.PIXEL_PACK_BUFFER,
null),m.readPixels(0,0,2,2,m.RGBA,m.UNSIGNED_BYTE,y),C=m.getError());if(C!==m.NO_ERROR)return!1;v=!0;for(q=0;16>q;++q)v=v&&4>Math.abs(y[q]-127);v&&(f.Yc=J,f.Hc=I);return v}function c(I,J){return K.V&&a(I,m.FLOAT,new Float32Array(p),J)?(r=l.cc,!0):!1}function d(I,J,v){if(!K.W)return!1;var q=Q.Ld(p),C=Ra.Ia(m);if(C&&C.HALF_FLOAT_OES&&a(I,C.HALF_FLOAT_OES,q,J)||m.HALF_FLOAT&&a(I,m.HALF_FLOAT,q,J))return r=l.qa,!0;q=new Float32Array(p);if(a(I,m.FLOAT,q,J))return r=l.qa,!0;m.bindTexture(m.TEXTURE_2D,v);
m.texImage2D(m.TEXTURE_2D,0,m.RGBA,2,2,0,m.RGBA,m.UNSIGNED_BYTE,null);m.bindFramebuffer(f.Ga,S);Q.uc(m,v,2,2,q,!1,!1);m.bindFramebuffer(f.Ga,null);m.bindTexture(m.TEXTURE_2D,v);return a(I,null,null,J)?(r=l.qa,!0):!1}function h(I,J,v){u=!0;if(d(I,!0,v)||c(J,!0))return!0;u=!1;return d(I,!1,v)||c(J,!1)?!0:!1}function t(I){if(r===l.N){m=I||D;r=l.RGBA8;u=!0;Ra.nc(m);K||(K=Ra.pb(m));Sa.reset();S=m.createFramebuffer();f.Ga=m.DRAW_FRAMEBUFFER||m.FRAMEBUFFER;m.bindFramebuffer(f.Ga,null);m.clearColor(0,0,0,
0);m.viewport(0,0,2,2);G.N();O=G.xa(m);I=m.createTexture();m.activeTexture(m.TEXTURE0);m.bindTexture(m.TEXTURE_2D,I);m.texParameteri(m.TEXTURE_2D,m.TEXTURE_WRAP_S,m.REPEAT);m.texParameteri(m.TEXTURE_2D,m.TEXTURE_WRAP_T,m.REPEAT);m.texParameteri(m.TEXTURE_2D,m.TEXTURE_MAG_FILTER,m.NEAREST);E=I;var J=I=m.RGBA,v=m.RGBA16F,q=m.RGBA32F;q&&(I=q);v&&(J=v);if((v||q)&&h(J,I,E))return n(),!0;I=J=m.RGBA;if(h(J,I,E))return n(),!0;r=l.RGBA8;n();return!1}}function n(){m.deleteProgram(O.ea);m.deleteTexture(E);E=
O=null}for(var l={N:-1,cc:3,qa:2,RGBA8:0},r=l.N,f={Yc:null,Hc:null,Ga:null},u=!0,y=new Uint8Array(16),p=Array(64),k=0;4>k;++k)for(var A=0;4>A;++A){var x=0===(A+k)%2?1:0,g=4*k+A;p[4*g]=x;p[4*g+1]=x;p[4*g+2]=x;p[4*g+3]=x}var m=null,K=null,O=null,E=null,S=null;return{Gd:function(I){t(I);return u},kc:function(I,J){r===l.N&&(typeof("undefined"!==J)&&(K=J),t(I));return r!==l.RGBA8},Yf:function(I){t(I);return r===l.cc},ze:function(I){t(I);return r===l.qa},Mf:function(I){t(I);return f.Yc},ee:function(I){t(I);
return f.Hc},m:function(){m=null;u=!0;r=l.N;K=null}}}(),Wa={instance:function(a){var c=Q.instance(a.alpha),d=Q.instance(a.beta);return{Vd:function(){c.g(1);d.g(2)}}}},bb={instance:function(a){var c=null,d=!1,h=!1,t=null,n=!1,l=!1,r=null,f="undefined"===typeof a.preprocessing?!1:a.preprocessing,u="undefined"===typeof a.preprocessingSize?a.size:a.preprocessingSize;a.mask&&(d=!0,b&&void 0!==b.Bd&&(a.mask=b.Bd+a.mask),c=Q.instance({isFloat:!1,url:a.mask}));var y=!1;a.customInputShader&&(y="s44",G.dc({name:"_",
id:y,h:a.customInputShader,og:["uSource"],precision:"lowp"}),G.I(y,[{type:"1i",name:"_",value:0}]));switch(f){case "sobel":r="s31";n=!0;break;case "meanNormalization":r="s32";n=!0;break;case "grayScale":r="s28";n=!1;break;case "grayScaleTilt":r="s29";l=!0;n=!1;break;case "rgbGrayTilt":r="s30";l=!0;n=!1;break;case "copy":r=y?y:"s0";break;case "inputLightRegulation":r=y?y:"s28";t=$a.instance({Gc:u,Xc:a.size,Tc:a.nBlurPass,Ra:!1});h=!0;break;case "inputMix0":r="none";t=ab.instance({ha:u,vd:a.varianceMin,
jc:a.blurKernelSizePx,Ra:!1});h=!0;break;case "direct":case "none":r="abort";break;default:r="s3"}l&&G.I(r,[{name:"u26",type:"1f",value:a.tilt}]);d&&(r+="Mask");var p=Q.instance({isFloat:!1,isPot:!1,width:a.size}),k={A:function(){return u},ub:function(){return k.A()},le:function(){return h?t.vb():p},K:function(A){Sa.U();"abort"!==r&&("none"!==r&&(G.set(r),n&&G.L("u27",1/a.size),p.P(),d&&c.g(1),N.l(!1,!1),p.g(0),A=p),h&&t.process(A))},m:function(){p.remove();d&&c.remove()}};return k}},ib={instance:function(a){function c(e){t.forEach(function(L,
H){n[H][0]=e[0][L];n[H][1]=e[1][L];n[H][2]=e[2][L];n[H][3]=e[3][L]});return n}"undefined"===typeof a.normalize&&(a.normalize=!1);var d={input:null,Ea:null,Ab:null,S:null,Va:null,Nb:null,Ob:null},h=null,t=[],n=[],l=!1,r=null,f=!0,u=-1,y=a.isReorganize?a.isReorganize:!1,p=a.kernelsCount?!0:!1,k=a.dynPelu?Wa.instance(a.dynPelu):!1,A=k?!0:!1,x={isEnabled:!1};a.xe?(a.sparsity="undefined"!==typeof a.sparsity?a.sparsity:a.Xa.ub(),f=!1):"full"===a.connectivityUp&&(a.sparsity=a.Xa.ub());var g={elu:"s15",elu01:"s16",
relu:"s14",arctan:"s18",sigmoid:"s13",copy:"s0",softplus:"s19",dynPelu:"s17"}[a.activation],m=a.sparsity*a.sparsity,K=!1,O=a.size,E="";if(a.maxPooling){switch(a.maxPooling.size){case 2:E="s33";break;case 4:E="s34"}K=!0;O/=a.maxPooling.size;d.Nb=Q.instance({isFloat:!0,isPot:!1,width:O})}var S=void 0!==a.Ee&&a.Ee?!0:!1,I=null,J=null,v=null;if(S){I="s45"+a.index.toString();G.Ec("s45",I,[((a.normalization.n-1)/2).toFixed(1)]);G.I(I,[{type:"1i",name:"u1",value:0},{type:"2f",name:"u7",value:[1/a.size,1/
a.size]},{type:"1f",name:"u6",value:a.normalization.alpha},{type:"1f",name:"u9",value:a.normalization.beta},{type:"1f",name:"u30",value:a.normalization.k}]);var q={isFloat:!0,isPot:!0,width:a.size};J=Q.instance(q);v=Q.instance(q)}var C=-1,M=null;f&&(d.S=Q.instance({isFloat:!0,isPot:!1,width:a.size}));d.Ea=Q.instance(a.bias);var R={A:function(){return a.size},ub:function(){return O},yc:function(){return a.classesCount},Dd:function(e){h.g(e)},Ie:function(){a.remap&&a.remap.isEnabled&&(x={isEnabled:!0,
Ae:Q.instance({isFloat:!1,isFlipY:!1,array:new Uint8Array(a.remap.maskTexture.data),width:a.remap.maskTexture.width,isPot:!1}),Ta:a.remap.layers.map(function(e){return a.parent.ie(e)}),depth:a.remap.depth})},$e:function(){switch(a.connectivityUp){case "direct":M=cb.instance(a.connectivity);break;case "square":M=db.instance(a.connectivity);break;case "squareFast":M=fb.instance(a.connectivity,a.activation);break;case "full":M=gb.instance(a.connectivity);break;case "conv":u=a.kernelsCount,M=hb.instance(a.connectivity),
y&&(d.Va=Q.instance({width:O,isFloat:!0,isFlipY:!1,isPot:!1}))}if(M.oa){var e=a.size*a.sparsity;C=Math.log(e/a.size)/Math.log(2);d.input=Q.instance({isMipmap:!0,isFloat:!0,isPot:!0,width:e,Hb:C});d.Ab=Q.instance({isFloat:!0,isPot:!0,width:a.size})}},K:function(e,L){h=e;M.oa?(d.input.P(),p&&d.Ea.g(2),M.K(x),d.input.g(0),d.input.Zd(C),d.Ab.P(),p?G.set("s0"):(G.set("s27"),G.L("u25",m),d.Ea.g(1)),d.input.Ed(C,0),N.l(!1,!1),G.set(g),S?J.u():d.S.u(),d.Ab.g(0),A&&k.Vd(),N.l(!1,!1)):(d.S.P(),d.Ea.g(1),M.K());
S&&(G.set(I),v.u(),J.g(0),N.l(!1,!1),G.set("s46"),G.L("u6",1),d.S.u(),v.g(1),N.l(!1,!1));if(f)return K?(d.Nb.P(),d.S.g(0),G.set(E),G.fa("u7",1/a.size,1/a.size),N.l(!1,!1),L=d.Nb):L=d.S,L.g(0),y&&(d.Va.u(),G.set("s21"),G.fa("u12",u,O/u),N.l(!1,!1),L=d.Va,d.Va.g(0)),L;var H=d.S;a.normalize&&(G.set("gpuRawAvg"===l?"s8":"s7"),G.L("u4",1/a.size),d.Ob.P(),d.S.g(0),N.l(!1,!1),H=d.Ob);e=null;switch(l){case "cpuRGBA2Float":H.qb(!1);L?e=R.Ke(H).then(r):(H=R.Le(H),r(H));break;case "cpuMeanFloat":H.qb(!0);L?
e=H.Ne().then(r):(H=H.Oe(),r(H));break;case "gpuRawAvg":case "gpuRaw":H.g(0);case "none":null!==r&&r(H)}L&&null===e&&(e=Promise.resolve());return e},Md:function(e){e&&(l=e.Pb||"none",r=e.Mb||null);d.S=Q.instance({isFloat:!0,isPot:!0,isMipmap:!1,width:a.size});e="undefined"!==typeof a.classesCount&&a.classesCount?a.classesCount:a.size*a.size;for(var L=0,H=0,P=0;L<e;++L)t.push(H+(a.size-1-P)*a.size),n.push([-1,-1,-1,-1]),++H,H===a.size&&(H=0,++P);a.normalize&&(d.Ob=Q.instance({isFloat:!0,isPot:!0,width:a.size}))},
Ke:function(e){return e.Me().then(c)},Le:function(e){e=e.Qb();c(e);return n},m:function(){for(var e in d){var L=d[e];L&&L.remove()}M&&(M.m(),M=null)}};a.Xa&&R.$e(a.Xa);return R}};
function jb(a){var c=null,d=null,h=null,t=0;this.s=function(n){this.Ye(n.Ta);h.Md({Pb:n.Pb,Mb:n.Mb})};this.ie=function(n){return c[n]};this.Ye=function(n){var l=null;t=n.length;c=n.map(function(r,f){r=Object.assign({},r,{index:f,parent:this,Xa:l,xe:f===t-1});return l=f=0===f?bb.instance(r):ib.instance(r)});d=c[0];h=c[t-1];c.forEach(function(r,f){0!==f&&r.Ie()})};this.K=function(n){var l=n;c.forEach(function(r){l=r.K(l,!1)});return l};this.ge=function(){return d.A()};this.me=function(){return h.A()};
this.vb=function(){return h.le()};this.yc=function(){return h.yc()};this.m=function(){c&&(c.forEach(function(n){n.m()}),h=d=c=null,t=0)};"undefined"!==typeof a&&this.s(a)}
var cb={instance:function(a){var c=Q.instance(a.weights);return{oa:!0,Ma:function(){return 1},m:function(){c.remove()},oe:function(){return c},K:function(){G.set("s26");c.g(1);N.l(!1,!1)}}}},gb={instance:function(a){var c=a.fromLayerSize,d=Q.instance(a.weights);return{oa:!0,Ma:function(){return c},m:function(){d.remove()},K:function(h){if(h.isEnabled){G.set("s24");h.Ae.g(3);var t,n=Math.min(h.Ta.length,h.depth);for(t=0;t<n;++t)h.Ta[t].Dd(4+t)}else G.set("s23");G.L("u16",a.toLayerSize);d.g(1);N.l(!1,
!1)}}}},db={instance:function(a){for(var c=a.fromLayerSize,d=a.toLayerSize,h=a.toSparsity,t=h*d,n=t/c,l=c/d,r=0,f=0,u=0,y=Array(h*d*h*d*4),p=Array(h*d*h*d*4),k=Array(c*c),A=0;A<k.length;++A)k[A]=0;A=Math.floor(h/2);for(var x=.5/d,g=.5/c,m=.5/t,K=0;K<d;++K)for(var O=Math.round(K*l),E=0;E<d;++E){var S=Math.round(E*l),I=K/d,J=E/d;I+=x;J+=x;for(var v=0;v<h;++v){var q=O+v-A;0>q&&(q+=c);q>=c&&(q-=c);for(var C=0;C<h;++C){var M=r/t,R=f/t,e=S+C-A;0>e&&(e+=c);e>=c&&(e-=c);var L=q/c,H=e/c;R=1-R-1/t;L+=g;H+=
g;M+=m;R+=m;var P=K*h+v,aa=E*h+C;aa=d*h-aa-1;P=aa*d*h+P;y[4*P]=M;y[4*P+1]=R;y[4*P+2]=L;y[4*P+3]=H;H=k[e*c+q]++;P=H%n;L=q*n+P;e=e*n+(H-P)/n;e=c*n-1-e;e=e*c*n+L;p[4*e]=M;p[4*e+1]=R;p[4*e+2]=I;p[4*e+3]=J;++r>=t&&(r=0,++f);++u}}}k=null;var W=Q.instance(a.weights);delete a.weights.data;var la=Q.instance({width:t,isFloat:!0,array:new Float32Array(p),isPot:!0});p=null;var w=Q.instance({width:t,isFloat:!0,array:new Float32Array(y),isPot:!0});y=null;return{oa:!0,Ma:function(){return n},m:function(){la.remove();
w.remove();W.remove()},K:function(){G.set("s22");W.g(1);w.g(2);N.l(!1,!1)}}}},hb={instance:function(a){var c=a.kernelsCount,d=a.toSparsity,h=d*a.toLayerSize/a.fromLayerSize,t=Q.instance(a.weights);return{oa:!0,Ma:function(){return h},Sf:function(){return d},oe:function(){return t},m:function(){t.remove()},K:function(){G.set("s25");G.L("u22",c);G.L("u23",d);G.L("u16",a.toLayerSize);G.L("u24",a.fromLayerSize);t.g(1);N.l(!1,!1)}}}},fb={instance:function(a,c){var d=a.fromLayerSize,h=a.toLayerSize,t=a.toSparsity,
n=a.stride?a.stride:1,l=t*h/d,r=h<d,f=d/h,u=Q.instance(a.weights),y="s47"+[d.toString(),h.toString(),t.toString(),n.toString(),c].join("_");G.Yd(y)||(a=Ja(c),h=[{type:"1f",name:"u16",value:h},{type:"1f",name:"u29",value:n}],r&&h.push({type:"1f",name:"u24",value:d}),d=[(r?l:t).toFixed(1),a],r&&d.push(f.toFixed(1)),G.Ec(r?"s39":"s38",y,d),G.I(y,h.concat([{type:"1i",name:"u14",value:0},{type:"1i",name:"u21",value:1},{type:"1i",name:"u13",value:3}])));return{oa:!1,Ma:function(){return l},m:function(){u.remove()},
K:function(){G.set(y);u.g(3);N.l(!1,!1)}}}},$a={instance:function(a){var c=a.Tc?a.Tc:3,d=a.Gc?a.Gc:64,h=a.Xc?a.Xc:64,t=a.Ra?!0:!1;a={isFloat:!1,width:d,isPot:!1,isFlipY:!1};var n=Q.instance(a),l=Q.instance(a),r=Q.instance(a),f=Q.instance(a),u=Q.instance({isFloat:!0,width:h,isPot:!1,isFlipY:!1}),y=1/d;return{process:function(p){G.set("s35");f.u();N.l(t,!1);G.set("s36");for(var k=0;k<c;++k)n.u(),G.fa("u7",y,0),N.l(t,!1),r.u(),f.g(0),N.l(t,!1),l.u(),n.g(0),G.fa("u7",0,y),N.l(t,!1),f.u(),r.g(0),N.l(t,
!1),k!==c-1&&l.g(0);G.set("s37");u.u();p.g(0);l.g(1);f.g(2);N.l(t,!1);u.g(0)},vb:function(){return u}}}},ab={instance:function(a){function c(u){return Q.instance({isFloat:u,width:d.ha,isPot:!1,isFlipY:!1})}var d=Object.assign({vd:.1,jc:9,ha:128,Ra:!1},a),h=c(!1),t=[c(!1),c(!1),c(!1)],n=[c(!1),c(!1),c(!1)],l=c(!0),r=[h,n[0],n[1]];a="uniform sampler2D u1;const float e=1.1111,g=2.2222;uniform vec2 u31;varying vec2 vv0;void main(){float b=0.,c=0.;for(float a=-e;a<=e;a+=1.){vec2 i=u31*a,j=vv0+i*g;float d=1.2*a/e,f=exp(-d*d);b+=f*texture2D(u1,j).r,c+=f;}b/=c,gl_FragColor=vec4(b,0.,0.,1.);}".replace("1.1111",
Math.round((d.jc-1)/2).toFixed(2)).replace("2.2222",(1/d.ha).toFixed(6));var f={u1:0};G.ec([{id:"s49",name:"_",h:"uniform sampler2D u1;varying vec2 vv0;const vec3 f=vec3(.2126,.7152,.0722),g=vec3(1.,1.,1.);void main(){vec3 b=texture2D(u1,vv0).rgb;float a=dot(b,f);gl_FragColor=vec4(a,a,a,a);}",j:f,i:["u1"],precision:"lowp"},{id:"s50",name:"_",h:a,j:f,i:["u1","u31"],precision:"lowp"},{id:"s51",name:"_",h:"uniform sampler2D u32,u33,u34,u35;const float f=1.1111;const vec3 g=vec3(1.,1.,1.);varying vec2 vv0;void main(){vec3 a=texture2D(u32,vv0).rgb;float c=texture2D(u33,vv0).r,d=texture2D(u34,vv0).r,h=texture2D(u35,vv0).r,i=a.r*a.r;vec3 b=vec3(c,d,h),j=max(g*f,abs(i-b*b)),k=sqrt(j);gl_FragColor=vec4(a.r,(a-b)/k);}".replace("1.1111",
d.vd.toFixed(4)),j:{u32:0,u33:1,u34:2,u35:3},i:["u32","u33","u34","u35"],precision:"highp"}]);return{process:function(){G.set("s49");h.P();N.l(d.Ra,!1);G.set("s50");for(var u=0;3>u;++u)G.fa("u31",1,0),t[u].u(),r[u].g(0),N.l(!1,!1),G.fa("u31",0,1),n[u].u(),t[u].g(0),N.l(!1,!1);G.set("s51");l.u();h.g(0);n[0].g(1);n[1].g(2);n[2].g(3);N.l(!1,!1);l.g(0)},vb:function(){return l}}}};function kb(a,c){a[c]=!0;a.setAttribute(c,"true")}
function lb(){return/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream}function mb(){var a=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);return a&&a.length&&2<a.length?[parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3]||0,10)]:[0,0,0]}function nb(){var a=navigator.userAgent.toLowerCase();return-1!==a.indexOf("safari")&&-1===a.indexOf("chrome")?!0:!1}function ob(){return navigator.mediaDevices&&navigator.mediaDevices.getUserMedia?!0:!1}
function pb(a){if(!a)return a;var c=null;if(a.video){var d=function(h){return h&&"object"===typeof h?Object.assign({},h):h};c={};"undefined"!==typeof a.video.width&&(c.width=d(a.video.width));"undefined"!==typeof a.video.height&&(c.height=d(a.video.height));"undefined"!==typeof a.video.facingMode&&(c.facingMode=d(a.video.facingMode))}c={audio:a.audio,video:c};"undefined"!==typeof a.deviceId&&qb(c,a.deviceId);return c}
function qb(a,c){c&&(a.video=a.video||{},a.video.deviceId={exact:c},a.video.facingMode&&delete a.video.facingMode)}function sb(a){var c=a.video.width;a.video.width=a.video.height;a.video.height=c;return a}
function tb(a){function c(k){return[480,576,640,648,720,768,800,960,1080,1152,1280,1366,1920].sort(function(A,x){return Math.abs(A-k)-Math.abs(x-k)})}function d(k){var A=pb(a);k=k(A);t.push(k);h(k)}function h(k){if(k.video&&k.video.facingMode&&k.video.facingMode.exact){var A=k.video.facingMode.exact;k=pb(k);delete k.video.facingMode.exact;k.video.facingMode.ideal=A;t.push(k)}}var t=[];if(!a||!a.video)return t;h(a);if(a.video.width&&a.video.height){if(a.video.width.ideal&&a.video.height.ideal){var n=
c(a.video.width.ideal).slice(0,3),l=c(a.video.height.ideal).slice(0,3),r={},f=0;for(r.ba=void 0;f<n.length;r={ba:r.ba},++f){r.ba=n[f];var u={},y=0;for(u.aa=void 0;y<l.length;u={aa:u.aa},++y)if(u.aa=l[y],r.ba!==a.video.width.ideal||u.aa!==a.video.height.ideal){var p=Math.max(r.ba,u.aa)/Math.min(r.ba,u.aa);p<4/3-.1||p>16/9+.1||d(function(k,A){return function(x){x.video.width.ideal=k.ba;x.video.height.ideal=A.aa;return x}}(r,u))}}}d(function(k){return sb(k)})}a.video.width&&a.video.height&&(a.video.width.ideal&&
a.video.height.ideal&&d(function(k){delete k.video.width.ideal;delete k.video.height.ideal;return k}),d(function(k){delete k.video.width;delete k.video.height;return k}));a.video.facingMode&&(d(function(k){delete k.video.facingMode;return k}),a.video.width&&a.video.height&&d(function(k){sb(k);delete k.video.facingMode;return k}));t.push({audio:a.audio,video:!0});return t}
function ub(a){try{var c=window.matchMedia("(orientation: portrait)").matches?!0:!1}catch(h){c=window.innerHeight>window.innerWidth}if(c&&a&&a.video){c=a.video.width;var d=a.video.height;c&&d&&c.ideal&&d.ideal&&c.ideal>d.ideal&&(a.video.height=c,a.video.width=d)}}
function vb(a){a.volume=0;kb(a,"muted");if(nb()){if(1===a.volume){var c=function(){a.volume=0;window.removeEventListener("mousemove",c,!1);window.removeEventListener("touchstart",c,!1)};window.addEventListener("mousemove",c,!1);window.addEventListener("touchstart",c,!1)}setTimeout(function(){a.volume=0;kb(a,"muted")},5)}}
function wb(a,c,d,h){function t(l){n||(n=!0,d(l))}var n=!1;navigator.mediaDevices.getUserMedia(h).then(function(l){function r(){setTimeout(function(){if(a.currentTime){var u=a.videoWidth,y=a.videoHeight;if(0===u||0===y)t("VIDEO_NULLSIZE");else{u&&(a.style.width=u.toString()+"px");y&&(a.style.height=y.toString()+"px");u={Id:null,cf:null,Be:null};try{var p=l.getVideoTracks()[0];p&&(u.Be=p,u.Id=p.getCapabilities(),u.cf=p.getSettings())}catch(k){}nb()||lb()?a.parentNode&&null!==a.parentNode?(n||c(a,l,
u),setTimeout(function(){a.play()},100)):(document.body.appendChild(a),vb(a),n||c(a,l,u),setTimeout(function(){a.style.transform="scale(0.0001,0.0001)";a.style.position="fixed";a.style.bottom="0px";a.style.right="0px";vb(a);setTimeout(function(){a.play()},100)},80)):n||c(a,l,u)}}else t("VIDEO_NOTSTARTED")},700)}function f(){a.removeEventListener("loadeddata",f,!1);var u=a.play();vb(a);"undefined"===typeof u?r():u.then(function(){r()}).catch(function(){t("VIDEO_PLAYPROMISEREJECTED")})}"undefined"!==
typeof a.srcObject?a.srcObject=l:(a.src=window.URL.createObjectURL(l),a.videoStream=l);vb(a);a.addEventListener("loadeddata",f,!1)}).catch(function(l){t(l)})}
function xb(a,c,d){var h=ob()?document.createElement("video"):!1;if(h)if(ob()){if(d&&d.video){if(lb()){var t=mb();0!==t[0]&&(12>t[0]||12===t[0]&&2>t[1])&&ub(d)}d.video.width&&d.video.width.ideal&&(h.style.width=d.video.width.ideal+"px");d.video.height&&d.video.height.ideal&&(h.style.height=d.video.height.ideal+"px")}kb(h,"autoplay");kb(h,"playsinline");d&&d.audio?h.volume=0:kb(h,"muted");wb(h,a,function(){function n(r){if(0===r.length)c("INVALID_FALLBACKCONSTRAINTS");else{var f=r.shift();wb(h,a,function(){n(r)},
f)}}var l=tb(d);n(l)},d)}else c&&c("MEDIASTREAMAPI_NOTFOUND");else c&&c("VIDEO_NOTPROVIDED")}
var yb=function(){var a={n:5,Jb:1,Rc:0,Ka:[30,45],Ha:[2,200],k:.7,lf:200,He:.05},c=-1,d=null,h=-1,t=-1,n=0,l=-1,r=-1,f=0,u=0,y=a.Ha[1],p={je:function(){switch(c){case -1:return-1;case 0:return r+d.Rc;case 1:return f}},ae:function(k){return Math.pow(Math.min(Math.max(l,0),d.n-1)/(d.n-1),k||1)},s:function(k){d=Object.assign({},a,k);l=r=d.Jb;c=0;p.reset()},ff:function(k){k=("undefined"===typeof k?Date.now():k)||0;var A=Math.min(Math.max(k-u,d.Ha[0]),d.Ha[1]);y=A;u=k;var x=-1===h?0:d.k;h=Math.min(Math.max(1E3/
A,5),120)*(1-x)+h*x;k-t>d.lf&&5<++n&&(A=d.k,l=l*(1-A)+(h<d.Ka[0]?r-1:h>d.Ka[1]?r+1:r)*A,Math.abs(l-r)>1-d.He&&(A=Math.min(Math.max(Math.round(l),0),d.n-1),A!==r&&(l=r=A,h=(d.Ka[1]-d.Ka[0])/2)),t=k)},Xe:function(k){f=k;c=1},kf:function(){c=0;p.reset()},reset:function(){y=a.Ha[1];t=h=-1;n=0},Jf:function(){return y}};return p}(),zb=function(){var a={Vc:4,Wa:[1.5,1.5,2],ga:[.1,.1,.1],hd:1,ha:-1,xb:-1,ef:2,Ge:1,kd:!0,Wd:.8},c=null,d=[],h=0,t=[.5,.5,1];return{s:function(n){c=Object.assign({},a,n);d.splice(0);
n=c.Wa[0]*c.ga[0];var l=c.Wa[1]*c.ga[1],r=1/(1+c.Wa[2]*c.ga[2]),f=c.hd*Math.min(c.ha,c.xb),u=f/c.ha;f/=c.xb;var y=.5*c.Wd;y*=y;for(var p=0;p<c.Vc;++p){var k=Math.pow(r,p),A=u*k,x=f*k;k=A*n;var g=x*l,m=A/2;x/=2;for(var K=1+(1-m-m)/k,O=1+(1-x-x)/g,E=0;E<O;++E)for(var S=x+E*g,I=S-.5,J=0;J<K;++J){var v=m+J*k,q=v-.5;q*q+I*I>y||d.push([v,S,A*c.Ge])}}c.kd&&d.sort(function(C,M){var R=C[0]-.5;C=C[1]-.5;var e=M[0]-.5;M=M[1]-.5;return R*R+C*C-(e*e+M*M)})},get:function(){var n=d.length;if(0===n)return t;h>=n&&
(h=0);var l=d[Math.floor(h)];h=(h+1/c.ef)%n;return l}}}(),Ab=function(){function a(){d(p+u.Ib);k.port.postMessage("DONE")}function c(){g.Ca=0===u.ja?window.requestAnimationFrame(d):window.requestAnimationFrame(h)}function d(E){x.ma&&null!==y&&(E-=p,E=Math.min(Math.max(E,u.mc[0]),u.mc[1]),p+=E,n(),y(p))}function h(E){x.ma&&(g.timeout=window.setTimeout(d.bind(null,E),u.ja))}function t(){y=null;x.ma=!1;n()}function n(){g.Ca&&(window.cancelAnimationFrame(g.Ca),g.Ca=null);g.timeout&&(window.clearTimeout(g.timeout),
g.timeout=null)}function l(E){E&&!x.X?(x.X=!0,A&&yb.kf(),k.port.postMessage("STOP"),Ra.sd(!0),c()):!E&&x.X&&(x.X=!1,A&&yb.Xe(1),Ra.sd(!1),k.port.postMessage("START"))}function r(E){E.target.hidden?K():m()}var f={Lc:!0,mc:[1,200],Ib:20,ja:0},u=null,y=null,p=0,k=null,A=!1,x={da:!1,X:!0,Fb:!1,Eb:!1,Cb:!1,ma:!1},g={Ca:null,timeout:null},m=l.bind(null,!0),K=l.bind(null,!1),O={s:function(E){u=Object.assign(f,E);Object.assign(x,{X:!0,da:!0,ma:!1});if(u.Lc){E=!1;try{if("undefined"===typeof SharedWorker){var S=
URL.createObjectURL(new Blob(["let handler = null;\n      self.addEventListener('message', function(e){\n        if (handler !== null){\n          clearTimeout(handler);\n          handler = null;\n        }\n        switch (e.data) {\n          case 'START':\n          case 'DONE':\n            handler = setTimeout(function(){\n              self.postMessage('TICK');\n            }, "+u.Ib.toString()+");\n            break;\n          case 'STOP':\n            break;\n        };\n      }, false);"],
{type:"text/javascript"})),I=new Worker(S);I.addEventListener("message",a);k={Zc:I,port:I};x.Fb=!0}else{var J=URL.createObjectURL(new Blob(["let handler = null;\n      onconnect = function(e) {\n        const port = e.ports[0];\n        port.addEventListener('message', function(e) {\n          \n          if (handler !== null){\n            clearTimeout(handler);\n            handler = null;\n          }\n          switch (e.data) {\n            case 'START':\n            case 'DONE':\n              handler = setTimeout(function(){\n                port.postMessage('TICK');\n              }, "+
u.Ib.toString()+");\n              break;\n            case 'STOP':\n              break;\n          };\n          \n        });\n        \n        port.start();\n      } // end onconnect()"],{type:"text/javascript"})),v=new SharedWorker(J);v.port.start();v.port.addEventListener("message",a);k={Zc:v,port:v.port};x.Eb=!0}E=!0}catch(q){}E&&("onvisibilitychange"in document?document.addEventListener("visibilitychange",r):(window.addEventListener("blur",K),window.addEventListener("focus",m)),x.Cb=!0)}A=
"undefined"!==typeof yb},m:function(){t();x.Cb&&("onvisibilitychange"in document?document.removeEventListener("visibilitychange",r):(window.removeEventListener("blur",K),window.removeEventListener("focus",m)),x.Cb=!1);x.Eb?(k.port.close(),x.Eb=!1):x.Fb&&(k.Zc.terminate(),x.Fb=!1);Object.assign(x,{X:!0,da:!1,ma:!1});y=null},bg:function(){return x.X},update:function(E){Object.assign(u,E)},Te:function(E){x.da||O.s({});n();x.ma=!0;y=E;x.X&&c()},stop:t};return O}(),Bb=function(){var a=0,c=null,d=null,
h=null,t=null;return{s:function(n,l){a=n.length;c=l;d=n;h=new Float32Array(a);t=new Float32Array(a)},ke:function(){return t},df:function(n,l,r){n.forEach(function(f,u){var y=Math.min(1,d[u]*r*(l+.33*(1-l)));f=y*f+(1-y)*h[u];h[u]=f;t[u]=c[u](f)})}}}(),V={VERSION:"1.2.5",ia:[],hb:!1,ib:!1,gb:!1,Ba:!0,Aa:!1,ready:!1,initialized:!1},Cb={facingMode:"user",idealWidth:800,idealHeight:600,minWidth:240,maxWidth:1280,minHeight:240,maxHeight:1280,isAudio:!0},b={neuralNetworkPath:"jeelizFaceExpressionsNNC.json",
bc:"../../",ja:0,width:512,height:512,gf:30,jd:[.6,5.8],ga:[.06,.08,.15],We:.7,Ue:2,Ve:[2,2,2],threshold:.9,zd:[.03,1],rf:20,re:!1,fb:[2,7],H:{Cc:[3,7],quality:[0,6],position:[0,7],rotation:[5,7]},Uc:11,Sc:1,Ce:1,fc:[.1,.01],Re:[.4,-.7,-.4],Se:[.3,0,0],Ud:!1,Ad:.001,hc:[Math.PI/10,Math.PI/6],ad:[.1,.4],bd:[.009,.02],cd:[.02,.04],Kb:5,Dc:.05,yd:[.2,.2,.15,.15,.15,.15,1,.2,.15,.15,.2],De:[Ia.bind(null,.1,.7),Ia.bind(null,.1,.7),Ia.bind(null,0,.4),Ia.bind(null,0,.4),Ia.bind(null,.05,.6),Ia.bind(null,
.05,.6),Ia.bind(null,.1,.3),Ia.bind(null,.3,.5),Ia.bind(null,.7,.8),Ia.bind(null,.7,.8),Ia.bind(null,.15,.5)]};V.get_nMorphs=function(){return b.Uc};var Db=null,Eb=null,Fb=null,Gb=[];
function Hb(){function a(){1===++L&&(Bb.s(b.yd,b.De),c(),V.ready=!0,V.ia.forEach(function(z){z()}),V.ia.splice(0,V.ia.length),d(),L=0)}function c(){O=Da();E=new Uint8Array(x*x*4);V.get_morphTargetInfluences=function(){return O};V.get_morphTargetInfluencesStabilized=function(){return Bb.ke()};V.set_morphUpdateCallback=function(z){S=z};V.get_rotation=function(){return v};V.get_positionScale=function(){var z=m.qd.he();z.qb(!1);z=z.Qb();M[0]=1-z[1][0];M[1]=z[2][0];M[2]=z[3][0]*g[0];return M};V.get_rotationStabilized=
function(){return C};V.switch_sleep=function(z){P!==H.Vb||z?P=z?H.Vb:H.play:d()};V.on_detect=function(z){z(aa.R);aa.Lb.push(z)};V.is_detected=function(){return aa.R};V.set_animateDelay=function(z){k=z;Ab.update({ja:k})}}function d(){P!==H.play&&(P=H.play,Ab.stop(),h())}function h(){var z,F;return Aa(new ua(new ka(function(ca){switch(ca.Z){case 1:a:{if("VIDEO"===e.element.nodeName){var Y=e.element.currentTime-la;0>Y&&(la=e.element.currentTime);if(1E3*Y<b.rf)break a;la+=Y}e.pa.refresh();Y=w.Ac();Y[0]===
e.Fa[0]&&Y[1]===e.Fa[1]||w.ud()}z=yb.je();F=0;case 2:if(!(F<z)){ca.Z=4;break}Y=m;var qa=A;G.set("s53");Sa.U();Y.Pa.P();e.pa.g(0);Y.ab.g(1);N.l(!1,!1);Y.Pa.g(0);qa.K(Y.Pa);b.re?Y=Q.Qe(I,E).then(t):(Q.Pe(I,E),t(),Y=Promise.resolve());ca.Z=3;return{value:Y};case 3:++F;ca.Z=2;break;case 4:Y=m,Sa.U(),K.P(),G.set("s56"),Y.ab.g(0),N.l(!1,!1),Y=yb.ae(),R=3*(1-Y)+1*Y,yb.ff(),V.Ba&&(Sa.jf(),G.set("s52"),e.pa.g(0),N.l(!1,!1),D.enable(D.BLEND),D.blendFunc(D.SRC_ALPHA,D.ONE),K.g(0),N.l(!1,!1),D.disable(D.BLEND)),
D.flush(),P!==H.Vb&&Ab.Te(h),ca.Z=0}})))}function t(){r();if(!b.Ud&&aa.R)for(var z=0;3>z;++z){var F=l(z+b.H.rotation[0],b.H.rotation[1]);F=(2*F-1)*b.Re[z];F+=b.Se[z];J[z]=F}n();z=Date.now();F=z-W.Pc;var ca=l(b.H.quality[0],b.H.quality[1]);W.$c=Ia(b.ad[0],b.ad[1],ca);ca=l(b.H.position[0],b.H.position[1]);var Y=l(b.H.position[0]+1,b.H.position[1]),qa=l(b.H.position[0]+2,b.H.position[1]);W.gd=1-Ia(b.cd[0],b.cd[1],Math.sqrt(ca*ca+Y*Y+qa*qa)/F);ca=W.na[0]-J[0];Y=W.na[1]-J[1];qa=W.na[2]-J[2];F=Math.sqrt(ca*
ca+Y*Y+qa*qa)/F;W.na[0]=J[0];W.na[1]=J[1];W.na[2]=J[2];W.dd=1-Ia(b.bd[0],b.bd[1],F);W.O=W.$c*W.gd*W.dd;W.Pc=z;W.Oc[W.Gb]=W.O;W.Gb=(W.Gb+1)%b.Kb;for(z=0;z<b.Kb;++z)W.O=Math.min(W.Oc[z],W.O);Bb.df(O,W.O,R);S&&S(W.O,R);if(aa.R)for(z=b.fc[1]*W.O+b.fc[0]*(1-W.O),z*=R,F=0;3>F;++F)v[F]=z*J[F]+(1-z)*v[F],C[F]=v[F];else z=Date.now()*b.Ad,q[0]=b.hc[0]*Math.sin(z),q[1]=b.hc[1]*Math.cos(z),C[0]=q[0],C[1]=q[1],C[2]=q[2]}function n(){var z=l(b.H.Cc[0],b.H.Cc[1]);aa.Qa=b.Dc*z+(1-b.Dc)*aa.Qa;.6<aa.Qa&&!aa.R?(aa.Lb.forEach(function(F){F(!0)}),
aa.R=!0):.4>aa.Qa&&aa.R&&(aa.Lb.forEach(function(F){F(!1)}),aa.R=!1)}function l(z,F){z+=x*F;return(E[4*z]+E[4*z+1]+E[4*z+2]+E[4*z+3])/1020}function r(){O.forEach(function(z,F){if(aa.R){z=(b.Sc+F)%x;var ca=b.Ce+Math.floor((b.Sc+F)/x);ca=x-1-ca;z=l(z,ca);O[F]=z}else O[F]=0})}function f(z){A=new jb({Ta:z.layers,Pb:"gpuRaw",Mb:function(F){var ca=m;ca.ab.nd(1);D.viewport(0,0,1,1);G.set("s54");G.L("u36",W.O);G.od("u37",zb.get());G.od("u38",b.ga);N.l(!1,!1);ca.qd.nd(1);G.set("s55");G.L("u36",W.O);ca.ab.g(0);
N.l(!1,!1);I=F}});z=A.ge();z!==p&&(p=z,w.Fc(),m.Pa.resize(p,p),w.pd());x=A.me();a()}var u=-1,y=-1,p=64,k=b.ja,A=null,x=0,g=null,m={},K=null,O=null,E=null,S=null,I=null,J=[0,0,0],v=[0,0,0],q=[0,0,0],C=[0,0,0],M=[0,0,0],R=1,e={qf:[.5,.5],pf:[.5,.5],element:null,pa:null,Fa:[-1,-1]},L=0,H={Qd:-4,Fe:-3,cg:-2,Vb:-1,play:0},P=H.Fe,aa={Qa:0,R:!1,Lb:[]},W={O:1,gd:1,$c:1,dd:1,na:[0,0,0],Pc:Date.now(),Oc:new Float32Array(b.Kb),Gb:0},la=0,w={Fc:function(){u=b.width;y=b.height;zb.s({Wa:b.Ve,Vc:b.Ue,ha:u,xb:y,
hd:b.We,ga:b.ga,kd:!0});g=[1,u/y]},pd:function(){G.I("s52",[{type:"1i",name:"u1",value:0}]);G.I("s53",[{type:"1i",name:"u1",value:0},{type:"1i",name:"u39",value:1},{type:"2f",name:"u40",value:g}]);G.I("s56",[{type:"1i",name:"u39",value:0},{type:"2f",name:"u40",value:g},{type:"3f",name:"u41",value:[0,.5,1]}]);G.I("s54",[{type:"1i",name:"u42",value:0},{type:"1i",name:"u39",value:1},{type:"1f",name:"u43",value:b.jd[0]},{type:"1f",name:"u44",value:b.jd[1]},{type:"1f",name:"u45",value:b.gf},{type:"1f",
name:"u46",value:b.threshold},{type:"1f",name:"u47",value:g[0]}]);G.I("s55",[{type:"1i",name:"u1",value:0},{type:"1i",name:"u5",value:1},{type:"2f",name:"u48",value:b.zd}])},Nd:function(){G.ec([{id:"s52",name:"_",za:"attribute vec2 a0;uniform vec2 u49,u50;varying vec2 vv0;void main(){gl_Position=vec4(a0,0.,1.),vv0=u50+u49*a0;}",Da:["a0"],sa:[2],h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",i:["u1","u49","u50"],precision:"lowp"},{id:"s53",name:"_",h:"uniform sampler2D u1;varying vec2 vv0;void main(){gl_FragColor=texture2D(u1,vv0);}",
za:"attribute vec2 a0;uniform sampler2D u39;uniform vec2 u40,u49,u50;const vec2 f=vec2(.25,.5),i=vec2(.75,.5),e=vec2(.5,.5);varying vec2 vv0;void main(){vec4 a=texture2D(u39,f);vec2 b=a.gb,c=a.a*u40,d=a0*.5+e,h=b+(d-e)*c;vv0=u50+u49*2.*(h-.5),gl_Position=vec4(a0,0.,1.);}",Da:["a0"],sa:[2],i:["u1","u39","u40","u49","u50"],precision:"lowp"},{id:"s54",name:"_",za:"attribute vec2 a0;void main(){gl_Position=vec4(a0,0.,1.);}",h:"uniform sampler2D u42,u39;uniform vec3 u37,u38;uniform float u43,u44,u45,u46,u47,u36;varying vec2 vv0;const vec4 e=vec4(.25,.25,.25,.25);void main(){vec4 c=texture2D(u42,vec2(.4375,.9375)),d=texture2D(u42,vec2(.5625,.9375));float f=dot(c-d,e);bool g=f>u46;vec4 a=texture2D(u39,vec2(.5,.5));g?a.r=2.:a.r>u45?a.r=0.:a.r>1.9&&(a.a>u44||a.a<u43)?a.r=0.:a.r>1.9?a.r+=1.:0.;if(a.r<.9)a.gba=u37,a.r=1.;else{float h=dot(e,texture2D(u42,vec2(.0625,.9375))),i=dot(e,texture2D(u42,vec2(.1875,.9375))),j=dot(e,texture2D(u42,vec2(.3125,.9375))),b;if(a.r>1.9)b=1.-u36;else b=1.,a.r=0.;float k=a.a*u47;a.gba+=vec3(h,i,j)*u38*b*k;}gl_FragColor=a;}",
i:"u42 u39 u37 u43 u44 u45 u46 u38 u47 u36".split(" ")},{id:"s56",name:"_",h:"uniform sampler2D u39;uniform vec3 u41;uniform vec2 u40;varying vec2 vv0;const vec2 i=vec2(1.,1.);void main(){vec4 f=texture2D(u39,vec2(.25,.5));vec2 g=f.gb;float j=f.a;vec2 a=j*u40,c=g+a,d=g;d-=a/2.,c-=a/2.;vec2 k=.5*(d+c),h=step(d,vv0)*step(vv0,c);float l=h.x*h.y;vec2 b=2.*abs(k-vv0)/a;b=pow(b,3.*i),gl_FragColor=vec4(l*u41*max(b.x,b.y),1.);}",i:["u39","u40","u41"],precision:"lowp"},{id:"s55",name:"_",h:"uniform sampler2D u1,u5;uniform vec2 u48;uniform float u36;const vec4 f=vec4(1.,1.,1.,1.);varying vec2 vv0;void main(){vec4 a=texture2D(u1,vv0),b=texture2D(u5,vv0);float c=(1.-u36)*(u48.y-u48.x)+u48.x;gl_FragColor=mix(b,a,c*f);}",
i:["u1","u5","u48","u36"]}])},qe:function(z){var F=new Float32Array([0,.5,.5,0]);z.Pa=Q.instance({isPot:!0,isFloat:!1,width:p});F={width:1,height:1,isFloat:!0,isPot:!1,array:F};z.ab=Va.instance(F);z.qd=Va.instance(F)},Od:function(){e.pa=Q.instance({C:e.element,isPot:!1,isFloat:!1,isFlipY:!0});K=Q.instance({isPot:!1,isFloat:!1,width:u,height:y})},s:function(){w.Od();w.qe(m);Ab.s({Lc:!1,ja:k});yb.s({Jb:0,n:b.fb[1]-b.fb[0]+1,Rc:b.fb[0]});Fb?f(Fb):Ca(function(z){z=JSON.parse(z);f(z)})},m:function(){Ab.stop();
A&&(A.m(),A=null);P=H.Qd},Jd:function(z){V.hb&&V.hb();var F={video:{facingMode:{ideal:Cb.facingMode},width:{min:Cb.minWidth,max:Cb.maxWidth,ideal:Cb.idealWidth},height:{min:Cb.minHeight,max:Cb.maxHeight,ideal:Cb.idealHeight}},audio:Cb.isAudio};qb(F,Cb.deviceId);xb(function(ca,Y){Db=Y;V.ib&&V.ib();z(ca)},function(){window.eb&&window.eb("WEBCAM_UNAVAILABLE")},F)},Qc:function(z,F){w.Nd();e.element=z;Eb=e.element;w.ud();w.Fc();w.pd();w.s();F&&F()},Ac:function(){var z=[-1,-1],F=e.element;"VIDEO"===F.nodeName?
(z[0]=F.videoWidth,z[1]=F.videoHeight):(z[0]=F.width,z[1]=F.height);return z},ud:function(){var z=w.Ac();e.Fa[0]=z[0];e.Fa[1]=z[1];Ua.La().width=z[0];Ua.La().height=z[1];b.width=z[0];b.height=z[1];var F=e.qf,ca=e.pf,Y=z[1]/z[0];z=Ua.J()/Ua.A();Y>z?1>=Y?F[0]*=Y:F[1]/=Y:(F[0]*=Y,Y=1/z,F[0]*=Y,F[1]*=Y);F[1]*=z;F=[{type:"2f",name:"u49",value:F},{type:"2f",name:"u50",value:ca}];G.I("s53",[{type:"1i",name:"u1",value:0}].concat(F));G.I("s52",F)}};Gb.push(w);return w}V.onLoad=function(a){V.ready?a():V.ia.push(a)};
V.switch_displayVideo=function(a){V.Ba=a;V.Aa&&(V.Aa.style.display=V.Ba?"block":"none")};V.onWebcamAsk=function(a){V.hb=a};V.onContextLost=function(a){V.gb=a};V.onWebcamGet=function(a){V.ib=a};V.destroy=function(){Ab.m();Eb&&Eb.srcObject&&Eb.srcObject.getTracks().forEach(function(a){a.stop()});Gb.forEach(function(a){a.m()});Gb.splice(0);Ua.m();V.switch_displayVideo(!1);V.initialized=!1;V.ia.splice(0)};V.set_size=function(a,c){b.width=a;b.height=c};V.get_size=function(){return{width:b.width,height:b.height}};
V.get_videoStream=function(){return Db};V.get_video=function(){return Eb};V.get_cv=function(){return Ua.La()};V.set_color=function(a){G.I("s56",[{type:"3f",name:"u41",value:a}])};
V.init=function(a){var c=Hb(),d=a.callbackReady?a.callbackReady:function(n){console.log("ERR:",n)},h=a.callbackReady?a.callbackReady.bind(null,!1):!1;if(a.canvasId||a.canvas){var t=a.canvas?a.canvas:document.getElementById(a.canvasId);if(t)if(V.initialized)d("ALREADY_INITIALIZED");else{V.initialized=!0;window.eb=d?function(n){d(n);window.eb=!1}:!1;a.NNCPath&&(b.bc=a.NNCPath);"undefined"!==typeof a.NNC&&(Fb="string"===typeof a.NNC?JSON.parse(a.NNC):a.NNC);h&&V.ia.push(h);if(!Ua.s({ob:t,width:b.width,
height:b.height,debug:!1,Bb:!1,Wc:function(){V.gb&&V.gb()},premultipliedAlpha:!1}))return d("GL_INCOMPATIBLE"),!1;V.Aa=Ua.La();V.Ba||(V.Aa.style.display="none");N.s();Sa.s();G.s();Q.s();D.depthFunc(D.LEQUAL);D.clearDepth(1);a.videoSettings&&a.videoSettings.videoElement?c.Qc(a.videoSettings.videoElement,!1):(a.videoSettings&&Object.assign(Cb,a.videoSettings),c.Jd(function(n){c.Qc(n,!1)}));return!0}else d("INVALID_CANVAS")}else d("NO_CANVASID")};const JEELIZFACEEXPRESSIONS=V;
if(typeof(module)!=='undefined'){module.exports=JEELIZFACEEXPRESSIONS;}
/* eslint-enable */
